// Copyright (c) 2022 FlyByWire Simulations
// SPDX-License-Identifier: GPL-3.0

// These need to align with the IDs in the Presets C++ WASM.
// WASM: src/presets/src/Aircraft/AircraftProcedures.h
export const AircraftPresetsList: { index: number, name: string }[] = [
    { index: 1, name: 'Cold & Dark' },
    { index: 2, name: 'Turnaround' },
    { index: 3, name: 'Ready for Pushback' },
    { index: 4, name: 'Ready for Taxi' },
    { index: 5, name: 'Ready for Takeoff' },
];

// These are defined in the presets' wasm C++ code and can be
// printed to the console by compiling the c++ with --debug
// The console output can then be easily pasted here and transformed to
// the correct syntax.
// WASM: src/presets/src/Aircraft/AircraftProcedures.h
export const StepDescription = new Map([
    [0, ''],
    [101, 'BAT1 On'],
    [102, 'BAT2 On'],
    [103, 'EXT PWR On'],
    [104, 'APU Master On'],
    [105, 'APU Start On'],
    [106, 'AC BUS Avail Check'],
    [107, 'Nav & Logo Lt On'],
    [108, 'ADIRS 1 Nav'],
    [109, 'ADIRS 2 Nav'],
    [110, 'ADIRS 3 Nav'],
    [111, 'GND CTL On'],
    [112, 'Crew Oxy On'],
    [113, 'NO SMOKING Auto'],
    [114, 'EMER EXT Lt Arm'],
    [115, 'APU Avail Check'],
    [116, 'APU Bleed On'],
    [200, 'EXT PWR Off'],
    [201, 'FUEL PUMP 2 On'],
    [202, 'FUEL PUMP 5 On'],
    [203, 'FUEL PUMP 1 On'],
    [204, 'FUEL PUMP 4 On'],
    [205, 'FUEL PUMP 3 On'],
    [206, 'FUEL PUMP 6 On'],
    [207, 'Radar PWS On'],
    [208, 'Transponder On'],
    [209, 'ATC ALT RPTG On'],
    [210, 'TCAS TRAFFIC ABV'],
    [211, 'COCKPIT DOOR LCK'],
    [212, 'Strobe Auto'],
    [213, 'Beacon On'],
    [214, 'SEAT BELTS On'],
    [215, 'ADIRS 1 Await Alignment'],
    [216, 'ADIRS 2 Await Alignment'],
    [217, 'ADIRS 3 Await Alignment'],
    [300, 'ENG MODE SEL START'],
    [301, 'ENG 2 ON'],
    [302, 'ENG 2 Avail Check'],
    [303, 'ENG 1 ON'],
    [304, 'ENG 1 Avail Check'],
    [305, 'ENG MODE SEL NORM'],
    [306, 'APU Bleed Off'],
    [307, 'APU Master Off'],
    [308, 'Autobrake Max'],
    [309, 'Spoiler Arm'],
    [310, 'Rudder Trim Reset'],
    [311, 'Flaps 1'],
    [312, 'NOSE Lt Taxi'],
    [313, 'RWY TURN OFF Lt L On'],
    [314, 'RWY TURN OFF Lt R On'],
    [400, 'WX Radar On'],
    [401, 'WX Radar Mode'],
    [402, 'TCAS Switch TA/RA'],
    [403, 'NOSE Lt Takeoff'],
    [404, 'LL Lt L On'],
    [405, 'LL Lt R On'],
    [406, 'LL Lt L Off'],
    [407, 'LL Lt R Off'],
    [408, 'NOSE Lt Takeoff'],
    [409, 'TCAS Switch TA/RA'],
    [410, 'WX Radar Off'],
    [411, 'WX Radar Mode'],
    [315, 'NOSE Lt Taxi'],
    [316, 'RWY TURN OFF Lt L Off'],
    [317, 'RWY TURN OFF Lt R Off'],
    [318, 'Autobrake Off'],
    [319, 'Spoiler Disarm'],
    [320, 'Rudder Trim Reset'],
    [321, 'Flaps 0'],
    [322, 'ENG 1 Off'],
    [323, 'ENG 2 Off'],
    [324, 'ENG 1 N1 <3%'],
    [325, 'ENG 2 N1 <3%'],
    [218, 'Strobe Off'],
    [219, 'Beacon Off'],
    [220, 'SEAT BELTS Off'],
    [221, 'Radar PWS Off'],
    [222, 'Transponder Off'],
    [223, 'ATC ALT RPTG Off'],
    [224, 'TCAS TRAFFIC ABV'],
    [225, 'COCKPIT DOOR OP'],
    [226, 'FUEL PUMP 2 Off'],
    [227, 'FUEL PUMP 5 Off'],
    [228, 'FUEL PUMP 1 Off'],
    [229, 'FUEL PUMP 4 Off'],
    [230, 'FUEL PUMP 3 Off'],
    [231, 'FUEL PUMP 6 Off'],
    [117, 'NO SMOKING Off'],
    [118, 'EMER EXT Lt Off'],
    [119, 'Crew Oxy Off'],
    [120, 'GND CTL Off'],
    [121, 'ADIRS 3 Off'],
    [122, 'ADIRS 2 Off'],
    [123, 'ADIRS 1 Off'],
    [124, 'Nav & Logo Lt Off'],
    [125, 'APU Bleed Off'],
    [126, 'APU Master Off'],
    [127, 'EXT PWR Off'],
    [128, 'BAT2 Off'],
    [129, 'BAT1 Off'],
    [130, 'AC BUS Off Check'],

]);
