export enum LateralMode {
    NONE = 0,
    HDG = 10,
    TRACK = 11,
    NAV = 20,
    LOC_CPT = 30,
    LOC_TRACK = 31,
    LAND = 32,
    FLARE = 33,
    ROLL_OUT = 34,
    RWY = 40,
    RWY_TRACK = 41,
    GA_TRACK = 50,
}

export enum VerticalMode {
    NONE= 0,
    ALT = 0,
    ALT_CPT = 1,
    OP_CLB = 2,
    OP_DES = 3,
    VS = 4,
    FPA = 5,
    ALT_CST = 0,
    ALT_CST_CPT = 1,
    CLB = 2,
    DES = 3,
    GS_CPT = 0,
    GS_TRACK = 1,
    LAND = 2,
    FLARE = 3,
    ROLL_OUT = 4,
    SRS = 0,
    SRS_GA = 1,
}
