export const EFB_CLEAR_STATE = 'EFB_CLEAR_STATE';

export const SET_TOD_DATA = 'SET_TOD_DATA';
export const ADD_TOD_GROUND_SPEED = 'ADD_TOD_GROUND_SPEED';
export const REMOVE_TOD_GROUND_SPEED = 'REMOVE_TOD_GROUND_SPEED';
export const SET_TOD_GROUND_SPEED = 'SET_TOD_GROUND_SPEED';
export const CLEAR_TOD_GROUND_SPEED = 'CLEAR_TOD_GROUND_SPEED';

export const ADD_ACTIVE_BUTTON = 'ADD_ACTIVE_BUTTON';
export const REMOVE_ACTIVE_BUTTON = 'REMOVE_ACTIVE_BUTTON';
export const SET_ACTIVE_BUTTONS = 'SET_ACTIVE_BUTTONS';

export const ADD_DISABLED_BUTTON = 'ADD_DISABLED_BUTTON';
export const REMOVE_DISABLED_BUTTON = 'REMOVE_DISABLED_BUTTON';

export const SET_TUG_REQUEST_ONLY = 'SET_TUG_REQUEST_ONLY';
export const SET_PUSH_BACK_WAIT_TIMER_HANDLE = 'SET_PUSH_BACK_WAIT_TIMER_HANDLE';
