export enum GroundServices {
    TOGGLE_PUSHBACK = "K:TOGGLE_PUSHBACK",
    PUSHBACK_TURN_LEFT = "K:KEY_TUG_HEADING",
    PUSHBACK_TURN_RIGHT="",
    TOGGLE_JETWAY="",
    TOGGLE_STAIRS="",
    TOGGLE_CARGO="",
    TOGGLE_CATERING="",
    TOGGLE_FUEL=""
}
