export enum GroundServices {
    TOGGLE_PUSHBACK = "K:TOGGLE_PUSHBACK",
    PUSHBACK_TURN = "K:KEY_TUG_HEADING",
    TOGGLE_JETWAY= "K:TOGGLE_JETWAY",
    TOGGLE_STAIRS="K:TOGGLE_RAMPTRUCK",
    TOGGLE_CARGO="K:REQUEST_LUGGAGE",
    TOGGLE_CATERING="K:REQUEST_CATERING",
    TOGGLE_FUEL="K:REQUEST_FUEL_KEY"
}
