#ifndef RTW_HEADER_FmgcComputer_h_
#define RTW_HEADER_FmgcComputer_h_
#include "rtwtypes.h"
#include "FmgcComputer_types.h"

class FmgcComputer final
{
 public:
  struct rtDW_MATLABFunction_FmgcComputer_T {
    real_T timeSinceCondition;
    boolean_T output;
  };

  struct rtDW_MATLABFunction_FmgcComputer_e_T {
    boolean_T previousInput;
    boolean_T previousInput_not_empty;
  };

  struct rtDW_MATLABFunction_FmgcComputer_ll_T {
    real_T remainingTriggerTime;
    boolean_T previousInput;
  };

  struct D_Work_FmgcComputer_T {
    base_fmgc_ap_fd_logic_outputs Delay_DSTATE;
    boolean_T Delay_DSTATE_p;
    boolean_T Delay_DSTATE_k;
    boolean_T Memory_PreviousInput;
    boolean_T Memory_PreviousInput_g;
    boolean_T Memory_PreviousInput_g1;
    boolean_T Memory_PreviousInput_p;
    boolean_T Memory_PreviousInput_k;
    boolean_T Memory_PreviousInput_c;
    boolean_T Memory_PreviousInput_b;
    boolean_T Memory_PreviousInput_l;
    boolean_T Memory_PreviousInput_d;
    boolean_T Memory_PreviousInput_dv;
    boolean_T Memory_PreviousInput_f;
    boolean_T Memory_PreviousInput_i;
    boolean_T Memory_PreviousInput_e;
    boolean_T Memory_PreviousInput_f2;
    boolean_T Memory_PreviousInput_i1;
    boolean_T Memory_PreviousInput_ip;
    boolean_T Memory_PreviousInput_a;
    boolean_T Memory_PreviousInput_cv;
    boolean_T Memory_PreviousInput_lq;
    boolean_T Memory_PreviousInput_n;
    boolean_T Memory_PreviousInput_ne;
    boolean_T Memory_PreviousInput_cb;
    boolean_T Memory_PreviousInput_fg;
    boolean_T Memory_PreviousInput_m;
    boolean_T Memory_PreviousInput_ec;
    boolean_T Memory_PreviousInput_nt;
    boolean_T Memory_PreviousInput_b3;
    boolean_T Memory_PreviousInput_ae;
    boolean_T Memory_PreviousInput_ev;
    boolean_T Memory_PreviousInput_fm;
    boolean_T Memory_PreviousInput_nu;
    boolean_T Memory_PreviousInput_as;
    boolean_T Memory_PreviousInput_cu;
    boolean_T Memory_PreviousInput_h;
    boolean_T Runtime_MODE;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_d5;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_dtd;
    rtDW_MATLABFunction_FmgcComputer_T sf_MATLABFunction_jc;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_lr;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_mrn;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_ft;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_aba;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_ih;
    rtDW_MATLABFunction_FmgcComputer_T sf_MATLABFunction_j3;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_fe;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_cx;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_ds;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_nd;
    rtDW_MATLABFunction_FmgcComputer_T sf_MATLABFunction_gbq;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_ms;
    rtDW_MATLABFunction_FmgcComputer_T sf_MATLABFunction_khd;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_f0h;
    rtDW_MATLABFunction_FmgcComputer_T sf_MATLABFunction_go;
    rtDW_MATLABFunction_FmgcComputer_T sf_MATLABFunction_dba;
    rtDW_MATLABFunction_FmgcComputer_T sf_MATLABFunction_mu;
    rtDW_MATLABFunction_FmgcComputer_T sf_MATLABFunction_bs;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_pe;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_iv;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_mo;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_fz;
    rtDW_MATLABFunction_FmgcComputer_T sf_MATLABFunction_n5;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_ax;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_p3;
    rtDW_MATLABFunction_FmgcComputer_T sf_MATLABFunction_ir;
    rtDW_MATLABFunction_FmgcComputer_T sf_MATLABFunction_dt;
    rtDW_MATLABFunction_FmgcComputer_T sf_MATLABFunction_ee;
    rtDW_MATLABFunction_FmgcComputer_T sf_MATLABFunction_hw;
    rtDW_MATLABFunction_FmgcComputer_ll_T sf_MATLABFunction_bq;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_hu;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_h0;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_jle;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_m1;
    rtDW_MATLABFunction_FmgcComputer_T sf_MATLABFunction_ge4;
    rtDW_MATLABFunction_FmgcComputer_T sf_MATLABFunction_pr;
    rtDW_MATLABFunction_FmgcComputer_T sf_MATLABFunction_is;
    rtDW_MATLABFunction_FmgcComputer_T sf_MATLABFunction_p4;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_k4;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_ma;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_ol;
    rtDW_MATLABFunction_FmgcComputer_T sf_MATLABFunction_ah;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_gb;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_at;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_h4;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_di2;
    rtDW_MATLABFunction_FmgcComputer_T sf_MATLABFunction_hdw;
    rtDW_MATLABFunction_FmgcComputer_ll_T sf_MATLABFunction_aw;
    rtDW_MATLABFunction_FmgcComputer_T sf_MATLABFunction_kz;
    rtDW_MATLABFunction_FmgcComputer_ll_T sf_MATLABFunction_mn;
    rtDW_MATLABFunction_FmgcComputer_T sf_MATLABFunction_jl;
    rtDW_MATLABFunction_FmgcComputer_ll_T sf_MATLABFunction_db;
    rtDW_MATLABFunction_FmgcComputer_T sf_MATLABFunction_fm;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_gk;
    rtDW_MATLABFunction_FmgcComputer_T sf_MATLABFunction_fx;
    rtDW_MATLABFunction_FmgcComputer_T sf_MATLABFunction_hz;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_pn;
    rtDW_MATLABFunction_FmgcComputer_T sf_MATLABFunction_mtz;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_fn;
    rtDW_MATLABFunction_FmgcComputer_T sf_MATLABFunction_lm;
    rtDW_MATLABFunction_FmgcComputer_T sf_MATLABFunction_hv;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_eb2;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_kb;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_es;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_hh;
    rtDW_MATLABFunction_FmgcComputer_T sf_MATLABFunction_ha;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_fa;
    rtDW_MATLABFunction_FmgcComputer_T sf_MATLABFunction_op;
    rtDW_MATLABFunction_FmgcComputer_T sf_MATLABFunction_fo;
    rtDW_MATLABFunction_FmgcComputer_T sf_MATLABFunction_crq;
    rtDW_MATLABFunction_FmgcComputer_T sf_MATLABFunction_mq;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_d3;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_d;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_kq;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_o;
    rtDW_MATLABFunction_FmgcComputer_T sf_MATLABFunction_k;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_c;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_h;
    rtDW_MATLABFunction_FmgcComputer_e_T sf_MATLABFunction_i;
    rtDW_MATLABFunction_FmgcComputer_T sf_MATLABFunction_f;
    rtDW_MATLABFunction_FmgcComputer_T sf_MATLABFunction;
  };

  struct ExternalInputs_FmgcComputer_T {
    fmgc_inputs in;
  };

  struct ExternalOutputs_FmgcComputer_T {
    fmgc_outputs out;
  };

  struct Parameters_FmgcComputer_T {
    base_fmgc_ap_fd_logic_outputs fmgc_ap_fd_logic_output_MATLABStruct;
    base_fmgc_discrete_outputs fmgc_discrete_output_MATLABStruct;
    real_T BitfromLabel_bit;
    real_T BitfromLabel1_bit;
    real_T BitfromLabel2_bit;
    real_T BitfromLabel2_bit_l;
    real_T BitfromLabel_bit_n;
    real_T BitfromLabel1_bit_i;
    real_T BitfromLabel_bit_c;
    real_T BitfromLabel_bit_m;
    real_T BitfromLabel1_bit_g;
    real_T BitfromLabel_bit_f;
    real_T BitfromLabel1_bit_n;
    real_T BitfromLabel_bit_k;
    real_T BitfromLabel2_bit_b;
    real_T BitfromLabel1_bit_l;
    real_T BitfromLabel_bit_ff;
    real_T BitfromLabel2_bit_f;
    real_T BitfromLabel_bit_l;
    real_T BitfromLabel2_bit_e;
    real_T BitfromLabel_bit_a;
    real_T BitfromLabel_bit_cs;
    real_T BitfromLabel_bit_e;
    real_T BitfromLabel_bit_p;
    real_T BitfromLabel1_bit_o;
    real_T BitfromLabel2_bit_i;
    real_T BitfromLabel4_bit;
    real_T BitfromLabel3_bit;
    real_T BitfromLabel_bit_fu;
    real_T BitfromLabel2_bit_m;
    real_T BitfromLabel1_bit_p;
    real_T BitfromLabel_bit_nk;
    real_T BitfromLabel_bit_o;
    real_T BitfromLabel1_bit_ls;
    real_T BitfromLabel_bit_j;
    real_T BitfromLabel_bit_es;
    real_T BitfromLabel1_bit_m;
    real_T BitfromLabel_bit_et;
    real_T BitfromLabel1_bit_ng;
    real_T BitfromLabel2_bit_n;
    real_T BitfromLabel3_bit_f;
    real_T BitfromLabel1_bit_p2;
    real_T BitfromLabel2_bit_fr;
    real_T BitfromLabel1_bit_a;
    real_T BitfromLabel2_bit_k;
    real_T BitfromLabel4_bit_g;
    real_T BitfromLabel3_bit_e;
    real_T BitfromLabel_bit_jh;
    real_T BitfromLabel2_bit_p;
    real_T BitfromLabel1_bit_g3;
    real_T BitfromLabel2_bit_is;
    real_T BitfromLabel_bit_cq;
    real_T BitfromLabel2_bit_p5;
    real_T BitfromLabel1_bit_mi;
    real_T BitfromLabel2_bit_j;
    real_T BitfromLabel1_bit_nv;
    real_T BitfromLabel2_bit_i1;
    real_T BitfromLabel4_bit_d;
    real_T BitfromLabel1_bit_b;
    real_T BitfromLabel2_bit_kr;
    real_T BitfromLabel4_bit_i;
    real_T BitfromLabel_bit_b;
    real_T BitfromLabel2_bit_n0;
    real_T BitfromLabel3_bit_d;
    real_T BitfromLabel2_bit_nl;
    real_T BitfromLabel3_bit_g;
    real_T BitfromLabel1_bit_aw;
    real_T BitfromLabel3_bit_gv;
    real_T BitfromLabel_bit_kq;
    real_T BitfromLabel2_bit_ie;
    real_T BitfromLabel_bit_i;
    real_T BitfromLabel1_bit_i5;
    real_T BitfromLabel2_bit_o;
    real_T BitfromLabel3_bit_l;
    real_T BitfromLabel4_bit_f;
    real_T BitfromLabel1_bit_d;
    real_T BitfromLabel3_bit_j;
    real_T BitfromLabel4_bit_o;
    real_T BitfromLabel5_bit;
    real_T BitfromLabel6_bit;
    real_T CompareToConstant_const;
    real_T CompareToConstant1_const;
    real_T CompareToConstant1_const_k;
    real_T CompareToConstant2_const;
    real_T CompareToConstant3_const;
    real_T CompareToConstant4_const;
    real_T CompareToConstant5_const;
    real_T CompareToConstant6_const;
    real_T CompareToConstant2_const_b;
    real_T CompareToConstant1_const_i;
    real_T CompareToConstant_const_l;
    real_T CompareToConstant_const_g;
    real_T CompareToConstant_const_d;
    real_T CompareToConstant3_const_i;
    real_T CompareToConstant5_const_k;
    real_T CompareToConstant_const_a;
    real_T CompareToConstant_const_o;
    real_T CompareToConstant_const_m;
    real_T CompareToConstant1_const_b;
    real_T CompareToConstant2_const_n;
    real_T CompareToConstant1_const_n;
    real_T CompareToConstant1_const_h;
    real_T CompareToConstant_const_mh;
    real_T CompareToConstant2_const_j;
    real_T CompareToConstant_const_l5;
    real_T CompareToConstant_const_f;
    real_T CompareToConstant1_const_o;
    real_T CompareToConstant2_const_g;
    real_T CompareToConstant1_const_n2;
    real_T CompareToConstant2_const_i;
    real_T CompareToConstant2_const_h;
    real_T CompareToConstant_const_c;
    real_T CompareToConstant_const_e;
    real_T CompareToConstant1_const_m;
    real_T CompareToConstant_const_ce;
    real_T MTrigNode_isRisingEdge;
    real_T MTrigNode_isRisingEdge_j;
    real_T MTrigNode_isRisingEdge_g;
    real_T MTrigNode_isRisingEdge_k;
    real_T MTrigNode_retriggerable;
    real_T MTrigNode_retriggerable_p;
    real_T MTrigNode_retriggerable_f;
    real_T MTrigNode_retriggerable_pd;
    real_T ConfirmNode1_timeDelay;
    real_T ConfirmNode_timeDelay;
    real_T ConfirmNode1_timeDelay_l;
    real_T ConfirmNode_timeDelay_i;
    real_T ConfirmNode_timeDelay_h;
    real_T ConfirmNode_timeDelay_o;
    real_T ConfirmNode_timeDelay_f;
    real_T ConfirmNode_timeDelay_j;
    real_T ConfirmNode_timeDelay_d;
    real_T ConfirmNode_timeDelay_l;
    real_T ConfirmNode1_timeDelay_d;
    real_T ConfirmNode_timeDelay_a;
    real_T ConfirmNode2_timeDelay;
    real_T ConfirmNode_timeDelay_j5;
    real_T ConfirmNode_timeDelay_a3;
    real_T ConfirmNode_timeDelay_dw;
    real_T ConfirmNode_timeDelay_a2;
    real_T ConfirmNode_timeDelay_d1;
    real_T ConfirmNode_timeDelay_g;
    real_T ConfirmNode_timeDelay_h4;
    real_T ConfirmNode_timeDelay_e;
    real_T ConfirmNode_timeDelay_es;
    real_T ConfirmNode_timeDelay_lk;
    real_T ConfirmNode_timeDelay_at;
    real_T ConfirmNode_timeDelay_b;
    real_T ConfirmNode_timeDelay_ll;
    real_T ConfirmNode_timeDelay_n;
    real_T ConfirmNode_timeDelay_dy;
    real_T ConfirmNode_timeDelay_ib;
    real_T ConfirmNode_timeDelay_ob;
    real_T ConfirmNode_timeDelay_a3g;
    real_T ConfirmNode_timeDelay_m;
    real_T ConfirmNode_timeDelay_mu;
    real_T ConfirmNode_timeDelay_ht;
    real_T ConfirmNode_timeDelay_gz;
    real_T MTrigNode_triggerDuration;
    real_T MTrigNode_triggerDuration_n;
    real_T MTrigNode_triggerDuration_b;
    real_T MTrigNode_triggerDuration_bh;
    SignStatusMatrix EnumeratedConstant1_Value;
    SignStatusMatrix EnumeratedConstant_Value;
    SignStatusMatrix EnumeratedConstant1_Value_d;
    fmgc_flight_phase EnumeratedConstant_Value_a;
    fmgc_flight_phase EnumeratedConstant1_Value_dg;
    fmgc_flight_phase EnumeratedConstant_Value_p;
    fmgc_flight_phase EnumeratedConstant1_Value_m;
    fmgc_flight_phase EnumeratedConstant2_Value;
    fmgc_flight_phase EnumeratedConstant_Value_pq;
    fmgc_flight_phase EnumeratedConstant1_Value_i;
    fmgc_flight_phase EnumeratedConstant_Value_m;
    fmgc_flight_phase EnumeratedConstant1_Value_k;
    fmgc_flight_phase EnumeratedConstant2_Value_p;
    fmgc_flight_phase EnumeratedConstant_Value_c;
    fmgc_flight_phase EnumeratedConstant1_Value_c;
    fmgc_flight_phase EnumeratedConstant_Value_ad;
    real32_T A429ValueOrDefault_defaultValue;
    real32_T A429ValueOrDefault1_defaultValue;
    real32_T A429ValueOrDefault_defaultValue_n;
    real32_T A429ValueOrDefault1_defaultValue_p;
    real32_T A429ValueOrDefault_defaultValue_l;
    real32_T A429ValueOrDefault1_defaultValue_b;
    real32_T A429ValueOrDefault1_defaultValue_m;
    real32_T A429ValueOrDefault_defaultValue_e;
    real32_T A429ValueOrDefault_defaultValue_ek;
    real32_T A429ValueOrDefault1_defaultValue_f;
    real32_T A429ValueOrDefault2_defaultValue;
    real32_T A429ValueOrDefault3_defaultValue;
    real32_T A429ValueOrDefault_defaultValue_p;
    real32_T A429ValueOrDefault1_defaultValue_d;
    real32_T A429ValueOrDefault_defaultValue_o;
    real32_T A429ValueOrDefault_defaultValue_b;
    real32_T A429ValueOrDefault_defaultValue_pm;
    real32_T A429ValueOrDefault1_defaultValue_j;
    real32_T A429ValueOrDefault2_defaultValue_j;
    real32_T A429ValueOrDefault_defaultValue_a;
    real32_T A429ValueOrDefault_defaultValue_m;
    real32_T A429ValueOrDefault_defaultValue_h;
    real32_T A429ValueOrDefault_defaultValue_mo;
    real32_T A429ValueOrDefault_defaultValue_ht;
    real32_T A429ValueOrDefault_defaultValue_i;
    real32_T A429ValueOrDefault_defaultValue_g;
    real32_T A429ValueOrDefault_defaultValue_k;
    boolean_T SRFlipFlop1_initial_condition;
    boolean_T SRFlipFlop_initial_condition;
    boolean_T SRFlipFlop1_initial_condition_n;
    boolean_T SRFlipFlop_initial_condition_b;
    boolean_T SRFlipFlop_initial_condition_h;
    boolean_T SRFlipFlop_initial_condition_i;
    boolean_T SRFlipFlop_initial_condition_c;
    boolean_T SRFlipFlop_initial_condition_d;
    boolean_T SRFlipFlop_initial_condition_iz;
    boolean_T SRFlipFlop_initial_condition_l;
    boolean_T SRFlipFlop_initial_condition_j;
    boolean_T SRFlipFlop_initial_condition_h5;
    boolean_T SRFlipFlop_initial_condition_e;
    boolean_T SRFlipFlop_initial_condition_cs;
    boolean_T SRFlipFlop_initial_condition_o;
    boolean_T SRFlipFlop_initial_condition_g;
    boolean_T SRFlipFlop_initial_condition_n;
    boolean_T SRFlipFlop_initial_condition_of;
    boolean_T SRFlipFlop_initial_condition_on;
    boolean_T SRFlipFlop1_initial_condition_b;
    boolean_T SRFlipFlop_initial_condition_ja;
    boolean_T SRFlipFlop_initial_condition_li;
    boolean_T SRFlipFlop1_initial_condition_i;
    boolean_T SRFlipFlop_initial_condition_be;
    boolean_T SRFlipFlop_initial_condition_jv;
    boolean_T SRFlipFlop_initial_condition_p;
    boolean_T SRFlipFlop_initial_condition_lz;
    boolean_T SRFlipFlop_initial_condition_oz;
    boolean_T SRFlipFlop_initial_condition_pr;
    boolean_T SRFlipFlop_initial_condition_ce;
    boolean_T SRFlipFlop_initial_condition_hs;
    boolean_T SRFlipFlop_initial_condition_dp;
    boolean_T SRFlipFlop1_initial_condition_o;
    boolean_T SRFlipFlop_initial_condition_n1;
    boolean_T PulseNode_isRisingEdge;
    boolean_T ConfirmNode1_isRisingEdge;
    boolean_T PulseNode2_isRisingEdge;
    boolean_T PulseNode1_isRisingEdge;
    boolean_T ConfirmNode_isRisingEdge;
    boolean_T ConfirmNode1_isRisingEdge_n;
    boolean_T PulseNode_isRisingEdge_k;
    boolean_T PulseNode1_isRisingEdge_m;
    boolean_T PulseNode2_isRisingEdge_n;
    boolean_T ConfirmNode_isRisingEdge_h;
    boolean_T PulseNode_isRisingEdge_p;
    boolean_T ConfirmNode_isRisingEdge_c;
    boolean_T ConfirmNode_isRisingEdge_p;
    boolean_T ConfirmNode_isRisingEdge_l;
    boolean_T ConfirmNode_isRisingEdge_hu;
    boolean_T PulseNode_isRisingEdge_l;
    boolean_T ConfirmNode_isRisingEdge_f;
    boolean_T PulseNode2_isRisingEdge_e;
    boolean_T PulseNode3_isRisingEdge;
    boolean_T PulseNode1_isRisingEdge_c;
    boolean_T ConfirmNode_isRisingEdge_e;
    boolean_T ConfirmNode1_isRisingEdge_g;
    boolean_T ConfirmNode_isRisingEdge_d;
    boolean_T PulseNode_isRisingEdge_a;
    boolean_T ConfirmNode2_isRisingEdge;
    boolean_T PulseNode_isRisingEdge_h;
    boolean_T ConfirmNode_isRisingEdge_m;
    boolean_T PulseNode_isRisingEdge_c;
    boolean_T ConfirmNode_isRisingEdge_hj;
    boolean_T PulseNode_isRisingEdge_f;
    boolean_T ConfirmNode_isRisingEdge_mf;
    boolean_T PulseNode_isRisingEdge_i;
    boolean_T PulseNode1_isRisingEdge_e;
    boolean_T PulseNode3_isRisingEdge_l;
    boolean_T PulseNode2_isRisingEdge_b;
    boolean_T ConfirmNode_isRisingEdge_a;
    boolean_T PulseNode_isRisingEdge_j;
    boolean_T PulseNode3_isRisingEdge_e;
    boolean_T PulseNode2_isRisingEdge_i;
    boolean_T PulseNode1_isRisingEdge_k;
    boolean_T ConfirmNode_isRisingEdge_co;
    boolean_T PulseNode1_isRisingEdge_cs;
    boolean_T PulseNode2_isRisingEdge_o;
    boolean_T ConfirmNode_isRisingEdge_n;
    boolean_T PulseNode_isRisingEdge_g;
    boolean_T ConfirmNode_isRisingEdge_at;
    boolean_T ConfirmNode_isRisingEdge_nd;
    boolean_T ConfirmNode_isRisingEdge_ea;
    boolean_T ConfirmNode_isRisingEdge_hux;
    boolean_T ConfirmNode_isRisingEdge_nf;
    boolean_T ConfirmNode_isRisingEdge_lj;
    boolean_T PulseNode_isRisingEdge_d;
    boolean_T PulseNode1_isRisingEdge_ky;
    boolean_T PulseNode2_isRisingEdge_bh;
    boolean_T PulseNode3_isRisingEdge_n;
    boolean_T ConfirmNode_isRisingEdge_lu;
    boolean_T PulseNode_isRisingEdge_b;
    boolean_T PulseNode3_isRisingEdge_d;
    boolean_T ConfirmNode_isRisingEdge_fc;
    boolean_T PulseNode_isRisingEdge_o;
    boolean_T PulseNode3_isRisingEdge_j;
    boolean_T ConfirmNode_isRisingEdge_j;
    boolean_T PulseNode_isRisingEdge_n;
    boolean_T ConfirmNode_isRisingEdge_ca;
    boolean_T PulseNode_isRisingEdge_fw;
    boolean_T ConfirmNode_isRisingEdge_ep;
    boolean_T PulseNode1_isRisingEdge_b;
    boolean_T PulseNode_isRisingEdge_lz;
    boolean_T ConfirmNode_isRisingEdge_g;
    boolean_T ConfirmNode_isRisingEdge_gr;
    boolean_T ConfirmNode_isRisingEdge_o;
    boolean_T PulseNode1_isRisingEdge_kl;
    boolean_T PulseNode2_isRisingEdge_f;
    boolean_T ConfirmNode_isRisingEdge_ch;
    boolean_T PulseNode1_isRisingEdge_n;
    boolean_T PulseNode2_isRisingEdge_iu;
    boolean_T PulseNode3_isRisingEdge_i;
    boolean_T PulseNode_isRisingEdge_jp;
    boolean_T PulseNode4_isRisingEdge;
    boolean_T ConfirmNode_isRisingEdge_h2;
    int8_T CompareToConstant_const_b;
    int8_T CompareToConstant_const_cq;
    int8_T CompareToConstant_const_j;
    fmgc_outputs out_Y0;
    base_fmgc_bus_outputs Constant4_Value;
    base_fmgc_logic_outputs Constant1_Value;
    base_fmgc_ap_fd_logic_outputs Delay_InitialCondition;
    real32_T Constant17_Value;
    real32_T Constant18_Value;
    real32_T Constant19_Value;
    real32_T Constant20_Value;
    real32_T Constant16_Value;
    real32_T Constant1_Value_g;
    real32_T Constant2_Value;
    real32_T Constant22_Value;
    real32_T Constant26_Value;
    real32_T Constant27_Value;
    real32_T Constant28_Value;
    real32_T Constant11_Value;
    real32_T Constant12_Value;
    real32_T Constant13_Value;
    real32_T Constant14_Value;
    real32_T Constant15_Value;
    real32_T Constant32_Value;
    real32_T Constant1_Value_k;
    real32_T Constant11_Value_m;
    real32_T Constant2_Value_n;
    boolean_T Delay_InitialCondition_g;
    boolean_T Logic_table[16];
    boolean_T Logic_table_h[16];
    boolean_T Constant_Value;
    boolean_T Logic_table_f[16];
    boolean_T Delay_InitialCondition_gu;
    boolean_T Logic_table_n[16];
    boolean_T Logic_table_b[16];
    boolean_T Constant_Value_j;
    boolean_T Logic_table_hz[16];
    boolean_T Logic_table_d[16];
    boolean_T Constant_Value_l;
    boolean_T Constant2_Value_p;
    boolean_T Logic_table_k[16];
    boolean_T Logic_table_p[16];
    boolean_T Logic_table_c[16];
    boolean_T Logic_table_pl[16];
    boolean_T Logic_table_o[16];
    boolean_T Logic_table_c2[16];
    boolean_T Logic_table_i[16];
    boolean_T Logic_table_g[16];
    boolean_T Logic_table_a[16];
    boolean_T Logic_table_ku[16];
    boolean_T Constant_Value_d;
    boolean_T Logic_table_g4[16];
    boolean_T Logic_table_j[16];
    boolean_T Logic_table_pk[16];
    boolean_T Logic_table_nz[16];
    boolean_T Logic_table_ob[16];
    boolean_T Logic_table_ny[16];
    boolean_T Logic_table_ns[16];
    boolean_T Logic_table_kw[16];
    boolean_T Logic_table_he[16];
    boolean_T Logic_table_cv[16];
    boolean_T Logic_table_jq[16];
    boolean_T Logic_table_l[16];
    boolean_T Logic_table_dr[16];
    boolean_T Logic_table_d3[16];
    boolean_T Logic_table_fi[16];
    boolean_T Logic_table_kg[16];
    boolean_T Logic_table_ds[16];
    boolean_T Constant_Value_m;
    boolean_T Constant1_Value_i;
    boolean_T Constant10_Value;
    boolean_T Constant3_Value;
    boolean_T Constant4_Value_g;
    boolean_T Constant5_Value;
    boolean_T Constant6_Value;
    boolean_T Constant7_Value;
    boolean_T Constant8_Value;
    boolean_T Constant9_Value;
    int8_T Constant_Value_o;
  };

  FmgcComputer(FmgcComputer const&) = delete;
  FmgcComputer& operator= (FmgcComputer const&) & = delete;
  FmgcComputer(FmgcComputer &&) = delete;
  FmgcComputer& operator= (FmgcComputer &&) = delete;
  void setExternalInputs(const ExternalInputs_FmgcComputer_T *pExternalInputs_FmgcComputer_T)
  {
    FmgcComputer_U = *pExternalInputs_FmgcComputer_T;
  }

  const ExternalOutputs_FmgcComputer_T &getExternalOutputs() const
  {
    return FmgcComputer_Y;
  }

  void initialize();
  void step();
  static void terminate();
  FmgcComputer();
  ~FmgcComputer();
 private:
  ExternalInputs_FmgcComputer_T FmgcComputer_U;
  ExternalOutputs_FmgcComputer_T FmgcComputer_Y;
  D_Work_FmgcComputer_T FmgcComputer_DWork;
  static Parameters_FmgcComputer_T FmgcComputer_P;
  static void FmgcComputer_MATLABFunction_Reset(rtDW_MATLABFunction_FmgcComputer_T *localDW);
  static void FmgcComputer_MATLABFunction(boolean_T rtu_u, real_T rtu_Ts, boolean_T rtu_isRisingEdge, real_T
    rtu_timeDelay, boolean_T *rty_y, rtDW_MATLABFunction_FmgcComputer_T *localDW);
  static void FmgcComputer_MATLABFunction_m_Reset(rtDW_MATLABFunction_FmgcComputer_e_T *localDW);
  static void FmgcComputer_MATLABFunction_i(boolean_T rtu_u, boolean_T rtu_isRisingEdge, boolean_T *rty_y,
    rtDW_MATLABFunction_FmgcComputer_e_T *localDW);
  static void FmgcComputer_MATLABFunction_j(const base_arinc_429 *rtu_u, real32_T rtu_default, real32_T *rty_y);
  static void FmgcComputer_MATLABFunction_f(const base_arinc_429 *rtu_u, boolean_T *rty_y);
  static void FmgcComputer_MATLABFunction_k(const base_arinc_429 *rtu_u, real_T rtu_bit, uint32_T *rty_y);
  static void FmgcComputer_MATLABFunction_g(const base_arinc_429 *rtu_u, boolean_T *rty_y);
  static void FmgcComputer_MATLABFunction_pz_Reset(rtDW_MATLABFunction_FmgcComputer_ll_T *localDW);
  static void FmgcComputer_MATLABFunction_d(boolean_T rtu_u, real_T rtu_Ts, boolean_T *rty_y, real_T rtp_isRisingEdge,
    real_T rtp_retriggerable, real_T rtp_triggerDuration, rtDW_MATLABFunction_FmgcComputer_ll_T *localDW);
  static void FmgcComputer_MATLABFunction_gy(const boolean_T rtu_u[19], real32_T *rty_y);
};

#endif

