#ifndef FmgcOuterLoops_h_
#define FmgcOuterLoops_h_
#include "rtwtypes.h"
#include "FmgcOuterLoops_types.h"
#include <cstring>

class FmgcOuterLoops final
{
 public:
  struct rtDW_LagFilter_FmgcOuterLoops_T {
    real_T pY;
    real_T pU;
    boolean_T pY_not_empty;
    boolean_T pU_not_empty;
  };

  struct rtDW_MATLABFunction_FmgcOuterLoops_j_T {
    real_T limit;
    real_T lastPsi;
    real_T limitDeltaPsi;
    boolean_T lastPsi_not_empty;
  };

  struct rtDW_Chart_FmgcOuterLoops_T {
    uint8_T is_active_c10_FmgcOuterLoops;
    uint8_T is_c10_FmgcOuterLoops;
  };

  struct rtDW_LagFilter_FmgcOuterLoops_j_T {
    real_T pY;
    real_T pU;
    boolean_T pY_not_empty;
    boolean_T pU_not_empty;
  };

  struct rtDW_RateLimiter_FmgcOuterLoops_T {
    real_T pY;
    boolean_T pY_not_empty;
  };

  struct rtDW_Chart_FmgcOuterLoops_k_T {
    uint8_T is_active_c15_FmgcOuterLoops;
    uint8_T is_c15_FmgcOuterLoops;
  };

  struct rtDW_RateLimiter_FmgcOuterLoops_h_T {
    real_T pY;
    boolean_T pY_not_empty;
  };

  struct rtDW_LeadLagFilter_FmgcOuterLoops_T {
    real_T pY;
    real_T pU;
    boolean_T pY_not_empty;
    boolean_T pU_not_empty;
  };

  struct rtDW_WashoutFilter_FmgcOuterLoops_T {
    real_T pY;
    real_T pU;
    boolean_T pY_not_empty;
    boolean_T pU_not_empty;
  };

  struct rtDW_WashoutFilter_FmgcOuterLoops_o_T {
    real_T pY;
    real_T pU;
    boolean_T pY_not_empty;
    boolean_T pU_not_empty;
  };

  struct BlockIO_FmgcOuterLoops_T {
    real_T u;
  };

  struct D_Work_FmgcOuterLoops_T {
    real_T Delay_DSTATE;
    real_T Delay_DSTATE_p;
    real_T Delay_DSTATE_f;
    real_T Delay_DSTATE_i;
    real_T Delay_DSTATE_l;
    real_T Delay_DSTATE_e;
    real_T prevVerticalLaw;
    real_T prevTarget;
    real_T pY;
    real_T storage;
    real_T prevVerticalLaw_p;
    real_T prevTarget_n;
    real_T Tau;
    real_T H_bias;
    real_T pY_l;
    real_T pU;
    real_T dH_offset;
    real_T k;
    real_T maxH_dot;
    real_T pY_m;
    real_T pY_h;
    real_T storage_b;
    real_T storage_l;
    real_T limit;
    real_T pY_f;
    boolean_T Delay_DSTATE_l4[100];
    boolean_T Delay_DSTATE_n[100];
    boolean_T icLoad;
    boolean_T icLoad_f;
    boolean_T prevVerticalLaw_not_empty;
    boolean_T prevTarget_not_empty;
    boolean_T islevelOffActive;
    boolean_T pY_not_empty;
    boolean_T storage_not_empty;
    boolean_T prevVerticalLaw_not_empty_f;
    boolean_T prevTarget_not_empty_d;
    boolean_T islevelOffActive_h;
    boolean_T wasActive;
    boolean_T wasActive_not_empty;
    boolean_T pY_not_empty_a;
    boolean_T pU_not_empty;
    boolean_T wasActive_m;
    boolean_T wasActive_not_empty_l;
    boolean_T pY_not_empty_l;
    boolean_T pY_not_empty_g;
    boolean_T storage_not_empty_j;
    boolean_T storage_not_empty_p;
    boolean_T limit_not_empty;
    boolean_T pY_not_empty_p;
    rtDW_WashoutFilter_FmgcOuterLoops_T sf_WashoutFilter_mv;
    rtDW_LeadLagFilter_FmgcOuterLoops_T sf_LeadLagFilter_iz;
    rtDW_LeadLagFilter_FmgcOuterLoops_T sf_LeadLagFilter_i5;
    rtDW_WashoutFilter_FmgcOuterLoops_T sf_WashoutFilter_g;
    rtDW_LeadLagFilter_FmgcOuterLoops_T sf_LeadLagFilter_av;
    rtDW_LeadLagFilter_FmgcOuterLoops_T sf_LeadLagFilter_mr;
    rtDW_LagFilter_FmgcOuterLoops_T sf_LagFilter_ag;
    rtDW_RateLimiter_FmgcOuterLoops_h_T sf_RateLimiter_jx;
    rtDW_WashoutFilter_FmgcOuterLoops_o_T sf_WashoutFilter_hj;
    rtDW_LagFilter_FmgcOuterLoops_T sf_LagFilter_j;
    rtDW_LagFilter_FmgcOuterLoops_T sf_LagFilter_ip;
    rtDW_WashoutFilter_FmgcOuterLoops_T sf_WashoutFilter_eq;
    rtDW_LeadLagFilter_FmgcOuterLoops_T sf_LeadLagFilter_ay;
    rtDW_LeadLagFilter_FmgcOuterLoops_T sf_LeadLagFilter_k;
    rtDW_WashoutFilter_FmgcOuterLoops_T sf_WashoutFilter_h;
    rtDW_LeadLagFilter_FmgcOuterLoops_T sf_LeadLagFilter_oer;
    rtDW_LeadLagFilter_FmgcOuterLoops_T sf_LeadLagFilter_c;
    rtDW_RateLimiter_FmgcOuterLoops_h_T sf_RateLimiter_j;
    rtDW_WashoutFilter_FmgcOuterLoops_T sf_WashoutFilter_bd;
    rtDW_LagFilter_FmgcOuterLoops_T sf_LagFilter_l;
    rtDW_LagFilter_FmgcOuterLoops_T sf_LagFilter_ft;
    rtDW_LagFilter_FmgcOuterLoops_T sf_LagFilter_c;
    rtDW_LagFilter_FmgcOuterLoops_j_T sf_LagFilter_f5;
    rtDW_LagFilter_FmgcOuterLoops_j_T sf_LagFilter_fd;
    rtDW_LagFilter_FmgcOuterLoops_T sf_LagFilter_k;
    rtDW_WashoutFilter_FmgcOuterLoops_T sf_WashoutFilter_e;
    rtDW_LeadLagFilter_FmgcOuterLoops_T sf_LeadLagFilter_a;
    rtDW_LeadLagFilter_FmgcOuterLoops_T sf_LeadLagFilter_mm;
    rtDW_WashoutFilter_FmgcOuterLoops_T sf_WashoutFilter_m;
    rtDW_LeadLagFilter_FmgcOuterLoops_T sf_LeadLagFilter_oe;
    rtDW_LeadLagFilter_FmgcOuterLoops_T sf_LeadLagFilter_m;
    rtDW_WashoutFilter_FmgcOuterLoops_T sf_WashoutFilter_l;
    rtDW_WashoutFilter_FmgcOuterLoops_o_T sf_WashoutFilter_b;
    rtDW_LeadLagFilter_FmgcOuterLoops_T sf_LeadLagFilter_i;
    rtDW_LagFilter_FmgcOuterLoops_j_T sf_LagFilter_or;
    rtDW_LagFilter_FmgcOuterLoops_T sf_LagFilter_d;
    rtDW_LagFilter_FmgcOuterLoops_T sf_LagFilter_o;
    rtDW_WashoutFilter_FmgcOuterLoops_T sf_WashoutFilter_k;
    rtDW_LeadLagFilter_FmgcOuterLoops_T sf_LeadLagFilter_o;
    rtDW_LeadLagFilter_FmgcOuterLoops_T sf_LeadLagFilter_l;
    rtDW_WashoutFilter_FmgcOuterLoops_T sf_WashoutFilter;
    rtDW_LeadLagFilter_FmgcOuterLoops_T sf_LeadLagFilter_n;
    rtDW_LeadLagFilter_FmgcOuterLoops_T sf_LeadLagFilter;
    rtDW_Chart_FmgcOuterLoops_T sf_Chart_b;
    rtDW_MATLABFunction_FmgcOuterLoops_j_T sf_MATLABFunction_n;
    rtDW_RateLimiter_FmgcOuterLoops_h_T sf_RateLimiter_g;
    rtDW_LagFilter_FmgcOuterLoops_T sf_LagFilter_g;
    rtDW_LagFilter_FmgcOuterLoops_T sf_LagFilter_f;
    rtDW_Chart_FmgcOuterLoops_k_T sf_Chart_h;
    rtDW_RateLimiter_FmgcOuterLoops_T sf_RateLimiter_k;
    rtDW_RateLimiter_FmgcOuterLoops_T sf_RateLimiter_o;
    rtDW_LagFilter_FmgcOuterLoops_T sf_LagFilter_n;
    rtDW_Chart_FmgcOuterLoops_k_T sf_Chart_k;
    rtDW_RateLimiter_FmgcOuterLoops_T sf_RateLimiter_e;
    rtDW_LagFilter_FmgcOuterLoops_j_T sf_LagFilter_i;
    rtDW_LagFilter_FmgcOuterLoops_T sf_LagFilter_a;
    rtDW_LagFilter_FmgcOuterLoops_T sf_LagFilter_m;
    rtDW_Chart_FmgcOuterLoops_T sf_Chart;
    rtDW_MATLABFunction_FmgcOuterLoops_j_T sf_MATLABFunction_g;
    rtDW_LagFilter_FmgcOuterLoops_T sf_LagFilter;
  };

  struct Parameters_FmgcOuterLoops_T {
    real_T ScheduledGain_BreakpointsForDimension1[7];
    real_T ScheduledGain2_BreakpointsForDimension1[7];
    real_T ScheduledGain_BreakpointsForDimension1_f[6];
    real_T ScheduledGain1_BreakpointsForDimension1[5];
    real_T ScheduledGain3_BreakpointsForDimension1[6];
    real_T ScheduledGain_BreakpointsForDimension1_k[7];
    real_T ScheduledGain_BreakpointsForDimension1_i[3];
    real_T ScheduledGain_BreakpointsForDimension1_h[8];
    real_T ScheduledGain3_BreakpointsForDimension1_j[5];
    real_T ScheduledGain2_BreakpointsForDimension1_f[8];
    real_T ScheduledGain1_BreakpointsForDimension1_m[7];
    real_T LagFilter_C1;
    real_T LagFilter2_C1;
    real_T LagFilter_C1_o;
    real_T LagFilter1_C1;
    real_T LagFilter_C1_n;
    real_T LagFilter_C1_c;
    real_T LagFilter_C1_m;
    real_T WashoutFilter_C1;
    real_T HighPassFilter_C1;
    real_T LowPassFilter_C1;
    real_T WashoutFilter_C1_k;
    real_T HighPassFilter_C1_e;
    real_T LowPassFilter_C1_h;
    real_T LagFilter_C1_d;
    real_T WashoutFilter_C1_e;
    real_T LagFilterH_C1;
    real_T LeadLagFilter_C1;
    real_T LeadLagFilter_C1_c;
    real_T WashoutFilter_C1_a;
    real_T HighPassFilter_C1_et;
    real_T LowPassFilter_C1_j;
    real_T WashoutFilter_C1_d;
    real_T HighPassFilter_C1_n;
    real_T LowPassFilter_C1_b;
    real_T LagFilter1_C1_l;
    real_T LagFilter2_C1_i;
    real_T LagFilter3_C1;
    real_T LagFilter4_C1;
    real_T WashoutFilter1_C1;
    real_T LagFilter_C1_b;
    real_T LagFilter2_C1_m;
    real_T WashoutFilter_C1_p;
    real_T HighPassFilter_C1_n3;
    real_T LowPassFilter_C1_h2;
    real_T WashoutFilter_C1_pq;
    real_T HighPassFilter_C1_h;
    real_T LowPassFilter_C1_bh;
    real_T WashoutFilter_C1_ea;
    real_T HighPassFilter_C1_ne;
    real_T LowPassFilter_C1_n;
    real_T WashoutFilter_C1_f;
    real_T HighPassFilter_C1_g;
    real_T LowPassFilter_C1_i;
    real_T LagFilter_C1_k;
    real_T WashoutFilter_C1_m;
    real_T LagFilter_C1_h;
    real_T WashoutFilterBeta_c_C1;
    real_T LagFilter_C1_cp;
    real_T LagFilter1_C1_n;
    real_T HighPassFilter_C2;
    real_T LowPassFilter_C2;
    real_T HighPassFilter_C2_b;
    real_T LowPassFilter_C2_k;
    real_T LeadLagFilter_C2;
    real_T LeadLagFilter_C2_o;
    real_T HighPassFilter_C2_m;
    real_T LowPassFilter_C2_l;
    real_T HighPassFilter_C2_h;
    real_T LowPassFilter_C2_j;
    real_T HighPassFilter_C2_l;
    real_T LowPassFilter_C2_ld;
    real_T HighPassFilter_C2_i;
    real_T LowPassFilter_C2_o;
    real_T HighPassFilter_C2_p;
    real_T LowPassFilter_C2_a;
    real_T HighPassFilter_C2_k;
    real_T LowPassFilter_C2_p;
    real_T HighPassFilter_C3;
    real_T LowPassFilter_C3;
    real_T HighPassFilter_C3_o;
    real_T LowPassFilter_C3_f;
    real_T LeadLagFilter_C3;
    real_T LeadLagFilter_C3_l;
    real_T HighPassFilter_C3_e;
    real_T LowPassFilter_C3_a;
    real_T HighPassFilter_C3_a;
    real_T LowPassFilter_C3_o;
    real_T HighPassFilter_C3_a5;
    real_T LowPassFilter_C3_l;
    real_T HighPassFilter_C3_eq;
    real_T LowPassFilter_C3_m;
    real_T HighPassFilter_C3_oi;
    real_T LowPassFilter_C3_k;
    real_T HighPassFilter_C3_j;
    real_T LowPassFilter_C3_g;
    real_T HighPassFilter_C4;
    real_T LowPassFilter_C4;
    real_T HighPassFilter_C4_p;
    real_T LowPassFilter_C4_d;
    real_T LeadLagFilter_C4;
    real_T LeadLagFilter_C4_a;
    real_T HighPassFilter_C4_g;
    real_T LowPassFilter_C4_e;
    real_T HighPassFilter_C4_j;
    real_T LowPassFilter_C4_o;
    real_T HighPassFilter_C4_n;
    real_T LowPassFilter_C4_c;
    real_T HighPassFilter_C4_pz;
    real_T LowPassFilter_C4_n;
    real_T HighPassFilter_C4_m;
    real_T LowPassFilter_C4_p;
    real_T HighPassFilter_C4_jw;
    real_T LowPassFilter_C4_k;
    real_T DiscreteDerivativeVariableTs_Gain;
    real_T DiscreteTimeIntegratorVariableTs_Gain;
    real_T VS_Gain;
    real_T DiscreteDerivativeVariableTs1_Gain;
    real_T DiscreteDerivativeVariableTs_Gain_k;
    real_T VS_Gain_c;
    real_T VS_Gain_a;
    real_T VS_Gain_k;
    real_T VS_Gain_j;
    real_T VS_Gain_n;
    real_T VS_Gain_b;
    real_T VS_Gain_d;
    real_T RateLimiterVariableTs_InitialCondition;
    real_T DiscreteDerivativeVariableTs_InitialCondition;
    real_T RateLimiterVariableTs_InitialCondition_j;
    real_T DiscreteTimeIntegratorVariableTs_InitialCondition;
    real_T RateLimiterVariableTs_InitialCondition_b;
    real_T RateLimiterVariableTs2_InitialCondition;
    real_T RateLimiterVariableTs_InitialCondition_l;
    real_T DiscreteDerivativeVariableTs1_InitialCondition;
    real_T RateLimiterVariableTs_InitialCondition_a;
    real_T DiscreteDerivativeVariableTs_InitialCondition_e;
    real_T RateLimiterVariableTs1_InitialCondition;
    real_T RateLimiterVariableTs_InitialCondition_d;
    real_T DiscreteTimeIntegratorVariableTs_LowerLimit;
    real_T ScheduledGain_Table[7];
    real_T ScheduledGain2_Table[7];
    real_T ScheduledGain_Table_e[6];
    real_T ScheduledGain1_Table[5];
    real_T ScheduledGain3_Table[6];
    real_T ScheduledGain_Table_a[7];
    real_T ScheduledGain_Table_ak[3];
    real_T ScheduledGain_Table_j[8];
    real_T ScheduledGain3_Table_b[5];
    real_T ScheduledGain2_Table_j[8];
    real_T ScheduledGain1_Table_g[7];
    real_T DiscreteTimeIntegratorVariableTs_UpperLimit;
    real_T Subsystem_Value;
    real_T Subsystem_Value_e;
    real_T CompareToConstant5_const;
    real_T CompareToConstant2_const;
    real_T CompareToConstant_const;
    real_T CompareToConstant1_const;
    real_T CompareToConstant4_const;
    real_T CompareToConstant_const_f;
    real_T CompareToConstant1_const_a;
    real_T CompareToConstant5_const_k;
    real_T CompareToConstant7_const;
    real_T CompareToConstant_const_n;
    real_T CompareToConstant6_const;
    real_T CompareToConstant2_const_c;
    real_T CompareToConstant6_const_n;
    real_T CompareToConstant5_const_ko;
    real_T CompareToConstant2_const_f;
    real_T CompareToConstant_const_j;
    real_T CompareToConstant4_const_k;
    real_T CompareToConstant8_const;
    real_T CompareToConstant6_const_o;
    real_T CompareToConstant5_const_e;
    real_T CompareToConstant2_const_a;
    real_T CompareToConstant_const_o;
    real_T CompareToConstant4_const_kg;
    real_T RateLimiterVariableTs_lo;
    real_T RateLimiterVariableTs_lo_f;
    real_T RateLimiterVariableTs_lo_m;
    real_T RateLimiterVariableTs2_lo;
    real_T RateLimiterVariableTs_lo_d;
    real_T RateLimiterVariableTs_lo_k;
    real_T RateLimiterVariableTs1_lo;
    real_T RateLimiterVariableTs_lo_h;
    real_T RateLimiterVariableTs_up;
    real_T RateLimiterVariableTs_up_m;
    real_T RateLimiterVariableTs_up_k;
    real_T RateLimiterVariableTs2_up;
    real_T RateLimiterVariableTs_up_h;
    real_T RateLimiterVariableTs_up_l;
    real_T RateLimiterVariableTs1_up;
    real_T RateLimiterVariableTs_up_j;
    boolean_T CompareToConstant_const_a;
    boolean_T CompareToConstant_const_l;
    real_T Gain1_Gain;
    real_T Gain_Gain;
    real_T Gain1_Gain_n;
    real_T Gain_Gain_l;
    real_T Gain1_Gain_i;
    real_T Gain_Gain_e;
    real_T Gain5_Gain;
    real_T Constant1_Value;
    real_T Gain_Gain_p;
    real_T Saturation_UpperSat;
    real_T Saturation_LowerSat;
    real_T Gain2_Gain;
    real_T Gain1_Gain_e;
    real_T Gain1_Gain_k;
    real_T Gain_Gain_j;
    real_T Gain_Gain_h;
    real_T Constant3_Value;
    real_T Constant3_Value_o;
    real_T Constant3_Value_i;
    real_T Constant_Value;
    real_T Saturation_UpperSat_e;
    real_T Saturation_LowerSat_e;
    real_T Gain4_Gain;
    real_T Gain1_Gain_c;
    real_T Gain2_Gain_n;
    real_T Saturation1_UpperSat;
    real_T Saturation1_LowerSat;
    real_T Constant3_Value_c;
    real_T beta_Value;
    real_T beta_Value_j;
    real_T beta_Value_h;
    real_T beta_Value_jb;
    real_T beta_Value_k;
    real_T Constant_Value_j;
    real_T Saturation_UpperSat_m;
    real_T Saturation_LowerSat_g;
    real_T Gain7_Gain;
    real_T Gain1_Gain_a;
    real_T Gain_Gain_g;
    real_T Gain1_Gain_ca;
    real_T beta1_Value;
    real_T beta1_Value_h;
    real_T beta1_Value_e;
    real_T beta1_Value_m;
    real_T beta1_Value_g;
    real_T beta1_Value_b;
    real_T Constant_Value_c;
    real_T Saturation_UpperSat_k;
    real_T Saturation_LowerSat_m;
    real_T Gain3_Gain;
    real_T Constant1_Value_f;
    real_T Constant_Value_g;
    real_T Constant_Value_d;
    real_T Gain6_Gain;
    real_T Switch1_Threshold;
    real_T Constant1_Value_h;
    real_T Gain5_Gain_o;
    real_T Constant_Value_p;
    real_T Gain6_Gain_j;
    real_T Switch1_Threshold_a;
    real_T Constant1_Value_l;
    real_T Gain5_Gain_ob;
    real_T Y_Y0;
    real_T Gain1_Gain_b;
    real_T Saturation1_UpperSat_i;
    real_T Saturation1_LowerSat_b;
    real_T Constant1_Value_b;
    real_T Constant_Value_n;
    real_T Gain6_Gain_f;
    real_T Switch1_Threshold_e;
    real_T Constant1_Value_m;
    real_T Gain5_Gain_e;
    real_T Constant_Value_a;
    real_T Gain6_Gain_l;
    real_T Switch1_Threshold_l;
    real_T Constant1_Value_k;
    real_T Gain5_Gain_f;
    real_T Switch_Threshold;
    real_T Gain1_Gain_o;
    real_T Gain2_Gain_h;
    real_T Gain1_Gain_g;
    real_T Gain6_Gain_lb;
    real_T Constant_Value_k;
    real_T Constant1_Value_c;
    real_T Gain1_Gain_j;
    real_T Constant2_Value;
    real_T Gain6_Gain_h;
    real_T Gain5_Gain_c;
    real_T Switch_Threshold_b;
    real_T Constant_Value_db;
    real_T Constant1_Value_cz;
    real_T Gain1_Gain_oc;
    real_T Constant2_Value_h;
    real_T Gain6_Gain_g;
    real_T Gain5_Gain_a;
    real_T Switch_Threshold_h;
    real_T Switch_Threshold_e;
    real_T Gain1_Gain_ir;
    real_T Gain1_Gain_e1;
    real_T Constant_Value_kr;
    real_T Constant_Value_i;
    real_T Gain6_Gain_n;
    real_T Switch1_Threshold_p;
    real_T Constant1_Value_e;
    real_T Gain5_Gain_k;
    real_T Constant_Value_m;
    real_T Gain6_Gain_a;
    real_T Switch1_Threshold_e3;
    real_T Constant1_Value_mr;
    real_T Gain5_Gain_j;
    real_T Constant_Value_j4;
    real_T tau_Value;
    real_T zeta_Value;
    real_T Constant3_Value_l;
    real_T Gain_Gain_i;
    real_T Gain_Gain_k;
    real_T Gain1_Gain_m;
    real_T tau_Value_h;
    real_T zeta_Value_d;
    real_T Constant3_Value_h;
    real_T Constant3_Value_a;
    real_T Constant3_Value_oh;
    real_T Gain2_Gain_b;
    real_T Constant3_Value_iv;
    real_T Gain1_Gain_ek;
    real_T Saturation_UpperSat_f;
    real_T Saturation_LowerSat_eg;
    real_T Gain_Gain_o;
    real_T Constant3_Value_n;
    real_T Gain3_Gain_o;
    real_T Constant2_Value_a;
    real_T Constant3_Value_m;
    real_T Gain_Gain_j4;
    real_T Saturation_UpperSat_g;
    real_T Saturation_LowerSat_o;
    real_T Constant3_Value_d;
    real_T Gain_Gain_o0;
    real_T Gain1_Gain_or;
    real_T Gain_Gain_c;
    real_T Gain_Gain_lv;
    real_T Gain_Gain_on;
    real_T Constant3_Value_lz;
    real_T Constant3_Value_k;
    real_T Gain1_Gain_iy;
    real_T Saturation_UpperSat_n;
    real_T Saturation_LowerSat_i;
    real_T Gain2_Gain_f;
    real_T Saturation1_UpperSat_k;
    real_T Saturation1_LowerSat_by;
    real_T Gain6_Gain_p;
    real_T Constant3_Value_e;
    real_T Constant3_Value_mt;
    real_T Constant3_Value_g;
    real_T Gain1_Gain_ke;
    real_T Gain_Gain_m;
    real_T Constant1_Value_fq;
    real_T Gain5_Gain_g;
    real_T Gain_Gain_gk;
    real_T Saturation_UpperSat_nz;
    real_T Saturation_LowerSat_mb;
    real_T Constant_Value_ku;
    real_T Gain10_Gain;
    real_T Saturation2_UpperSat;
    real_T Saturation2_LowerSat;
    real_T Gain_Gain_ll;
    real_T Saturation_UpperSat_b;
    real_T Saturation_LowerSat_ie;
    real_T Gain1_Gain_p;
    real_T Saturation_UpperSat_c;
    real_T Saturation_LowerSat_n;
    real_T Constant_Value_h;
    real_T ftmintoms_Gain;
    real_T kntoms_Gain;
    real_T Saturation_UpperSat_km;
    real_T Saturation_LowerSat_c;
    real_T Gain_Gain_jz;
    real_T Constant_Value_d4;
    real_T fpmtoms_Gain;
    real_T kntoms_Gain_d;
    real_T Saturation_UpperSat_d;
    real_T Saturation_LowerSat_k;
    real_T Gain_Gain_hi;
    real_T Gain1_Gain_mz;
    real_T fpmtoms_Gain_g;
    real_T kntoms_Gain_p;
    real_T Saturation_UpperSat_h;
    real_T Saturation_LowerSat_cd;
    real_T Gain_Gain_k1;
    real_T Gain1_Gain_ah;
    real_T Constant_Value_aa;
    real_T Gain1_Gain_cy;
    real_T Gain1_Gain_of;
    real_T Gain1_Gain_im;
    real_T Gain_Gain_ch;
    real_T Gain1_Gain_f;
    real_T g_Gain;
    real_T ktstomps_Gain;
    real_T GStoGS_CAS_Gain;
    real_T _Gain;
    real_T ktstomps_Gain_g;
    real_T ug_Gain;
    real_T Gain1_Gain_b5;
    real_T Gain_Gain_b;
    real_T Constant3_Value_lq;
    real_T Constant4_Value;
    real_T Gain1_Gain_ac;
    real_T Gain_Gain_py;
    real_T Switch_Threshold_c;
    real_T Gain1_Gain_jd;
    real_T Gain_Gain_bn;
    real_T fpmtoms_Gain_f;
    real_T kntoms_Gain_dr;
    real_T Saturation_UpperSat_j;
    real_T Saturation_LowerSat_oi;
    real_T Gain_Gain_eo;
    real_T Gain1_Gain_bo;
    real_T fpmtoms_Gain_j;
    real_T kntoms_Gain_m;
    real_T Saturation_UpperSat_m2;
    real_T Saturation_LowerSat_o0;
    real_T Gain_Gain_d;
    real_T Gain1_Gain_fz;
    real_T Constant_Value_l;
    real_T Gain1_Gain_fs;
    real_T Gain1_Gain_nn;
    real_T Gain1_Gain_jp;
    real_T Gain_Gain_pm;
    real_T Gain1_Gain_ev;
    real_T g_Gain_g;
    real_T ktstomps_Gain_n;
    real_T GStoGS_CAS_Gain_g;
    real_T _Gain_m;
    real_T ktstomps_Gain_e;
    real_T ug_Gain_b;
    real_T Gain1_Gain_mf;
    real_T Gain_Gain_a;
    real_T Constant1_Value_l2;
    real_T Constant2_Value_g;
    real_T Gain1_Gain_p5;
    real_T Gain_Gain_kc;
    real_T Switch_Threshold_bv;
    real_T Gain1_Gain_bj;
    real_T Gain_Gain_gkv;
    real_T Gain_Gain_bl;
    real_T Saturation_UpperSat_i;
    real_T Saturation_LowerSat_i1;
    real_T ftmintoms_Gain_p;
    real_T kntoms_Gain_b;
    real_T Saturation_UpperSat_jq;
    real_T Saturation_LowerSat_km;
    real_T Gain_Gain_gp;
    real_T Constant2_Value_m;
    real_T Gain4_Gain_d;
    real_T Gain5_Gain_m;
    real_T uDLookupTable_tableData[4];
    real_T uDLookupTable_bp01Data[4];
    real_T kntofpm_Gain;
    real_T maxslope_Gain;
    real_T Gain1_Gain_kq;
    real_T ftmintoms_Gain_b;
    real_T kntoms_Gain_p3;
    real_T Saturation_UpperSat_i5;
    real_T Saturation_LowerSat_b;
    real_T Gain_Gain_dn;
    real_T Gain1_Gain_pm;
    real_T ftmintoms_Gain_e;
    real_T Saturation_UpperSat_hw;
    real_T Saturation_LowerSat_k1;
    real_T Gain_Gain_ed;
    real_T Gain2_Gain_m;
    real_T Constant_Value_ah;
    real_T fpmtoms_Gain_h;
    real_T kntoms_Gain_c;
    real_T Saturation_UpperSat_c2;
    real_T Saturation_LowerSat_b4;
    real_T Gain_Gain_gf;
    real_T fpmtoms_Gain_jw;
    real_T kntoms_Gain_de;
    real_T Saturation_UpperSat_cf;
    real_T Saturation_LowerSat_p;
    real_T Gain_Gain_io;
    real_T Gain1_Gain_mc;
    real_T fpmtoms_Gain_c;
    real_T kntoms_Gain_j;
    real_T Saturation_UpperSat_dm;
    real_T Saturation_LowerSat_d;
    real_T Gain_Gain_oz;
    real_T Gain1_Gain_ay;
    real_T Constant_Value_f;
    real_T Gain1_Gain_bp;
    real_T Gain1_Gain_mv;
    real_T Gain1_Gain_l;
    real_T Gain_Gain_bo;
    real_T Gain1_Gain_bu;
    real_T g_Gain_h;
    real_T ktstomps_Gain_i;
    real_T GStoGS_CAS_Gain_n;
    real_T _Gain_b;
    real_T ktstomps_Gain_l;
    real_T ug_Gain_e;
    real_T Gain1_Gain_mc2;
    real_T Gain_Gain_hg;
    real_T Constant3_Value_g0;
    real_T Constant4_Value_m;
    real_T Gain1_Gain_ft;
    real_T Gain_Gain_hu;
    real_T Switch_Threshold_o;
    real_T Gain1_Gain_mt;
    real_T Gain_Gain_ah;
    real_T fpmtoms_Gain_d;
    real_T kntoms_Gain_a;
    real_T Saturation_UpperSat_ez;
    real_T Saturation_LowerSat_a;
    real_T Gain_Gain_pa;
    real_T Gain1_Gain_n2;
    real_T fpmtoms_Gain_m;
    real_T kntoms_Gain_jl;
    real_T Saturation_UpperSat_fj;
    real_T Saturation_LowerSat_mg;
    real_T Gain_Gain_f;
    real_T Gain1_Gain_mr;
    real_T Constant_Value_ab;
    real_T Gain1_Gain_o3;
    real_T Gain1_Gain_ip;
    real_T Gain1_Gain_bd;
    real_T Gain_Gain_n;
    real_T Gain1_Gain_cyk;
    real_T g_Gain_a;
    real_T ktstomps_Gain_f;
    real_T GStoGS_CAS_Gain_a;
    real_T _Gain_j;
    real_T ktstomps_Gain_go;
    real_T ug_Gain_j;
    real_T Gain1_Gain_f2;
    real_T Gain_Gain_e3;
    real_T Constant1_Value_bi;
    real_T Constant2_Value_b;
    real_T Gain1_Gain_oj;
    real_T Gain_Gain_ip;
    real_T Switch_Threshold_m;
    real_T Gain1_Gain_pmd;
    real_T Gain_Gain_lw;
    real_T Gain_Gain_cb;
    real_T Gain_Gain_p1;
    real_T Gain2_Gain_p;
    real_T Gain1_Gain_ipx;
    real_T kn2ms_Gain;
    real_T Gain_Gain_jd;
    real_T Gain4_Gain_h;
    real_T Saturation_UpperSat_g0;
    real_T Saturation_LowerSat_j;
    real_T Gain2_Gain_ne;
    real_T Saturation_UpperSat_p;
    real_T Saturation_LowerSat_aw;
    real_T Constant_Value_jm;
    real_T Gain3_Gain_f;
    real_T Saturation_UpperSat_dj;
    real_T Saturation_LowerSat_bn;
    real_T fpmtoms_Gain_n;
    real_T kntoms_Gain_h;
    real_T Saturation_UpperSat_l;
    real_T Saturation_LowerSat_pi;
    real_T Gain_Gain_bp;
    real_T Gain2_Gain_a;
    real_T Bias_Bias;
    real_T Gain1_Gain_eg;
    real_T Bias1_Bias;
    real_T Gain_Gain_dv;
    real_T Constant_Value_j0;
    real_T fpmtoms_Gain_fo;
    real_T kntoms_Gain_o;
    real_T Saturation_UpperSat_l3;
    real_T Saturation_LowerSat_b5;
    real_T Gain_Gain_jc;
    real_T Gain1_Gain_kk;
    real_T Gain1_Gain_jq;
    real_T fpmtoms_Gain_jv;
    real_T kntoms_Gain_at;
    real_T Saturation_UpperSat_cd;
    real_T Saturation_LowerSat_in;
    real_T Gain_Gain_lm;
    real_T Gain1_Gain_gw;
    real_T Constant_Value_gw;
    real_T Gain1_Gain_iz;
    real_T Gain1_Gain_c1;
    real_T Gain1_Gain_fp;
    real_T Gain_Gain_dr;
    real_T Gain1_Gain_in;
    real_T g_Gain_gg;
    real_T ktstomps_Gain_no;
    real_T GStoGS_CAS_Gain_k;
    real_T _Gain_c;
    real_T ktstomps_Gain_d;
    real_T ug_Gain_p;
    real_T Gain1_Gain_o3k;
    real_T Gain_Gain_kp;
    real_T Gain1_Gain_ox;
    real_T Gain_Gain_dt;
    real_T Constant3_Value_ku;
    real_T ftmintoms_Gain_po;
    real_T kntoms_Gain_cf;
    real_T Saturation_UpperSat_b2;
    real_T Saturation_LowerSat_dx;
    real_T Gain_Gain_io1;
    real_T ftmintoms_Gain_d;
    real_T kntoms_Gain_cg;
    real_T Saturation_UpperSat_fo;
    real_T Saturation_LowerSat_py;
    real_T Gain_Gain_l5;
    real_T fpmtoms_Gain_jm;
    real_T kntoms_Gain_ov;
    real_T Saturation_UpperSat_dh;
    real_T Saturation_LowerSat_mv;
    real_T Gain_Gain_gg;
    real_T Gain1_Gain_bjj;
    real_T fpmtoms_Gain_k;
    real_T kntoms_Gain_i;
    real_T Saturation_UpperSat_le;
    real_T Saturation_LowerSat_h;
    real_T Gain_Gain_dj;
    real_T Gain1_Gain_br;
    real_T Constant_Value_b;
    real_T Gain1_Gain_lq;
    real_T Gain1_Gain_gc;
    real_T Gain1_Gain_b3;
    real_T Gain_Gain_kd;
    real_T Gain1_Gain_jz;
    real_T g_Gain_b;
    real_T ktstomps_Gain_gp;
    real_T GStoGS_CAS_Gain_ah;
    real_T _Gain_p;
    real_T ktstomps_Gain_a;
    real_T ug_Gain_o;
    real_T Gain1_Gain_h;
    real_T Gain_Gain_as;
    real_T Constant4_Value_h;
    real_T Constant3_Value_hk;
    real_T Gain1_Gain_f5;
    real_T Gain_Gain_fx;
    real_T Switch_Threshold_mc;
    real_T Gain1_Gain_bt;
    real_T Gain_Gain_fz;
    real_T fpmtoms_Gain_kj;
    real_T kntoms_Gain_hs;
    real_T Saturation_UpperSat_bt;
    real_T Saturation_LowerSat_f;
    real_T Gain_Gain_g0;
    real_T Gain1_Gain_kl;
    real_T fpmtoms_Gain_cj;
    real_T kntoms_Gain_n;
    real_T Saturation_UpperSat_o;
    real_T Saturation_LowerSat_pf;
    real_T Gain_Gain_is;
    real_T Gain1_Gain_pr;
    real_T Constant_Value_k3;
    real_T Gain1_Gain_n0;
    real_T Gain1_Gain_c4;
    real_T Gain1_Gain_gn;
    real_T Gain_Gain_mq;
    real_T Gain1_Gain_d;
    real_T g_Gain_l;
    real_T ktstomps_Gain_p;
    real_T GStoGS_CAS_Gain_k1;
    real_T _Gain_d;
    real_T ktstomps_Gain_c;
    real_T ug_Gain_oy;
    real_T Gain1_Gain_fb;
    real_T Gain_Gain_ni;
    real_T Constant2_Value_j;
    real_T Constant1_Value_bk;
    real_T Gain1_Gain_nd;
    real_T Gain_Gain_ci;
    real_T Switch_Threshold_g;
    real_T Gain1_Gain_hy;
    real_T Gain_Gain_e0;
    real_T Constant_Value_nc;
    real_T Constant1_Value_lb;
    real_T Constant2_Value_c;
    real_T fpmtoms_Gain_j4;
    real_T kntoms_Gain_jo;
    real_T Saturation_UpperSat_oj;
    real_T Saturation_LowerSat_ow;
    real_T Gain_Gain_fs;
    real_T Gain1_Gain_jqs;
    real_T Gain1_Gain_ekc;
    real_T fpmtoms_Gain_cr;
    real_T kntoms_Gain_drq;
    real_T Saturation_UpperSat_pi;
    real_T Saturation_LowerSat_l;
    real_T Gain_Gain_ij;
    real_T Gain1_Gain_o1;
    real_T Constant_Value_ac;
    real_T Gain1_Gain_ni;
    real_T Gain1_Gain_ku;
    real_T Gain1_Gain_jj;
    real_T Gain_Gain_c1;
    real_T Gain1_Gain_mtb;
    real_T g_Gain_k;
    real_T ktstomps_Gain_lu;
    real_T GStoGS_CAS_Gain_l;
    real_T _Gain_h;
    real_T ktstomps_Gain_k;
    real_T ug_Gain_ek;
    real_T Gain1_Gain_fc;
    real_T Gain_Gain_ib;
    real_T Gain1_Gain_kz;
    real_T Gain_Gain_nk;
    real_T Constant3_Value_hz;
    real_T ftmintoms_Gain_h;
    real_T kntoms_Gain_pu;
    real_T Saturation_UpperSat_j2;
    real_T Saturation_LowerSat_mz;
    real_T Gain_Gain_n2;
    real_T Constant_Value_k0;
    real_T ftmintoms_Gain_a;
    real_T kntoms_Gain_k;
    real_T Saturation_UpperSat_hd;
    real_T Saturation_LowerSat_l0;
    real_T Gain_Gain_ibk;
    real_T Gain2_Gain_l;
    real_T Saturation_UpperSat_go;
    real_T Saturation_LowerSat_j5;
    real_T ftmintoms_Gain_el;
    real_T kntoms_Gain_ni;
    real_T Saturation_UpperSat_d0;
    real_T Saturation_LowerSat_mo;
    real_T Gain_Gain_gd;
    real_T Constant1_Value_o;
    real_T Gain_Gain_o2;
    real_T Saturation_UpperSat_mf;
    real_T Saturation_LowerSat_fa;
    real_T Gain_Gain_cx;
    real_T Gain3_Gain_e;
    real_T Gain_Gain_jr;
    real_T Gain_Gain_cv;
    real_T Gain1_Gain_ce;
    real_T Saturation_UpperSat_n5;
    real_T Saturation_LowerSat_mt;
    real_T Constant_Value_mv;
    real_T Gain7_Gain_k;
    real_T kntofpm_Gain_k;
    real_T maxslope_Gain_k;
    boolean_T Constant1_Value_i;
    boolean_T Delay_InitialCondition;
    boolean_T Delay_InitialCondition_l;
    uint8_T ManualSwitch_CurrentSetting;
    uint8_T ManualSwitch_CurrentSetting_o;
  };

  void init();
  FmgcOuterLoops(FmgcOuterLoops const&) = delete;
  FmgcOuterLoops& operator= (FmgcOuterLoops const&) & = delete;
  FmgcOuterLoops(FmgcOuterLoops &&) = delete;
  FmgcOuterLoops& operator= (FmgcOuterLoops &&) = delete;
  void step(const real_T *rtu_in_time_dt, const real_T *rtu_in_time_simulation_time, const real_T *rtu_in_data_Theta_deg,
            const real_T *rtu_in_data_Phi_deg, const real_T *rtu_in_data_qk_deg_s, const real_T *rtu_in_data_rk_deg_s,
            const real_T *rtu_in_data_pk_deg_s, const real_T *rtu_in_data_V_ias_kn, const real_T *rtu_in_data_V_tas_kn,
            const real_T *rtu_in_data_V_mach, const real_T *rtu_in_data_V_gnd_kn, const real_T *rtu_in_data_alpha_deg,
            const real_T *rtu_in_data_beta_deg, const real_T *rtu_in_data_H_ft, const real_T *rtu_in_data_H_ind_ft,
            const real_T *rtu_in_data_H_radio_ft, const real_T *rtu_in_data_H_dot_ft_min, const real_T
            *rtu_in_data_Psi_magnetic_deg, const real_T *rtu_in_data_Psi_magnetic_track_deg, const real_T
            *rtu_in_data_Psi_true_deg, const real_T *rtu_in_data_Chi_true_deg, const real_T *rtu_in_data_bx_m_s2, const
            real_T *rtu_in_data_by_m_s2, const real_T *rtu_in_data_bz_m_s2, const real_T *rtu_in_data_nav_loc_deg, const
            real_T *rtu_in_data_nav_gs_deg, const real_T *rtu_in_data_nav_dme_nmi, const real_T
            *rtu_in_data_nav_loc_magvar_deg, const real_T *rtu_in_data_nav_loc_error_deg, const boolean_T
            *rtu_in_data_nav_gs_valid, const real_T *rtu_in_data_nav_gs_error_deg, const real_T *rtu_in_data_fms_xtk_nmi,
            const real_T *rtu_in_data_fms_tae_deg, const real_T *rtu_in_data_fms_phi_deg, const real_T
            *rtu_in_data_fms_phi_limit_deg, const real_T *rtu_in_data_fms_H_c_profile_ft, const real_T
            *rtu_in_data_fms_H_dot_c_profile_ft_min, const real_T *rtu_in_data_VLS_kn, const real_T *rtu_in_data_VMAX_kn,
            const boolean_T *rtu_in_data_on_ground, const real_T *rtu_in_data_zeta_deg, const real_T
            *rtu_in_data_total_weight_kg, const boolean_T *rtu_in_input_ap_engaged, const real_T
            *rtu_in_input_lateral_law, const real_T *rtu_in_input_vertical_law, const real_T *rtu_in_input_Psi_c_deg,
            const real_T *rtu_in_input_Chi_c_deg, const real_T *rtu_in_input_H_c_ft, const real_T
            *rtu_in_input_H_dot_c_fpm, const real_T *rtu_in_input_FPA_c_deg, const real_T *rtu_in_input_V_c_kn, const
            boolean_T *rtu_in_input_ALT_soft_mode_active, const boolean_T *rtu_in_input_TCAS_mode_active, const
            boolean_T *rtu_in_input_FINAL_DES_mode_active, const boolean_T *rtu_in_input_GS_track_mode, real_T
            *rty_out_Phi_loc_c, real_T *rty_out_Nosewheel_c, real_T *rty_out_flight_director_Theta_c_deg, real_T
            *rty_out_flight_director_Phi_c_deg, real_T *rty_out_flight_director_Beta_c_deg, real_T
            *rty_out_autopilot_Theta_c_deg, real_T *rty_out_autopilot_Phi_c_deg, real_T *rty_out_autopilot_Beta_c_deg,
            boolean_T *rty_out_flare_law_condition_Flare, real_T *rty_out_flare_law_H_dot_radio_fpm, real_T
            *rty_out_flare_law_H_dot_c_fpm, real_T *rty_out_flare_law_delta_Theta_H_dot_deg, real_T
            *rty_out_flare_law_delta_Theta_bz_deg, real_T *rty_out_flare_law_delta_Theta_bx_deg, real_T
            *rty_out_flare_law_delta_Theta_beta_c_deg);
  void reset();
  FmgcOuterLoops();
  ~FmgcOuterLoops();
 private:
  BlockIO_FmgcOuterLoops_T FmgcOuterLoops_B;
  D_Work_FmgcOuterLoops_T FmgcOuterLoops_DWork;
  static Parameters_FmgcOuterLoops_T FmgcOuterLoops_rtP;
  static void FmgcOuterLoops_MATLABFunction(real_T rtu_tau, real_T rtu_zeta, real_T *rty_k2, real_T *rty_k1);
  static void FmgcOuterLoops_LagFilter_Reset(rtDW_LagFilter_FmgcOuterLoops_T *localDW);
  static void FmgcOuterLoops_LagFilter(real_T rtu_U, real_T rtu_C1, const real_T *rtu_dt, real_T *rty_Y,
    rtDW_LagFilter_FmgcOuterLoops_T *localDW);
  static void FmgcOuterLoops_MATLABFunction_j_Init(rtDW_MATLABFunction_FmgcOuterLoops_j_T *localDW);
  static void FmgcOuterLoops_MATLABFunction_d_Reset(rtDW_MATLABFunction_FmgcOuterLoops_j_T *localDW);
  static void FmgcOuterLoops_MATLABFunction_g(const real_T *rtu_Psi_c, real_T rtu_dPsi, real_T rtu_Phi_c, real_T *rty_up,
    real_T *rty_lo, rtDW_MATLABFunction_FmgcOuterLoops_j_T *localDW);
  static void FmgcOuterLoops_Chart_Init(real_T *rty_out);
  static void FmgcOuterLoops_Chart_Reset(real_T *rty_out, rtDW_Chart_FmgcOuterLoops_T *localDW);
  static void FmgcOuterLoops_Chart(real_T rtu_right, real_T rtu_left, boolean_T rtu_use_short_path, real_T *rty_out,
    rtDW_Chart_FmgcOuterLoops_T *localDW);
  static void FmgcOuterLoops_LagFilter_e_Reset(rtDW_LagFilter_FmgcOuterLoops_j_T *localDW);
  static void FmgcOuterLoops_LagFilter_i(const real_T *rtu_U, real_T rtu_C1, const real_T *rtu_dt, real_T *rty_Y,
    rtDW_LagFilter_FmgcOuterLoops_j_T *localDW);
  static void FmgcOuterLoops_RateLimiter_Reset(rtDW_RateLimiter_FmgcOuterLoops_T *localDW);
  static void FmgcOuterLoops_RateLimiter(boolean_T rtu_u, real_T rtu_up, real_T rtu_lo, const real_T *rtu_Ts, real_T
    rtu_init, real_T *rty_Y, rtDW_RateLimiter_FmgcOuterLoops_T *localDW);
  static void FmgcOuterLoops_Chart_k_Init(real_T *rty_out);
  static void FmgcOuterLoops_Chart_c_Reset(real_T *rty_out, rtDW_Chart_FmgcOuterLoops_k_T *localDW);
  static void FmgcOuterLoops_Chart_k(real_T rtu_right, real_T rtu_left, real_T rtu_use_short_path, real_T *rty_out,
    rtDW_Chart_FmgcOuterLoops_k_T *localDW);
  static void FmgcOuterLoops_RateLimiter_f_Reset(rtDW_RateLimiter_FmgcOuterLoops_h_T *localDW);
  static void FmgcOuterLoops_RateLimiter_g(const boolean_T *rtu_u, real_T rtu_up, real_T rtu_lo, const real_T *rtu_Ts,
    real_T rtu_init, real_T *rty_Y, rtDW_RateLimiter_FmgcOuterLoops_h_T *localDW);
  static void FmgcOuterLoops_LeadLagFilter_Reset(rtDW_LeadLagFilter_FmgcOuterLoops_T *localDW);
  static void FmgcOuterLoops_LeadLagFilter(real_T rtu_U, real_T rtu_C1, real_T rtu_C2, real_T rtu_C3, real_T rtu_C4,
    const real_T *rtu_dt, real_T *rty_Y, rtDW_LeadLagFilter_FmgcOuterLoops_T *localDW);
  static void FmgcOuterLoops_WashoutFilter_Reset(rtDW_WashoutFilter_FmgcOuterLoops_T *localDW);
  static void FmgcOuterLoops_WashoutFilter(real_T rtu_U, real_T rtu_C1, const real_T *rtu_dt, real_T *rty_Y,
    rtDW_WashoutFilter_FmgcOuterLoops_T *localDW);
  static void FmgcOuterLoops_V_LSSpeedSelection1(const real_T *rtu_V_c, const real_T *rtu_VLS, real_T *rty_y);
  static void FmgcOuterLoops_SpeedProtectionSignalSelection(const ap_laws_output *rtu_in, real_T rtu_VS_FD, real_T
    rtu_VS_AP, real_T rtu_VLS_FD, real_T rtu_VLS_AP, real_T rtu_VMAX_FD, real_T rtu_VMAX_AP, real_T rtu_margin, real_T
    *rty_FD, real_T *rty_AP);
  static void FmgcOuterLoops_VSLimiter(real_T rtu_u, const ap_laws_output *rtu_in, real_T *rty_y);
  static void FmgcOuterLoops_WashoutFilter_l_Reset(rtDW_WashoutFilter_FmgcOuterLoops_o_T *localDW);
  static void FmgcOuterLoops_WashoutFilter_b(const real_T *rtu_U, real_T rtu_C1, const real_T *rtu_dt, real_T *rty_Y,
    rtDW_WashoutFilter_FmgcOuterLoops_o_T *localDW);
  static void FmgcOuterLoops_Voter1(real_T rtu_u1, real_T rtu_u2, real_T rtu_u3, real_T *rty_Y);
};

extern FmgcOuterLoops::Parameters_FmgcOuterLoops_T FmgcOuterLoops_rtP;

#endif

