export const CLEAR_SCRATCHPAD_CHARACTER = 'CLEAR_SCRATCHPAD_CHARACTER';
export const CLEAR_SCRATCHPAD = 'CLEAR_SCRATCHPAD';
export const ADD_SCRATCHPAD_MESSAGE = 'ADD_SCRATCHPAD_MESSAGE';
export const ADD_TO_SCRATCHPAD = 'ADD_TO_SCRATCHPAD';
export const ADD_PLUSMINUS_SCRATCHPAD = 'ADD_PLUSMINUS_SCRATCHPAD';
export const ADD_ARROW_SCRATCHPAD = 'ADD_ARROW_SCRATCHPAD';
