export enum lineSelectKeys {
    L1 = 'A32NX_MCDU_L_L1_BUTTON_PRESSED',
    L2 = 'A32NX_MCDU_L_L2_BUTTON_PRESSED',
    L3 = 'A32NX_MCDU_L_L3_BUTTON_PRESSED',
    L4 = 'A32NX_MCDU_L_L4_BUTTON_PRESSED',
    L5 = 'A32NX_MCDU_L_L5_BUTTON_PRESSED',
    L6 = 'A32NX_MCDU_L_L6_BUTTON_PRESSED',
    R1 = 'A32NX_MCDU_L_R1_BUTTON_PRESSED',
    R2 = 'A32NX_MCDU_L_R2_BUTTON_PRESSED',
    R3 = 'A32NX_MCDU_L_R3_BUTTON_PRESSED',
    R4 = 'A32NX_MCDU_L_R4_BUTTON_PRESSED',
    R5 = 'A32NX_MCDU_L_R5_BUTTON_PRESSED',
    R6 = 'A32NX_MCDU_L_R6_BUTTON_PRESSED',
}

export enum slewKeys {
    left= 'A32NX_MCDU_L_LARROW_BUTTON_PRESSED',
    right= 'A32NX_MCDU_L_RARROW_BUTTON_PRESSED',
    up= 'A32NX_MCDU_L_UARROW_BUTTON_PRESSED',
    down= 'A32NX_MCDU_L_DARROW_BUTTON_PRESSED',
}
