export const de = {
    AirTrafficControl: {
        Active: 'Aktiv',
        ConnectHoppieACARS: 'Hoppie ACARS verbinden',
        DisconnectHoppieACARS: 'Hoppie ACARS Verbindung trennen',
        FlightnumberIsAlreadyInUse: 'Flugnummer wird schon verwendet',
        HoppieError: 'Hoppie Fehler',
        HoppieSystemRequiresAUserIdWhichNeedsToBeSetInSettings: 'Das Hoppie-System benötigt eine Benutzer ID, welche in den Einstellungen unter ATSU / AOC festgelegt wird',
        InvalidLogonCodeUsed: 'Es wurde ein ungültiger Anmeldecode verwendet.',
        NoInformationAvailableForThisFrequency: 'FÜR DIESE FREQUENZ SIND KEINE INFORMATIONEN VERFÜGBAR',
        SetActive: 'Aktivieren',
        SetStandby: 'Standby einstellen',
        Standby: 'Standby',
        Title: 'Flugsicherung',
    },
    Checklist: { ThereAreRemainingAutofillChecklistItemsThatHaveNotYetBeenCompleted: 'Es sind noch nicht abgeschlossene Checklist-Aufgaben vorhanden' },
    Checklists: {
        AreYouSureYouWantToResetAllChecklists: 'Bist du sicher, dass du alle Checklisten zurücksetzen möchtest?',
        AreYouSureYouWantToResetChecklists: 'Bist du sicher, dass du alle Checklisten zurücksetzen möchtest?',
        ChecklistResetWarning: 'Bist du sicher, dass du die Checkliste zurücksetzen möchtest',
        MarkChecklistAsComplete: 'Checkliste als abgeschlossen markieren',
        MarkItemAsComplete: 'Checklist-Aufgabe als abgeschlossen markieren',
        ProceedToNextChecklist: 'Fahren Sie mit der nächsten Checkliste fort',
        ResetAll: 'Alles zurücksetzen',
        ResetChecklist: 'Checkliste zurücksetzen',
        TheLastChecklistIsComplete: 'Die letzte Checkliste ist abgeschlossen',
        ThereAreRemainingAutofillChecklistItemsThatHaveNotYetBeenCompleted: 'Es sind noch nicht abgeschlossene Checklist-Aufgaben vorhanden',
        Title: 'Checklisten',
    },
    Dashboard: {
        ImportantInformation: {
            Checklists: {
                NoRelevantChecklists: 'Keine relevanten Checklisten',
                Title: 'Checklisten',
            },
            GoToPage: 'Gehe zu Seite',
            Maintenance: {
                NoActiveFailures: 'Keine aktiven Ausfälle',
                Title: 'Wartung',
            },
            PinnedCharts: {
                NoPinnedCharts: 'Keine angehefteten Karten',
                Title: 'Angeheftete Karten',
            },
            TT: { RearrangeWidgets: 'Widgets neu anordnen' },
            Title: 'Wichtige Informationen',
            Weather: {
                AirPressure: 'Luftdruck',
                DewPoint: 'Taupunkt',
                Loading: 'Wird geladen…',
                Raw: 'Rohdaten',
                TT: {
                    SwitchToIconView: 'Zur Icon-Ansicht wechseln',
                    SwitchToRawMetarView: 'Zur Rohdaten-Ansicht wechseln',
                },
                Temperature: 'Temperatur',
                Title: 'Wetter',
                WindSpeed: 'Windgeschwindigkeit',
            },
        },
        Title: 'Dashboard',
        YourFlight: {
            Alternate: 'Alternative',
            AverageWind: 'Durchschnittlicher Wind',
            CompanyRoute: 'Unternehmensroute',
            CostIndex: 'Kostenindex',
            CruiseAlt: 'Reiseflughöhe',
            ImportSimBriefData: 'Importieren von SimBrief-Daten',
            Route: 'Route',
            SimBriefDataNotYetLoaded: 'SimBrief-Daten noch nicht geladen.',
            Title: 'Dein Flug',
            ZFW: 'ZFW',
        },
    },
    Dispatch: {
        Ofp: {
            ImportSimBriefData: 'Importieren von SimBrief-Daten',
            TT: {
                IncreaseFontSize: 'Schrift vergrößern',
                ReduceFontSize: 'Schrift verkleinern',
            },
            Title: 'OFP',
            YouHaveNotYetImportedAnySimBriefData: 'Du hast noch keine SimBrief-Daten importiert.',
        },
        Overview: {
            Engines: 'Triebwerke',
            MMO: 'MMO',
            MRW: 'MRW',
            MTOW: 'MTOW',
            MZFW: 'MZFW',
            MaximumCargo: 'Maximales Frachtgewicht',
            MaximumFuelCapacity: 'Maximale Treibstoffmenge',
            MaximumPassengers: 'Maximale Passagieranzahl',
            Model: 'Modell',
            Range: 'Reichweite',
            Title: 'Übersicht',
        },
        Title: 'Dispatch',
    },
    Failures: {
        Comfort: { Title: 'Komfort' },
        Compact: { Title: 'Kompakt' },
        FullSimulationOfTheFailuresBelowIsntYetGuaranteed: 'Eine vollständige Simulation der folgenden Ausfälle ist noch nicht garantiert.',
        Search: 'Suchen',
        Title: 'Ausfälle',
    },
    Ground: {
        Fuel: {
            CenterTank: 'Tank in der Mitte',
            Completed: 'Abgeschlossen',
            Defueling: 'Enttanken',
            EstimatedTime: 'Geschätzte Dauer',
            LeftInnerTank: 'Linker innerer Tank',
            LeftOuterTank: 'Linker äußerer Tank',
            ReadyToStart: 'Bereit zum Tanken',
            Refuel: 'Tanken',
            RefuelTime: 'Tankdauer',
            Refueling: 'Tanken',
            RightInnerTank: 'Rechter innerer Tank',
            RightOuterTank: 'Rechter äußerer Tank',
            TT: {
                AircraftMustBeColdAndDarkToChangeRefuelTimes: 'Ändern der Tankdauer nur am Boden mit abgestellten Triebwerken',
                FillBlockFuelFromSimBrief: 'Tankmenge gemäß SimBrief verwenden',
            },
            Title: 'Treibstoff',
            TotalFuel: 'Treibstoff insgesamt',
            Unavailable: 'Nicht verfügbar',
        },
        Pushback: { Title: 'Pushback' },
        Services: {
            CallBaggageTruck: 'Gepäcktransporter rufen',
            CallCateringTruck: 'Catering-Transporter rufen',
            CallFuelTruck: 'Tankwagen rufen',
            ConnectExternalPower: 'Externe Stromversorgung anschließen',
            ConnectJetBridge: 'Fluggastbrücke verbinden',
            DisconnectExternalPower: 'Externe Stromversorgung trennen',
            DoorAft: 'Hintere Tür',
            DoorFwd: 'Vordere Tür',
            Title: 'Bodendienste',
        },
        Title: 'Boden',
    },
    Modals: {
        Cancel: 'Abbrechen',
        Confirm: 'Bestätigen',
        Okay: 'Okay',
    },
    NavigationAndCharts: {
        All: 'Alle',
        Altn: 'Alternative',
        ExitFullscreenMode: 'Vollbildmodus beenden',
        From: 'Von',
        LocalFiles: {
            Both: 'Beide',
            EstablishingConnection: 'Verbindung herstellen...',
            FailedToEstablishConnection: 'Verbindung konnte nicht hergestellt werden.',
            FileName: 'Dateiname',
            Image: 'Bild',
            Pdf: 'PDF',
            Retry: 'Wiederholen',
            Title: 'Lokale Dateien',
        },
        Navigraph: {
            AirportDoesNotExist: 'Der Flughafen existiert nicht',
            AuthenticateWithNavigraph: 'Authentifiziere dich mit Navigraph',
            InsufficientEnv: 'Keine oder unzureichende .env Datei',
            IntoYourBrowserAndEnterTheCodeBelow: 'Gib folgenden Code in Deinen Browser ein',
            NoAirportSelected: 'Kein Flughafen ausgewählt',
            ResetNavigraphAuthentication: 'Navigraph-Authentifizierung zurücksetzen',
            ScanTheQrCodeOrOpen: 'Den QR-Code scannen oder öffne',
            Title: 'Navigraph',
        },
        PinnedCharts: {
            Delete: 'Löschen',
            Edit: 'Bearbeiten',
            NoItemsFound: 'Keine Elemente gefunden.',
            ShowingChartsFromAllProviders: 'Karten von allen Anbietern anzeigen',
            SortMethods: {
                AlphabeticalAZ: 'Alphabetisch - A -> Z',
                AlphabeticalZA: 'Alphabetisch - Z -> A',
                FirstAccessed: 'Erster Zugriff',
                LastAccessed: 'Letzter Zugriff',
                None: 'Keine',
            },
            TT: {
                ChangeChartProvider: 'Kartenanbieter wechseln',
                ChangeChartSortMethod: 'Sortiermethode für Karten ändern',
            },
            Title: 'Angeheftete Karten',
            View: 'Ansicht',
        },
        PleaseWait: 'Bitte warten...',
        ShowingAllItems: 'Alle anzeigen',
        TT: {
            FitChartToHeight: 'Karte an Höhe anpassen',
            FitChartToWidth: 'Karte an Breite anpassen',
            ResetMovement: 'Verschiebung zurücksetzen',
            RotateLeft45Degrees: 'Um 45 Grad nach links drehen',
            RotateRight45Degrees: 'Um 45 Grad nach rechts drehen',
            ZoomIn: 'Vergrößern',
            ZoomOut: 'Verkleinern',
        },
        ThereAreNoChartsToDisplay: 'Es gibt keine anzuzeigenden Karten.',
        ThereIsNoChartToDisplay: 'Es gibt keine Karte zum Anzeigen.',
        Title: 'Navigation & Karten',
        To: 'Nach',
    },
    Performance: {
        Data: 'Daten',
        Landing: {
            AirportIcao: 'Flughafen ICAO',
            ApproachSpeed: 'Anflugsgeschwindigkeit',
            AutoLand: 'Automatische Landung',
            Calculate: 'Berechnen',
            Clear: 'Löschen',
            FillDataFrom: 'Ausfüllen von',
            FlapsConfiguration: 'Landeklappenkonfiguration',
            Low: 'Low',
            MaximumManual: 'Maximum Manuell',
            Medium: 'Medium',
            OverweightProcedure: 'Übergewichtsverfahren',
            Qnh: 'QNH',
            ReverseThrust: 'Schubumkehr',
            RunwayAltitude: 'Landebahnhöhenlage',
            RunwayCondition: 'Zustand der Startbahn',
            RunwayHeading: 'LandebahnrIchtung',
            RunwayLda: 'Landebahn LDA',
            RunwaySlope: 'Landebahnneigung',
            TT: {
                YouNeedToEnterAnIcaoCodeInOrderToMakeAMetarRequest: 'Du musst einen ICAO-Code eingeben, um eine METAR-Anfrage stellen zu können',
                YouNeedToLoadSimBriefDataInOrderToAutofillData: 'Du musst SimBrief-Daten laden, um Daten automatisch auszufüllen.',
            },
            Temperature: 'Temperatur',
            Title: 'Landung',
            Weight: 'Gewicht',
            WindDirection: 'Windrichtung',
            WindMagnitude: 'Windstärke',
        },
        SYNC: 'SYNC',
        Title: 'Performance',
        TopOfDescent: {
            Data: {
                Angle: 'Winkel',
                CurrentAltitude: 'Aktuelle Flughöhe',
                Distance: 'Entfernung',
                GroundSpeed: 'Geschwindigkeit über Grund',
                TargetAltitude: 'Zielflughöhe',
                Title: 'Daten',
                VerticalSpeed: 'Vertikale Geschwindigkeit',
            },
            GroundSpeed: {
                Add: 'Hinzufügen',
                FetchingSpeedFromSimulator: 'Geschwindigkeit vom Simulator auslesen',
                GroundSpeed: 'Geschwindigkeit über Grund',
                ManualInput: 'Manuelle Eingabe',
                MinAltitude: 'Min. Flughöhe',
                RemoveLast: 'Letzte entfernen',
                Sync: 'SYNC',
                Title: 'Geschwindigkeit über Grund',
            },
            Result: {
                BeforeTarget: 'vor dem Ziel',
                DesiredDescentAngle: 'Gewünschter Sinkwinkel',
                StartYourDescentAbout: 'Beginnen Sie Ihren Sinkflug ungefähr',
                Title: 'Ergebnis',
            },
            TT: {
                DesynchronizeInputWithAircraftsCurrentAltitude: 'Desynchronisierung der Eingabe mit der aktuellen Flughöhe',
                SynchronizeInputWithAircraftsCurrentAltitude: 'Eingabe mit aktueller Flughöhe des Flugzeugs synchronisieren',
            },
            Title: 'Top of Descent',
        },
    },
    Presets: {
        AircraftStates: {
            Cancel: 'Abbrechen',
            CurrentProcedureStep: 'Aktueller Verfahrensschritt',
            PleaseConfirmLoadingOfPreset: 'Bitte bestätigen Sie das Laden der Voreinstellung.',
            SelectAPresetToLoad: 'Wählen Sie eine Voreinstellung zum Laden',
            TheAircraftMustBeOnTheGroundToLoadAPreset: 'Das Flugzeug muss am Boden sein, um eine Voreinstellung zu laden.',
            TheAircraftMustBeOntheGroundToLoadAPreset: 'Das Flugzeug muss am Boden sein, um eine Voreinstellung zu laden.',
            Title: 'Flugzeugzustände',
        },
        InteriorLighting: {
            AircraftNeedsToBePoweredToLoadPresets: 'Das Flugzeug muss mit Strom versorgt werden, um Voreinstellungen zu laden',
            AircraftNeedsToBePoweredToSavePresets: 'Das Flugzeug muss mit Strom versorgt sein, um Voreinstellungen zu speichern',
            LoadPreset: 'Voreinstellung laden',
            LoadingPreset: 'Voreinstellung wird geladen',
            NoName: 'Kein Name',
            PleaseConfirmSavingPreset: 'Bitte bestätigen Sie das Speichern der Voreinstellung',
            SavePreset: 'Voreinstellung speichern',
            SavingPreset: 'Voreinstellung speichern',
            SelectAnInteriorLightingPresetToLoadOrSave: 'Wähle eine Voreinstellung für die Innenbeleuchtung zum Laden oder Speichern aus.',
            TT: {
                AircraftMustBePowered: 'Flugzeug muss mit Strom versorgt sein',
                ClickTextToChangeThePresetsName: 'Klicken Sie auf den Text, um den Namen der Voreinstellung zu ändern',
                LoadThisPreset: 'Diese Voreinstellung laden',
                SaveTheCurrentLightingLevels: 'Speichere die aktuellen Beleuchtungseinstellungen',
            },
            TheAircraftMustBePoweredForInteriorLightingPresets: 'Das Flugzeug muss für Voreinstellungen der Innenbeleuchtung mit Strom versorgt sein.',
            Title: 'Innenbeleuchtung',
        },
        Title: 'Voreinstellungen',
    },
    Pushback: {
        Backward: 'Rückwärts',
        CallTug: 'Rufe Flugzeugschleppfahrzeug',
        Forward: 'Vorwärts',
        Halt: 'Halt',
        ParkingBrake: {
            Off: 'Aus',
            On: 'An',
            Title: 'Parkbremse',
        },
        TugDirection: 'Schlepprichtung',
        TugSpeed: 'Schleppgeschwindigkeit',
    },
    Settings: {
        About: { Title: 'Über' },
        AircraftOptionsPinPrograms: {
            AccelerationHeight: 'Beschleunigungshöhe',
            EngineOutAccelerationHeight: 'Beschleunigungshöhe bei Triebwerksausfall',
            IsisBaroUnit: 'ISIS-Baro-Einheit',
            IsisMetricAltitude: 'ISIS metrische Höhe',
            PaxSigns: 'Passagier-Anzeigen',
            RmpVhfSpacing: 'RMP VHF Kanalraster',
            ThrustReductionHeight: 'Flughöhe für Schubreduzierung',
            Title: 'Flugzeug-Optionen/Pinprogramme',
            WeightUnit: 'Gewichtseinheit',
        },
        AtsuAoc: {
            AtisAtcSource: 'ATIS/ATC-Quelle',
            AutomaticallyImportSimBriefData: 'SimBrief-Daten automatisch importieren',
            Enable: 'Aktivieren',
            EnableTelex: 'TELEX aktivieren',
            ErrorReporting: 'Fehlerberichte senden',
            HoppieUserId: 'Hoppie-Benutzer-ID',
            MetarSource: 'METAR-Quelle',
            OptionalA32nxErrorReporting: 'Optionale A32NX-Fehlerberichterstattung',
            PleaseCheckThatYouHaveCorrectlyEnteredYourSimbBriefUsernameOrPilotId: 'Bitte überprüfe, ob Du Deinen SimBrief-Benutzernamen oder Deine Pilot-ID korrekt eingegeben hast.',
            SimBriefUsernamePilotId: 'SimBrief Benutzername/Pilot-ID',
            TafSource: 'TAF-Quelle',
            Telex: 'TELEX',
            TelexEnablesFreeTextAndLiveMap: 'TELEX ermöglicht das Versenden von Freitext    Nachrichten und das Erscheinen auf der FlyByWire Live-Map. Falls aktiviert, werden Flugzeug-Positionsdaten für die Dauer des Fluges veröffentlicht. Nachrichten sind öffentlich und werden nicht moderiert. NUTZUNG DIESER FUNKTION AUF EIGENES RISIKO. Um mehr über TELEX und die damit aktivierten Funktionen zu erfahren, besuche bitte https://docs.flybywiresim.com/telex.',
            TelexWarning: 'TELEX-Warnung',
            Title: 'ATSU / AOC',
            YouAreAbleToOptIntoAnonymousErrorReporting: 'Du kannst eine anonyme Fehlerberichterstattung aktivieren, mit der wir Probleme schneller diagnostizieren, überwachen und beheben können. Diese Funktion ist freiwillig und es werden keine persönlichen Daten erfasst. Eventuell ermöglicht es Dir jedoch, einfacher Support zu erhalten und Deine Probleme schneller zu beheben.',
            YourSimBriefPilotIdHasBeenValidatedAndUpdatedTo: 'Deine SimBrief-PilotID wurde validiert und aktualisiert auf',
        },
        Audio: {
            Announcements: 'Kabinenansagen',
            BoardingMusic: 'Boarding Musik',
            EngineInteriorVolume: 'Triebwerkslautstärke innen',
            ExteriorMasterVolume: 'Master-Lautstärke für den Außenbereich',
            PassengerAmbience: 'Passagier-Ambiente',
            PtuAudibleInCockpit: 'PTU im Cockpit hörbar',
            Title: 'Audio',
            WindInteriorVolume: 'Lautstärke Windgeräusche im Innern',
        },
        Fast: 'Schnell',
        Instant: 'Sofort',
        Real: 'Echtzeit',
        Realism: {
            AdirsAlignTime: 'ADIRS Ausrichtungszeit',
            AutofillChecklists: 'Automatisches Ausfüllen der Checklisten',
            BoardingTime: 'Einsteigedauer',
            DatalinkTransmissionTime: 'DATALINK Übertragungsdauer',
            DmcSelfTestTime: 'DMC-Selbsttestdauer',
            HomeCockpitMode: 'Home-Cockpitmodus',
            McduFocusTimeout: 'MCDU Fokusdauer (Sekunden)',
            McduKeyboardInput: 'MCDU-Tastatureingabe',
            SeparateTillerFromRudderInputs: 'Trennung von Tiller und Querruder Eingaben',
            Title: 'Realismus',
        },
        SimOptions: {
            Calibrate: 'Kalibrieren',
            DefaultBarometerUnit: 'Standard-Barometer-Einheit',
            DynamicRegistrationDecal: 'Dynamische Registrierungsbeschriftung',
            EnabledMcduServerConnectionAutoDeactivatesAfter5MinutesIfNoSuccessfulConnection: 'MCDU Serververbindung aktivieren (Wird nach 5 Minuten automatisch deaktiviert, wenn keine Verbindung zustande kommt)',
            ExternalMcduServerPort: 'Externer MCDU-Serverport',
            LoadOnly: 'Einmaliges Laden',
            None: 'Keine',
            Save: 'Zurückspeichern bei Änderung',
            SyncMsfsFlightPlan: 'MSFS-Flugplan synchronisieren',
            ThrottleDetents: 'Schubhebelkalibrierung',
            Title: 'Sim-Optionen',
            UseCalculatedIlsSignals: 'Berechnete ILS-Signale verwenden',
        },
        ThrottleConfig: {
            Apply: 'Anwenden',
            AreYouSureThatYouWantToResetYourCurrentThrottleConfigurationToTheirDefaultStates: 'Bist Du sicher, dass Du Deine aktuellen Einstellungen für die Schubhebelkalibrierung zurücksetzen möchten? Diese Aktion kann nicht rückgängig gemacht werden. ',
            Axis: 'Achse',
            Back: 'Zurück',
            ConfigureEnd: 'Bereich-Ende',
            CurrentValue: 'Aktueller Wert',
            Deadband: 'Toleranzbereich',
            IndependentAxis: 'Unabhängige Achsen',
            LoadFromFile: 'Aus Datei laden',
            PleaseEnterAValidDeadzone: 'Bitte gib eine gültigen Toleranzbereich an',
            ResetToDefaults: 'Auf Standardwerte zurücksetzen',
            ReverseFull: 'Voller Umkehrschub',
            ReverseIdle: 'Leerlauf Umkehrschub',
            ReverserOnAxis: 'Umkehrschub auf Achsenbereich',
            SaveAndApply: 'Speichern und Anwenden',
            SetFromThrottle: 'Übernehme aktuelle Schubhebelstellung ',
            ThrottleConfigurationReset: 'Zurücksetzen der Schubhebelkalibrierung',
        },
        Title: 'Einstellungen',
        Unrealistic: 'Unrealistisch',
        flyPad: {
            '12Hour': '12h',
            '24Hour': '24h',
            'AutoBrightness': 'Automatische Helligkeit',
            'AutomaticallyShowOnscreenKeyboard': 'Bildschirmtastatur automatisch anzeigen',
            'Blue': 'Blau',
            'Brightness': 'Helligkeit',
            'Dark': 'Dunkel',
            'Language': 'Sprache',
            'Light': 'Hell',
            'Local': 'Lokal',
            'LocalTimeFormat': 'Lokales Zeitformat',
            'OnscreenKeyboardLayout': 'Layout der Bildschirmtastatur',
            'ShowColoredRawMetar': 'Rohdaten-METAR farbig anzeigen',
            'ShowStatusBarFlightProgressIndicator': 'Flugfortschrittsanzeige in der Statusleiste anzeigen',
            'Theme': 'Farbschema',
            'TimeDisplayed': 'Zeitanzeige',
            'Title': 'flyPad',
            'Utc': 'UTC',
            'UtcAndLocal': 'UTC und Lokal',
        },
    },
    StatusBar: {
        Apr: 'Apr',
        Aug: 'Aug',
        Dec: 'Dez',
        Feb: 'Feb',
        Fri: 'Fr',
        Jan: 'Jan',
        Jun: 'Jun',
        Mar: 'Mär',
        May: 'Mai',
        Mon: 'Mo',
        Nov: 'Nov',
        Oct: 'Okt',
        Sat: 'Sa',
        Sep: 'Sep',
        Sun: 'So',
        TT: {
            ConnectedToLocalApi: 'Mit Local-API Server verbinden',
            DisconnectedFromLocalApi: 'Vom Local-API Server trennen',
            TurnOffOrShutdownEfb: 'EFB ausschalten oder herunterfahren',
        },
        Thu: 'Do',
        Tue: 'Di',
        Wed: 'Mi',
    },
};
