export const en = {
    AirTrafficControl: {
        Active: 'Active',
        ConnectHoppieACARS: 'Connect Hoppie ACARS',
        DisconnectHoppieACARS: 'Disconnect Hoppie ACARS',
        HoppieError: 'Hoppie Error',
        HoppieSystemRequiresAUserIdWhichNeedsToBeSetInSettings: 'Hoppie system requires a user ID which needs to be set in Settings > ATSU / AOC.',
        NoInformationAvailableForThisFrequency: 'NO INFORMATION AVAILABLE FOR THIS FREQUENCY',
        SetActive: 'Set Active',
        SetStandby: 'Set Standby',
        Standby: 'Standby',
        Title: 'Air Traffic Control',
    },
    Checklists: {
        AreYouSureYouWantToResetAllChecklists: 'Are you sure you want to reset all checklists?',
        ChecklistResetWarning: 'Checklist Reset Warning',
        MarkItemAsComplete: 'Mark item as complete',
        ResetAll: 'Reset All',
        ResetChecklist: 'Reset Checklist',
    },
    Dashboard: {
        Alternate: 'Alternate',
        AverageWind: 'Average Wind',
        Checklists: 'Checklists',
        CompanyRoute: 'Company Route',
        CostIndex: 'Cost Index',
        CruiseAlt: 'Cruise Alt',
        GoToPage: 'Go to Page',
        ImportSimBriefData: 'Import SimBrief Data',
        ImportantInformation: 'Important Information',
        Maintenance: 'Maintenance',
        NoActiveFailures: 'No Active Failures',
        NoIcaoProvided: 'No ICAO Provided',
        NoPinnedCharts: 'No Pinned Charts',
        NoRelevantChecklists: 'No Relevant Checklists',
        PinnedCharts: 'Pinned Charts',
        Route: 'Route',
        SimBriefDataNotYetLoaded: 'SimBrief data not yet loaded.',
        Weather: 'Weather',
        YourFlight: 'Your Flight',
        ZFW: 'ZFW',
    },
    Dispatch: {
        Ofp: {
            ImportSimBriefData: 'Import SimBrief Data',
            Title: 'OFP',
            YouHaveNotYetImportedAnySimBriefData: 'You have not yet imported any SimBrief data.',
        },
        Overview: {
            Engines: 'Engines',
            MMO: 'MMO',
            MRW: 'MRW',
            MTOW: 'MTOW',
            MZFW: 'MZFW',
            MaximumCargo: 'Maximum Cargo',
            MaximumFuelCapacity: 'Maximum Fuel Capacity',
            MaximumPassengers: 'Maximum Passengers',
            Model: 'Model',
            Range: 'Range',
            Title: 'Overview',
        },
        Title: 'Dispatch',
    },
    Failures: {
        Comfort: 'Comfort',
        Compact: 'Compact',
        FullSimulationOfTheFailuresBelowIsntYetGuaranteed: "Full simulation of the failures below isn't yet guaranteed.",
        Search: 'Search',
        Title: 'Failures',
    },
    Ground: {
        Fuel: {
            CenterTank: 'Center Tank',
            Completed: 'Completed',
            Defueling: 'Defueling',
            EstimatedTime: 'Estimated Time',
            LeftInnerTank: 'Left Inner Tank',
            LeftOuterTank: 'Left Outer Tank',
            ReadyToStart: 'Ready to Start',
            Refuel: 'Refuel',
            RefuelTime: 'Refuel Time',
            Refueling: 'Refueling',
            RightInnerTank: 'Right Inner Tank',
            RightOuterTank: 'Right Outer Tank',
            Title: 'Fuel',
            TotalFuel: 'Total Fuel',
            Unavailable: 'Unavailable',
        },
        Pushback: { Title: 'Pushback' },
        Services: {
            CallBaggageTruck: 'Call Baggage Truck',
            CallCateringTruck: 'Call Catering Truck',
            CallFuelTruck: 'Call Fuel Truck',
            ConnectExternalPower: 'Connect External Power',
            ConnectJetBridge: 'Connect Jet Bridge',
            DisconnectExternalPower: 'Disconnect External Power',
            DoorAft: 'Door Aft',
            DoorFwd: 'Door Fwd',
            Title: 'Services',
        },
        Title: 'Ground',
    },
    NavigationAndCharts: {
        Altn: 'Altn',
        ExitFullscreenMode: 'Exit Fullscreen Mode',
        From: 'From',
        LocalFiles: {
            EstablishingConnection: 'Establishing Connection',
            FailedToEstablishConnection: 'Failed to Establish Connection.',
            Retry: 'Retry',
            Title: 'Local Files',
        },
        Navigraph: {
            AirportDoesNotExist: 'Airport Does Not Exist',
            AuthenticateWithNavigraph: 'Authenticate with Navigraph',
            InsufficientEnv: 'Insufficient .env File',
            IntoYourBrowserAndEnterTheCodeBelow: 'into your browser and enter the code below\n',
            NoAirportSelected: 'No Airport Selected',
            PleaseWait: 'Please Wait',
            ResetNavigraphAuthentication: 'Reset Navigraph Authentication',
            ScanTheQrCodeOrOpen: 'Scan the QR Code or Open',
            Title: 'Navigraph',
        },
        PinnedCharts: { Title: 'Pinned Charts' },
        ThereAreNoChartsToDisplay: 'There are no charts to display.',
        ThereIsNoChartToDisplay: 'There is no chart to display.',
        Title: 'Navigation & Charts',
        To: 'To',
    },
    Performance: {
        Data: 'Data',
        Landing: {
            AirportIcao: 'Airport ICAO',
            ApproachSpeed: 'Approach Speed',
            AutoLand: 'Auto Land',
            Calculate: 'Calculate',
            Clear: 'Clear',
            FillDataFrom: 'Fill data from',
            FlapsConfiguration: 'Flaps Configuration',
            Low: 'Low',
            MaximumManual: 'Maximum Manual',
            Medium: 'Medium',
            OverweightProcedure: 'Overweight Procedure',
            Qnh: 'QNH',
            ReverseThrust: 'Reverse Thrust',
            RunwayAltitude: 'Runway Altitude',
            RunwayCondition: 'Runway Condition',
            RunwayHeading: 'Runway Heading',
            RunwayLda: 'Runway LDA',
            RunwaySlope: 'Runway Slope',
            Temperature: 'Temperature',
            Title: 'Landing',
            Weight: 'Weight',
            WindDirection: 'Wind Direction',
            WindMagnitude: 'Wind Magnitude',
        },
        SYNC: 'SYNC',
        Title: 'Performance',
        TopOfDescent: {
            Data: {
                Angle: 'Angle',
                CurrentAltitude: 'Current Altitude',
                GroundSpeed: 'Ground Speed',
                TargetAltitude: 'Target Altitude',
                Title: 'Data',
            },
            GroundSpeed: {
                Add: 'Add',
                FetchingSpeedFromSimulator: 'Fetching speed from simulator',
                GroundSpeed: 'Ground Speed',
                ManualInput: 'Manual Input',
                MinAltitude: 'Min. Altitude',
                RemoveLast: 'Remove Last',
                Sync: 'SYNC',
                Title: 'Ground Speed',
            },
            Result: {
                BeforeTarget: 'before target',
                StartYourDescentAbout: 'Start your descent about',
                Title: 'Result',
            },
        },
    },
    Presets: {
        AircraftStates: {
            Cancel: 'Cancel',
            CurrentProcedureStep: 'Current Procedure Step',
            PleaseConfirmLoadingOfPreset: 'Please confirm loading of preset.',
            SelectAPresetToLoad: 'Select a Preset to Load',
            TheAircraftMustBeOnTheGroundToLoadAPreset: 'The aircraft must be on the ground to load a preset.',
            TheAircraftMustBeOntheGroundToLoadAPreset: 'The aircraft must be on the ground to load a preset.',
            Title: 'Aircraft States',
        },
        InteriorLighting: {
            LoadPreset: 'Load Preset',
            NoName: 'No Name',
            SavePreset: 'Save Preset',
            SelectAnInteriorLightingPresetToLoadOrSave: 'Select an interior lighting preset to load or save.',
            TheAircraftMustBePoweredForInteriorLightingPresets: 'The aircraft must be powered for interior lighting presets.',
            Title: 'Interior Lighting',
        },
        Title: 'Presets',
    },
};
