export const es = {
    AirTrafficControl: {
        Active: 'Activo',
        ConnectHoppieACARS: 'Conecta Hoppie ACARS',
        DisconnectHoppieACARS: 'Desconecte Hoppie ACARS',
        HoppieError: 'Error de Hoppie',
        HoppieSystemRequiresAUserIdWhichNeedsToBeSetInSettings: 'El sistema Hoppie requiere una identificación de usuario que debe configurarse en Ajustes > ATSU /AOC.',
        NoInformationAvailableForThisFrequency: 'NO HAY INFORMACIÓN DISPONIBLE PARA ESTA FRECUENCIA',
        SetActive: 'Establecer como activo',
        SetStandby: 'Establecer modo de espera',
        Standby: 'En espera',
        Title: 'Control de tráfico aéreo',
    },
    Checklist: { ThereAreRemainingAutofillChecklistItemsThatHaveNotYetBeenCompleted: 'Quedan elementos de la lista de verificación de autocompletar que aún no se han completado' },
    Checklists: {
        AreYouSureYouWantToResetAllChecklists: '¿Estás seguro de que quieres restablecer todas las listas de verificación?',
        AreYouSureYouWantToResetChecklists: '¿Estás seguro de que quieres restablecer todas las listas de verificación?',
        ChecklistResetWarning: 'Advertencia de restablecimiento de lista de verificación',
        MarkChecklistAsComplete: 'Marcar lista de verificación como completa',
        MarkItemAsComplete: 'Marcar artículo como completo',
        ProceedToNextChecklist: 'Pasar a la siguiente lista de verificación',
        ResetAll: 'Restablecer todos',
        ResetChecklist: 'Restablecer lista de verificación',
        TheLastChecklistIsComplete: 'La última lista de verificación está completa',
        ThereAreRemainingAutofillChecklistItemsThatHaveNotYetBeenCompleted: 'Quedan elementos de la lista de verificación de autocompletar que aún no se han completado',
        Title: 'Listas de Verificación',
    },
    Dashboard: {
        ImportantInformation: {
            Checklists: {
                NoRelevantChecklists: 'Sin listas de verificación relevantes',
                Title: 'Listas de Verificación',
            },
            GoToPage: 'Ir a la página',
            Maintenance: {
                NoActiveFailures: 'Sin fallos activos',
                Title: 'Mantenimiento',
            },
            PinnedCharts: {
                NoPinnedCharts: 'Sin gráficos anclados',
                Title: 'Cartas Anclados',
            },
            TT: { RearrangeWidgets: 'Reorganizar widgets' },
            Title: 'Información importante',
            Weather: {
                AirPressure: 'Presión de aire',
                DewPoint: 'Punto de rocío',
                Loading: 'Cargando…',
                Raw: 'Sin procesar',
                TT: {
                    SwitchToIconView: 'Cambiar a vista de iconos',
                    SwitchToRawMetarView: 'Cambiar a la vista de Raw Metar',
                },
                Temperature: 'Temperatura',
                Title: 'Clima',
                WindSpeed: 'Velocidad del viento',
            },
        },
        YourFlight: {
            Alternate: 'Alternar',
            AverageWind: 'Viento promedio',
            CompanyRoute: 'Ruta de la empresa',
            CostIndex: 'Índice de costos',
            CruiseAlt: 'Crucero Alt.',
            ImportSimBriefData: 'Importar Datos de SimBrief',
            Route: 'Ruta',
            SimBriefDataNotYetLoaded: 'Los datos de SimBrief aún no se han cargado.',
            Title: 'Tu vuelo',
            ZFW: 'ZFW',
        },
    },
    Dispatch: {
        Ofp: {
            ImportSimBriefData: 'Importar Datos de SimBrief',
            TT: {
                IncreaseFontSize: 'Aumentar tamaño de fuente',
                ReduceFontSize: 'Reducir el tamaño de fuente',
            },
            Title: 'OFP',
            YouHaveNotYetImportedAnySimBriefData: 'Aún no ha importado ningún dato de SimBrief.',
        },
        Overview: {
            Engines: 'Motores',
            MMO: 'MMO',
            MRW: 'MRW',
            MTOW: 'MTOW',
            MZFW: 'MZFW',
            MaximumCargo: 'Carga Máxima',
            MaximumFuelCapacity: 'Capacidad Máxima de Combustible',
            MaximumPassengers: 'Número Máximo de Pasajeros',
            Model: 'Modelo',
            Range: 'Rango',
            Title: 'Resumen',
        },
        Title: 'Envío',
    },
    Failures: {
        Comfort: { Title: 'Confort' },
        Compact: { Title: 'Compacto' },
        FullSimulationOfTheFailuresBelowIsntYetGuaranteed: 'La simulación completa de las fallas a continuación aún no está garantizada.',
        Search: 'Buscar',
        Title: 'Fallas',
    },
    Ground: {
        Fuel: {
            CenterTank: 'Tanque Central',
            Completed: 'Completado',
            Defueling: 'Vaciado',
            EstimatedTime: 'Tiempo Estimado',
            LeftInnerTank: 'Depósito Interior Izquierdo',
            LeftOuterTank: 'Tanque Exterior Izquierdo',
            ReadyToStart: 'Listo para Empezar',
            Refuel: 'Repostar',
            RefuelTime: 'Tiempo de Repostaje',
            Refueling: 'Llenar el depósito',
            RightInnerTank: 'Depósito Interior Derecho',
            RightOuterTank: 'Tanque Exterior Derecho',
            TT: {
                AircraftMustBeColdAndDarkToChangeRefuelTimes: 'La aeronave debe estar fría y oscura para cambiar los tiempos de repostaje',
                FillBlockFuelFromSimBrief: 'Combustible para bloques de llenado de SimBrief',
            },
            Title: 'Combustible',
            TotalFuel: 'Combustible Total',
            Unavailable: 'No disponible',
        },
        Pushback: { Title: 'Retroceso' },
        Services: {
            CallBaggageTruck: 'Llame a Camión de Equipaje',
            CallCateringTruck: 'Llame a Camión de Catering',
            CallFuelTruck: 'Llame a Camión de Combustible',
            ConnectExternalPower: 'Conectar Alimentación Externa',
            ConnectJetBridge: 'Conecte el Puente Jet',
            DisconnectExternalPower: 'Desconectar Alimentación Externa',
            DoorAft: 'Puerta en Popa',
            DoorFwd: 'Puerta Adelante',
            Title: 'Servicios',
        },
        Title: 'Tierra',
    },
    Modals: {
        Cancel: 'Cancelar',
        Confirm: 'Confirmar',
        Okay: 'Aceptar',
    },
    NavigationAndCharts: {
        All: 'Todo',
        Altn: 'Altn',
        ExitFullscreenMode: 'Salir de modo pantalla completa',
        From: 'De',
        LocalFiles: {
            Both: 'Ambos',
            EstablishingConnection: 'Estableciendo conexión',
            FailedToEstablishConnection: 'No se pudo establecer la conexión.',
            FileName: 'Nombre de archivo',
            Image: 'Imagen',
            Pdf: 'PDF',
            Retry: 'Reintentar',
            Title: 'Archivos locales',
        },
        Navigraph: {
            AirportDoesNotExist: 'El aeropuerto no existe',
            AuthenticateWithNavigraph: 'Autenticación con Navigraph',
            InsufficientEnv: 'Archivo.env insuficiente',
            IntoYourBrowserAndEnterTheCodeBelow: 'en tu navegador e introduce el código a continuación\n',
            NoAirportSelected: 'Sin aeropuerto seleccionado',
            ResetNavigraphAuthentication: 'Restablecer la autenticación de Navigraph',
            ScanTheQrCodeOrOpen: 'Escanee el código QR o ábralo',
            Title: 'Navigraph',
        },
        PinnedCharts: {
            Delete: 'Eliminar',
            Edit: 'Editar',
            NoItemsFound: 'No se encontraron artículos.',
            ShowingChartsFromAllProviders: 'Mostrar gráficos de todos los proveedores',
            SortMethods: {
                AlphabeticalAZ: 'Alfabético: A -> Z',
                AlphabeticalZA: 'Alfabético - Z -> A',
                FirstAccessed: 'Acceso por primera vez',
                LastAccessed: 'Último acceso',
                None: 'Ninguno',
            },
            TT: {
                ChangeChartProvider: 'Cambiar proveedor de gráficos',
                ChangeChartSortMethod: 'Cambiar método de clasificación de gráficos',
            },
            Title: 'Cartas Anclados',
            View: 'Ver',
        },
        PleaseWait: 'Por favor espera...',
        ShowingAllItems: 'Mostrar todos los artículos',
        TT: {
            FitChartToHeight: 'Ajustar tabla a altura',
            FitChartToWidth: 'Ajustar la tabla a la anchura',
            ResetMovement: 'Reiniciar movimiento',
            RotateLeft45Degrees: 'Girar 45 grados a la izquierda',
            RotateRight45Degrees: 'Girar 45 grados a la derecha',
            ZoomIn: 'Acercar',
            ZoomOut: 'Alejar',
        },
        ThereAreNoChartsToDisplay: 'No hay gráficos que mostrar.',
        ThereIsNoChartToDisplay: 'No hay ningún gráfico que mostrar.',
        Title: 'Navegación y Cartas',
        To: 'A',
    },
    Performance: {
        Data: 'Datos',
        Landing: {
            AirportIcao: 'Aeropuerto OACI',
            ApproachSpeed: 'Velocidad de aproximación',
            AutoLand: 'Tierra automática',
            Calculate: 'Calcular',
            Clear: 'Borrar',
            FillDataFrom: 'Rellenar datos de',
            FlapsConfiguration: 'Configuración de flaps',
            Low: 'Baja',
            MaximumManual: 'Manual máximo',
            Medium: 'Medio',
            OverweightProcedure: 'Procedimiento de sobrepeso',
            Qnh: 'QNH',
            ReverseThrust: 'Empuje inverso',
            RunwayAltitude: 'Altitud de pista',
            RunwayCondition: 'Estado de la pista',
            RunwayHeading: 'Encabezado de pista',
            RunwayLda: 'Pista LDA',
            RunwaySlope: 'Pendiente de pista',
            Temperature: 'Temperatura',
            Title: 'El Aterrizaje',
            Weight: 'Peso',
            WindDirection: 'Dirección del viento',
            WindMagnitude: 'Magnitud viento',
        },
        SYNC: 'Sincronizar',
        Title: 'Rendimiento',
        TopOfDescent: {
            Data: {
                Angle: 'Ángulo',
                CurrentAltitude: 'Altitud Actual',
                GroundSpeed: 'Velocidad respecto al suelo',
                TargetAltitude: 'Altitud Objetivo',
                Title: 'Datos',
            },
            GroundSpeed: {
                Add: 'Añadir',
                FetchingSpeedFromSimulator: 'Obteniendo velocidad del simulador',
                GroundSpeed: 'Velocidad respecto al suelo',
                ManualInput: 'Entrada Manual',
                MinAltitude: 'Mín. Altitud',
                RemoveLast: 'Eliminar el último',
                Sync: 'Sincronizar',
                Title: 'Velocidad respecto al suelo',
            },
            Result: {
                BeforeTarget: 'antes del objetivo',
                StartYourDescentAbout: 'Comienza tu descenso sobre',
                Title: 'Resultado',
            },
            Title: 'Cima del descenso',
        },
    },
    Presets: {
        AircraftStates: {
            Cancel: 'Cancelar',
            CurrentProcedureStep: 'Paso del Procedimiento Actual',
            PleaseConfirmLoadingOfPreset: 'Confirme la carga del ajuste preestablecido.',
            SelectAPresetToLoad: 'Seleccione un ajuste preestablecido para cargar',
            TheAircraftMustBeOnTheGroundToLoadAPreset: 'La aeronave debe estar en tierra para cargar un preajuste.',
            TheAircraftMustBeOntheGroundToLoadAPreset: 'La aeronave debe estar en tierra para cargar un preajuste.',
            Title: 'Estados de aeronaves',
        },
        InteriorLighting: {
            AircraftNeedsToBePoweredToLoadPresets: 'La aeronave necesita energía para cargar los ajustes preestablecidos',
            AircraftNeedsToBePoweredToSavePresets: 'La aeronave necesita energía para guardar los ajustes preestablecidos',
            LoadPreset: 'Cargar Preajuste',
            LoadingPreset: 'Cargando preajuste',
            NoName: 'Sin nombre',
            PleaseConfirmSavingPreset: 'Confirme guardar el ajuste preestablecido',
            SavePreset: 'Guardar Preajuste',
            SavingPreset: 'Guardar ajustes preestablecidos',
            SelectAnInteriorLightingPresetToLoadOrSave: 'Seleccione un preajuste de iluminación interior para cargar o guardar.',
            TT: {
                AircraftMustBePowered: 'La aeronave debe estar propulsada',
                ClickTextToChangeThePresetsName: 'Haga clic en Texto para cambiar el nombre del ajuste preestablecido',
                LoadThisPreset: 'Cargar este preajuste',
                SaveTheCurrentLightingLevels: 'Guarde los niveles de iluminación actuales',
            },
            TheAircraftMustBePoweredForInteriorLightingPresets: 'La aeronave debe estar encendida para preajustes de iluminación interior.',
            Title: 'Iluminación interior',
        },
        Title: 'Predeterminados',
    },
    Pushback: {
        Backward: 'Atrás',
        CallTug: 'Llamar a Tug',
        Forward: 'Adelante',
        Halt: 'Detener',
        ParkingBrake: {
            Off: 'DESACTIVADO',
            On: 'ACTIVADO',
            Title: 'Freno de estacionamiento',
        },
        TugDirection: 'Dirección del remolcador',
        TugSpeed: 'Velocidad del remolcador',
    },
    StatusBar: {
        Apr: 'Abr',
        Aug: 'Ago',
        Dec: 'Dic',
        Feb: 'Feb',
        Fri: 'Vie',
        Jan: 'Ene',
        Jun: 'Jun',
        Mar: 'Mar',
        May: 'May',
        Mon: 'Lun',
        Nov: 'Nov',
        Oct: 'Oct',
        Sat: 'Sábado',
        Sep: 'Sep',
        Sun: 'Dom',
        TT: {
            ConnectedToLocalApi: 'Conectado a la API local',
            DisconnectedFromLocalApi: 'Desconectado de la API local',
            TurnOffOrShutdownEfb: 'Apagar o apagar EFB',
        },
        Thu: 'Jue',
        Tue: 'Mar',
        Wed: 'Mié',
    },
};
