export const es = {
    AirTrafficControl: {
        Active: 'Activo',
        ConnectHoppieACARS: 'Conecta Hoppie ACARS',
        DisconnectHoppieACARS: 'Desconecte Hoppie ACARS',
        HoppieError: 'Error de Hoppie',
        HoppieSystemRequiresAUserIdWhichNeedsToBeSetInSettings: 'El sistema Hoppie requiere una identificación de usuario que debe configurarse en Ajustes > ATSU /AOC.',
        NoInformationAvailableForThisFrequency: 'NO HAY INFORMACIÓN DISPONIBLE PARA ESTA FRECUENCIA',
        SetActive: 'Establecer como activo',
        SetStandby: 'Establecer modo de espera',
        Standby: 'En espera',
        Title: 'Control de tráfico aéreo',
    },
    Checklist: { ThereAreRemainingAutofillChecklistItemsThatHaveNotYetBeenCompleted: 'Quedan elementos de la lista de verificación de autocompletar que aún no se han completado' },
    Checklists: {
        AreYouSureYouWantToResetAllChecklists: '¿Estás seguro de que quieres restablecer todas las listas de verificación?',
        AreYouSureYouWantToResetChecklists: '¿Estás seguro de que quieres restablecer todas las listas de verificación?',
        ChecklistResetWarning: 'Advertencia de restablecimiento de lista de verificación',
        MarkChecklistAsComplete: 'Marcar lista de verificación como completa',
        MarkItemAsComplete: 'Marcar artículo como completo',
        ProceedToNextChecklist: 'Pasar a la siguiente lista de verificación',
        ResetAll: 'Restablecer todos',
        ResetChecklist: 'Restablecer lista de verificación',
        TheLastChecklistIsComplete: 'La última lista de verificación está completa',
    },
    Dashboard: {
        Alternate: 'Alternativa',
        AverageWind: 'Viento Promedio',
        Checklists: 'Listas de Verificación',
        CompanyRoute: 'Ruta de la Empresa',
        CostIndex: 'Índice de Costos',
        CruiseAlt: 'Crucero Alt',
        GoToPage: 'Ir a la página',
        ImportSimBriefData: 'Importar Datos de SimBrief',
        ImportantInformation: 'Información Importante',
        Maintenance: 'Mantenimiento',
        NoActiveFailures: 'Sin Fallos Activos',
        NoIcaoProvided: 'No se proporcionó la OACI',
        NoPinnedCharts: 'Sin Cartas Anclados',
        NoRelevantChecklists: 'Sin Listas de Verificación Relevantes',
        PinnedCharts: 'Cartas Anclados',
        Route: 'Ruta',
        SimBriefDataNotYetLoaded: 'Los datos de SimBrief aún no se han cargado.',
        Weather: 'Clima',
        YourFlight: 'Tu Vuelo',
        ZFW: 'ZFW',
    },
    Dispatch: {
        Ofp: {
            ImportSimBriefData: 'Importar Datos de SimBrief',
            Title: 'OFP',
            YouHaveNotYetImportedAnySimBriefData: 'Aún no ha importado ningún dato de SimBrief.',
        },
        Overview: {
            Engines: 'Motores',
            MMO: 'MMO',
            MRW: 'MRW',
            MTOW: 'MTOW',
            MZFW: 'MZFW',
            MaximumCargo: 'Carga Máxima',
            MaximumFuelCapacity: 'Capacidad Máxima de Combustible',
            MaximumPassengers: 'Número Máximo de Pasajeros',
            Model: 'Modelo',
            Range: 'Rango',
            Title: 'Resumen',
        },
        Title: 'Envío',
    },
    Failures: {
        Comfort: { Title: 'Confort' },
        Compact: { Title: 'Compacto' },
        FullSimulationOfTheFailuresBelowIsntYetGuaranteed: 'La simulación completa de las fallas a continuación aún no está garantizada.',
        Search: 'Buscar',
        Title: 'Fallas',
    },
    Ground: {
        Fuel: {
            CenterTank: 'Tanque Central',
            Completed: 'Completado',
            Defueling: 'Vaciado',
            EstimatedTime: 'Tiempo Estimado',
            LeftInnerTank: 'Depósito Interior Izquierdo',
            LeftOuterTank: 'Tanque Exterior Izquierdo',
            ReadyToStart: 'Listo para Empezar',
            Refuel: 'Repostar',
            RefuelTime: 'Tiempo de Repostaje',
            Refueling: 'Llenar el depósito',
            RightInnerTank: 'Depósito Interior Derecho',
            RightOuterTank: 'Tanque Exterior Derecho',
            Title: 'Combustible',
            TotalFuel: 'Combustible Total',
            Unavailable: 'No disponible',
        },
        Pushback: { Title: 'Retroceso' },
        Services: {
            CallBaggageTruck: 'Llame a Camión de Equipaje',
            CallCateringTruck: 'Llame a Camión de Catering',
            CallFuelTruck: 'Llame a Camión de Combustible',
            ConnectExternalPower: 'Conectar Alimentación Externa',
            ConnectJetBridge: 'Conecte el Puente Jet',
            DisconnectExternalPower: 'Desconectar Alimentación Externa',
            DoorAft: 'Puerta en Popa',
            DoorFwd: 'Puerta Adelante',
            Title: 'Servicios',
        },
        Title: 'Tierra',
    },
    Modals: {
        Cancel: 'Cancelar',
        Confirm: 'Confirmar',
        Okay: 'Aceptar',
    },
    NavigationAndCharts: {
        All: 'Todo',
        Altn: 'Altn',
        ExitFullscreenMode: 'Salir de modo pantalla completa',
        From: 'De',
        LocalFiles: {
            Both: 'Ambos',
            EstablishingConnection: 'Estableciendo conexión',
            FailedToEstablishConnection: 'No se pudo establecer la conexión.',
            FileName: 'Nombre de archivo',
            Image: 'Imagen',
            Pdf: 'PDF',
            Retry: 'Reintentar',
            Title: 'Archivos locales',
        },
        Navigraph: {
            AirportDoesNotExist: 'El aeropuerto no existe',
            AuthenticateWithNavigraph: 'Autenticación con Navigraph',
            InsufficientEnv: 'Archivo.env insuficiente',
            IntoYourBrowserAndEnterTheCodeBelow: 'en tu navegador e introduce el código a continuación\n',
            NoAirportSelected: 'Sin aeropuerto seleccionado',
            ResetNavigraphAuthentication: 'Restablecer la autenticación de Navigraph',
            ScanTheQrCodeOrOpen: 'Escanee el código QR o ábralo',
            Title: 'Navigraph',
        },
        PinnedCharts: {
            Delete: 'Eliminar',
            Edit: 'Editar',
            NoItemsFound: 'No se encontraron artículos.',
            ShowingChartsFromAllProviders: 'Mostrar gráficos de todos los proveedores',
            SortMethods: {
                AlphabeticalAZ: 'Alfabético: A -> Z',
                AlphabeticalZA: 'Alfabético - Z -> A',
                FirstAccessed: 'Acceso por primera vez',
                LastAccessed: 'Último acceso',
                None: 'Ninguno',
            },
            Title: 'Cartas Anclados',
            View: 'Ver',
        },
        PleaseWait: 'Por favor espera...',
        ShowingAllItems: 'Mostrar todos los artículos',
        ThereAreNoChartsToDisplay: 'No hay gráficos que mostrar.',
        ThereIsNoChartToDisplay: 'No hay ningún gráfico que mostrar.',
        Title: 'Navegación y Cartas',
        To: 'A',
    },
    Performance: {
        Data: 'Datos',
        Landing: {
            AirportIcao: 'Aeropuerto OACI',
            ApproachSpeed: 'Velocidad de aproximación',
            AutoLand: 'Tierra automática',
            Calculate: 'Calcular',
            Clear: 'Borrar',
            FillDataFrom: 'Rellenar datos de',
            FlapsConfiguration: 'Configuración de flaps',
            Low: 'Baja',
            MaximumManual: 'Manual máximo',
            Medium: 'Medio',
            OverweightProcedure: 'Procedimiento de sobrepeso',
            Qnh: 'QNH',
            ReverseThrust: 'Empuje inverso',
            RunwayAltitude: 'Altitud de pista',
            RunwayCondition: 'Estado de la pista',
            RunwayHeading: 'Encabezado de pista',
            RunwayLda: 'Pista LDA',
            RunwaySlope: 'Pendiente de pista',
            Temperature: 'Temperatura',
            Title: 'El Aterrizaje',
            Weight: 'Peso',
            WindDirection: 'Dirección del viento',
            WindMagnitude: 'Magnitud viento',
        },
        SYNC: 'Sincronizar',
        Title: 'Rendimiento',
        TopOfDescent: {
            Data: {
                Angle: 'Ángulo',
                CurrentAltitude: 'Altitud Actual',
                GroundSpeed: 'Velocidad respecto al suelo',
                TargetAltitude: 'Altitud Objetivo',
                Title: 'Datos',
            },
            GroundSpeed: {
                Add: 'Añadir',
                FetchingSpeedFromSimulator: 'Obteniendo velocidad del simulador',
                GroundSpeed: 'Velocidad respecto al suelo',
                ManualInput: 'Entrada Manual',
                MinAltitude: 'Mín. Altitud',
                RemoveLast: 'Eliminar el último',
                Sync: 'Sincronizar',
                Title: 'Velocidad respecto al suelo',
            },
            Result: {
                BeforeTarget: 'antes del objetivo',
                StartYourDescentAbout: 'Comienza tu descenso sobre',
                Title: 'Resultado',
            },
            Title: 'Cima del descenso',
        },
    },
    Presets: {
        AircraftStates: {
            Cancel: 'Cancelar',
            CurrentProcedureStep: 'Paso del Procedimiento Actual',
            PleaseConfirmLoadingOfPreset: 'Confirme la carga del ajuste preestablecido.',
            SelectAPresetToLoad: 'Seleccione un ajuste preestablecido para cargar',
            TheAircraftMustBeOnTheGroundToLoadAPreset: 'La aeronave debe estar en tierra para cargar un preajuste.',
            TheAircraftMustBeOntheGroundToLoadAPreset: 'La aeronave debe estar en tierra para cargar un preajuste.',
            Title: 'Estados de aeronaves',
        },
        InteriorLighting: {
            LoadPreset: 'Cargar Preajuste',
            NoName: 'Sin nombre',
            SavePreset: 'Guardar Preajuste',
            SelectAnInteriorLightingPresetToLoadOrSave: 'Seleccione un preajuste de iluminación interior para cargar o guardar.',
            TheAircraftMustBePoweredForInteriorLightingPresets: 'La aeronave debe estar encendida para preajustes de iluminación interior.',
            Title: 'Iluminación interior',
        },
        Title: 'Predeterminados',
    },
    Pushback: {
        Backward: 'Atrás',
        CallTug: 'Llamar a Tug',
        Forward: 'Adelante',
        Halt: 'Detener',
        ParkingBrake: {
            Off: 'DESACTIVADO',
            On: 'ACTIVADO',
            Title: 'Freno de estacionamiento',
        },
        TugDirection: 'Dirección del remolcador',
        TugSpeed: 'Velocidad del remolcador',
    },
};
