/* eslint-disable max-len */
export const es = {
    'AirTrafficControl': {
        Active: 'Activo',
        ConnectHoppieACARS: 'Conecta Hoppie ACARS',
        DisconnectHoppieACARS: 'Desconecte Hoppie ACARS',
        FlightnumberIsAlreadyInUse: 'El número de vuelo ya está en uso.',
        HoppieError: 'Error de Hoppie',
        HoppieSystemRequiresAUserIdWhichNeedsToBeSetInSettings: 'El sistema Hoppie requiere una identificación de usuario que debe configurarse en Ajustes > ATSU /AOC.',
        InvalidLogonCodeUsed: 'Se usó código de inicio de sesión no válido',
        NoInformationAvailableForThisFrequency: 'NO HAY INFORMACIÓN DISPONIBLE PARA ESTA FRECUENCIA',
        SetActive: 'Establecer como activo',
        SetStandby: 'Establecer modo de espera',
        Standby: 'En espera',
        Title: 'Control de tráfico aéreo',
    },
    'Checklist': { ThereAreRemainingAutofillChecklistItemsThatHaveNotYetBeenCompleted: 'Quedan elementos de la lista de verificación de autocompletar que aún no se han completado' },
    'Checklists': {
        AreYouSureYouWantToResetAllChecklists: '¿Estás seguro de que quieres restablecer todas las listas de verificación?',
        AreYouSureYouWantToResetChecklists: '¿Estás seguro de que quieres restablecer todas las listas de verificación?',
        ChecklistResetWarning: 'Advertencia de restablecimiento de lista de verificación',
        MarkChecklistAsComplete: 'Marcar lista de verificación como completa',
        MarkItemAsComplete: 'Marcar artículo como completo',
        ProceedToNextChecklist: 'Pasar a la siguiente lista de verificación',
        ResetAll: 'Restablecer todos',
        ResetChecklist: 'Restablecer lista de verificación',
        TheLastChecklistIsComplete: 'La última lista de verificación está completa',
        ThereAreRemainingAutofillChecklistItemsThatHaveNotYetBeenCompleted: 'Quedan elementos de la lista de verificación de autocompletar que aún no se han completado',
        Title: 'Listas de Verificación',
    },
    'Dashboard': {
        ImportantInformation: {
            Checklists: {
                NoRelevantChecklists: 'Sin listas de verificación relevantes',
                Title: 'Listas de Verificación',
            },
            GoToPage: 'Ir a la página',
            Maintenance: {
                NoActiveFailures: 'Sin fallos activos',
                Title: 'Mantenimiento',
            },
            PinnedCharts: {
                NoPinnedCharts: 'Sin gráficos anclados',
                Title: 'Cartas Anclados',
            },
            TT: { RearrangeWidgets: 'Reorganizar widgets' },
            Title: 'Información importante',
            Weather: {
                AirPressure: 'Presión de aire',
                DewPoint: 'Punto de rocío',
                IcaoInvalid: 'ICAO inválido o sin METAR disponible',
                Loading: 'Cargando…',
                MetarParsingError: 'El METAR recibido no puede ser analizado',
                NoIcaoProvided: 'No se proporciona la ICAO',
                Raw: 'Sin procesar',
                TT: {
                    SwitchToIconView: 'Cambiar a vista de iconos',
                    SwitchToRawMetarView: 'Cambiar a la vista de Raw METAR',
                },
                Temperature: 'Temperatura',
                Title: 'Clima',
                WindSpeed: 'Velocidad del viento',
            },
        },
        Title: 'Tablero',
        YourFlight: {
            Alternate: 'Alternar',
            AverageWind: 'Viento promedio',
            CompanyRoute: 'Ruta de la empresa',
            CostIndex: 'Índice de costos',
            CruiseAlt: 'Crucero Alt.',
            ImportSimBriefData: 'Importar Datos de SimBrief',
            Route: 'Ruta',
            SimBriefDataNotYetLoaded: 'Los datos de SimBrief aún no se han cargado.',
            Title: 'Tu vuelo',
            ZFW: 'ZFW',
        },
    },
    'Dispatch': {
        Ofp: {
            ImportSimBriefData: 'Importar Datos de SimBrief',
            TT: {
                IncreaseFontSize: 'Aumentar tamaño de fuente',
                ReduceFontSize: 'Reducir el tamaño de fuente',
            },
            Title: 'OFP',
            YouHaveNotYetImportedAnySimBriefData: 'Aún no ha importado ningún dato de SimBrief.',
        },
        Overview: {
            Engines: 'Motores',
            MMO: 'MMO',
            MRW: 'MRW',
            MTOW: 'MTOW',
            MZFW: 'MZFW',
            MaximumCargo: 'Carga Máxima',
            MaximumFuelCapacity: 'Capacidad Máxima de Combustible',
            MaximumPassengers: 'Número Máximo de Pasajeros',
            Model: 'Modelo',
            Range: 'Rango',
            Title: 'Resumen',
        },
        Title: 'Envío',
    },
    'Failures': {
        Comfort: { Title: 'Confort' },
        Compact: { Title: 'Compacto' },
        FullSimulationOfTheFailuresBelowIsntYetGuaranteed: 'La simulación completa de las fallas a continuación aún no está garantizada.',
        Search: 'Buscar',
        Title: 'Fallas',
    },
    'Ground': {
        Fuel: {
            CenterTank: 'Tanque Central',
            Completed: 'Completado',
            Defueling: 'Vaciado',
            EstimatedDuration: 'Duración estimada (minutos)',
            EstimatedTime: 'Tiempo Estimado',
            LeftInnerTank: 'Depósito Interior Izquierdo',
            LeftOuterTank: 'Tanque Exterior Izquierdo',
            ReadyToStart: 'Listo para Empezar',
            Refuel: 'Repostar',
            RefuelTime: 'Tiempo de Repostaje',
            Refueling: 'Llenar el depósito',
            RightInnerTank: 'Depósito Interior Derecho',
            RightOuterTank: 'Tanque Exterior Derecho',
            TT: {
                AircraftMustBeColdAndDarkToChangeRefuelTimes: 'La aeronave debe estar fría y oscura para cambiar los tiempos de repostaje',
                FillBlockFuelFromSimBrief: 'Combustible para bloques de llenado de SimBrief',
            },
            Title: 'Combustible',
            TotalFuel: 'Combustible Total',
            Unavailable: 'No disponible',
        },
        Pushback: { Title: 'Retroceso' },
        Services: {
            BaggageTruck: 'Camión de equipaje',
            CateringTruck: 'Camión de catering',
            DoorAft: 'Puerta en Popa',
            DoorFwd: 'Puerta Adelante',
            ExternalPower: 'Alimentación externa',
            FuelTruck: 'Camión de combustible',
            JetBridge: 'Puente de embarque',
            Title: 'Servicios',
        },
        Title: 'Tierra',
    },
    'Modals': {
        Cancel: 'Cancelar',
        Confirm: 'Confirmar',
        Okay: 'Aceptar',
    },
    'NavigationAndCharts': {
        All: 'Todo',
        Altn: 'Altn',
        ExitFullscreenMode: 'Salir de modo pantalla completa',
        From: 'De',
        LocalFiles: {
            Both: 'Ambos',
            EstablishingConnection: 'Estableciendo conexión',
            FailedToEstablishConnection: 'No se pudo establecer la conexión.',
            FileName: 'Nombre de archivo',
            Image: 'Imagen',
            Pdf: 'PDF',
            Retry: 'Reintentar',
            Title: 'Archivos locales',
        },
        Navigraph: {
            AirportDoesNotExist: 'El aeropuerto no existe',
            AuthenticateWithNavigraph: 'Autenticación con Navigraph',
            InsufficientEnv: 'Archivo.env insuficiente',
            IntoYourBrowserAndEnterTheCodeBelow: 'en tu navegador e introduce el código a continuación\n',
            NoAirportSelected: 'Sin aeropuerto seleccionado',
            ResetNavigraphAuthentication: 'Restablecer la autenticación de Navigraph',
            ScanTheQrCodeOrOpen: 'Escanee el código QR o ábralo',
            Title: 'Navigraph',
        },
        PinnedCharts: {
            Delete: 'Eliminar',
            Edit: 'Editar',
            NoItemsFound: 'No se encontraron artículos.',
            SearchPlaceholder: 'Buscar',
            ShowingChartsFromAllProviders: 'Mostrar gráficos de todos los proveedores',
            SortMethods: {
                AlphabeticalAZ: 'Alfabético: A -> Z',
                AlphabeticalZA: 'Alfabético - Z -> A',
                FirstAccessed: 'Acceso por primera vez',
                LastAccessed: 'Último acceso',
                None: 'Ninguno',
            },
            TT: {
                ChangeChartProvider: 'Cambiar proveedor de gráficos',
                ChangeChartSortMethod: 'Cambiar método de clasificación de gráficos',
            },
            Title: 'Cartas Anclados',
            View: 'Ver',
        },
        PleaseWait: 'Por favor espera...',
        ShowingAllItems: 'Mostrar todos los artículos',
        TT: {
            FitChartToHeight: 'Ajustar tabla a altura',
            FitChartToWidth: 'Ajustar la tabla a la anchura',
            ResetMovement: 'Reiniciar movimiento',
            RotateLeft45Degrees: 'Girar 45 grados a la izquierda',
            RotateRight45Degrees: 'Girar 45 grados a la derecha',
            ZoomIn: 'Acercar',
            ZoomOut: 'Alejar',
        },
        ThereAreNoChartsToDisplay: 'No hay gráficos que mostrar.',
        ThereIsNoChartToDisplay: 'No hay ningún gráfico que mostrar.',
        Title: 'Navegación y Cartas',
        To: 'A',
    },
    'Performance': {
        Data: 'Datos',
        Landing: {
            AirportIcao: 'Aeropuerto OACI',
            ApproachSpeed: 'Velocidad de aproximación',
            ApproachSpeedUnit: 'kts',
            AutoLand: 'Tierra automática',
            Calculate: 'Calcular',
            Clear: 'Borrar',
            DropDownNo: 'No',
            DropDownYes: 'Sí',
            FillDataFrom: 'Rellenar datos de',
            FlapsConfiguration: 'Configuración de flaps',
            Low: 'Baja',
            MaximumManual: 'Manual máximo',
            Medium: 'Medio',
            OverweightProcedure: 'Procedimiento de sobrepeso',
            Qnh: 'QNH',
            ReverseThrust: 'Empuje inverso',
            RunwayAltitude: 'Altitud de pista',
            RunwayAltitudeUnit: 'pies sobre el nivel del mar',
            RunwayCondition: 'Estado de la pista',
            RunwayHeading: 'Encabezado de pista',
            RunwayHeadingUnit: '°',
            RunwayLda: 'Pista LDA',
            RunwayLdaUnitFt: 'pi',
            RunwayLdaUnitMeter: 'm',
            RunwaySlope: 'Pendiente de pista',
            TT: {
                YouNeedToEnterAnIcaoCodeInOrderToMakeAMetarRequest: 'Debe introducir un código de la OACI para realizar una solicitud METAR',
                YouNeedToLoadSimBriefDataInOrderToAutofillData: 'Debe cargar datos de SimBrief para completar automáticamente los datos',
            },
            Temperature: 'Temperatura',
            Title: 'El Aterrizaje',
            UnitFt: 'pi',
            UnitMeter: 'm',
            Weight: 'Peso',
            WindDirection: 'Dirección del viento',
            WindDirectionUnit: '°',
            WindMagnitude: 'Magnitud viento',
            WindMagnitudeUnit: 'kts',
        },
        SYNC: 'Sincronizar',
        Title: 'Rendimiento',
        TopOfDescent: {
            Data: {
                Angle: 'Ángulo',
                CurrentAltitude: 'Altitud Actual',
                Distance: 'Distancia',
                GroundSpeed: 'Velocidad respecto al suelo',
                TargetAltitude: 'Altitud Objetivo',
                Title: 'Datos',
                UnitAngleDegrees: 'grados',
                UnitFeet: 'pies',
                UnitFtMin: 'pi/min',
                UnitNM: 'NM',
                VerticalSpeed: 'Velocidad Vertical',
            },
            GroundSpeed: {
                Add: 'Añadir',
                FetchingSpeedFromSimulator: 'Obteniendo velocidad del simulador',
                GroundSpeed: 'Velocidad respecto al suelo',
                ManualInput: 'Entrada Manual',
                MinAltitude: 'Mín. Altitud',
                RemoveLast: 'Eliminar el último',
                Sync: 'Sincronizar',
                Title: 'Velocidad respecto al suelo',
                UnitKnots: 'nudos',
                UnitKt: 'kt',
            },
            Result: {
                BeforeTarget: 'antes del objetivo',
                DesiredDescentAngle: 'Ángulo de descenso deseado',
                DesiredVerticalSpeed: 'Velocidad vertical requerida',
                StartYourDescentAbout: 'Comienza tu descenso sobre',
                Title: 'Resultado',
            },
            TT: {
                DesynchronizeInputWithAircraftsCurrentAltitude: 'Desincronizar la entrada con la altitud actual de la aeronave',
                SynchronizeInputWithAircraftsCurrentAltitude: 'Sincronizar la entrada con la altitud actual de la aeronave',
            },
            Title: 'Cima del descenso',
        },
    },
    'Presets': {
        AircraftStates: {
            Cancel: 'Cancelar',
            ColdDark: 'Cold & Dark',
            ConfirmationDialogMsg: 'Confirme la carga del ajuste preestablecido.',
            CurrentProcedureStep: 'Paso del Procedimiento Actual',
            PleaseConfirmLoadingOfPreset: 'Confirme la carga del ajuste preestablecido.',
            ReadyPushback: 'Preparado para Pushback',
            ReadyTakeoff: 'Listo para despegar',
            ReadyTaxi: 'Listo para Taxi',
            SelectAPresetToLoad: 'Seleccione un ajuste preestablecido para cargar',
            TheAircraftMustBeOnTheGroundToLoadAPreset: 'La aeronave debe estar en tierra para cargar un preajuste.',
            TheAircraftMustBeOntheGroundToLoadAPreset: 'La aeronave debe estar en tierra para cargar un preajuste.',
            Title: 'Estados de aeronaves',
            Turnaround: 'Preparación',
        },
        InteriorLighting: {
            AircraftNeedsToBePoweredToLoadPresets: 'La aeronave necesita energía para cargar los ajustes preestablecidos',
            AircraftNeedsToBePoweredToSavePresets: 'La aeronave necesita energía para guardar los ajustes preestablecidos',
            LoadPreset: 'Cargar Preajuste',
            LoadingPreset: 'Cargando preajuste',
            NoName: 'Sin nombre',
            PleaseConfirmSavingPreset: 'Confirme guardar el ajuste preestablecido',
            SavePreset: 'Guardar Preajuste',
            SavingPreset: 'Guardar ajustes preestablecidos',
            SelectAnInteriorLightingPresetToLoadOrSave: 'Seleccione un preajuste de iluminación interior para cargar o guardar.',
            TT: {
                AircraftMustBePowered: 'La aeronave debe estar propulsada',
                ClickTextToChangeThePresetsName: 'Haga clic en Texto para cambiar el nombre del ajuste preestablecido',
                LoadThisPreset: 'Cargar este preajuste',
                SaveTheCurrentLightingLevels: 'Guarde los niveles de iluminación actuales',
            },
            TheAircraftMustBePoweredForInteriorLightingPresets: 'La aeronave debe estar encendida para preajustes de iluminación interior.',
            Title: 'Iluminación interior',
        },
        Title: 'Predeterminados',
    },
    'Pushback': {
        Backward: 'Atrás',
        CallTug: 'Llamar a Tug',
        Forward: 'Adelante',
        Halt: 'Detener',
        ParkingBrake: {
            Off: 'DESACTIVADO',
            On: 'ACTIVADO',
            Title: 'Freno de estacionamiento',
        },
        TugDirection: 'Dirección del remolcador',
        TugSpeed: 'Velocidad del remolcador',
    },
    'Settings': {
        About: { Title: 'Sobre' },
        AircraftOptionsPinPrograms: {
            AccelerationHeight: 'Altura de aceleración (pi)',
            EngineOutAccelerationHeight: 'Altura de aceleración del motor fuera (pi)',
            IsisBaroUnit: 'Unidad Baro del ISIS',
            IsisMetricAltitude: 'Altura métrica de ISIS',
            PaxSigns: 'Señales PAX',
            RmpVhfSpacing: 'Espaciado VHF RMP',
            ThrustReductionHeight: 'Altura de reducción de empuje (pi)',
            Title: 'Opciones de aeronaves/programas de pines',
            WeightUnit: 'Unidad de peso',
        },
        AtsuAoc: {
            AtisAtcSource: 'Fuente ATIS/ATC',
            AutomaticallyImportSimBriefData: 'Importación automática de datos de SimBrief',
            Enable: 'Habilitar',
            EnableTelex: 'Habilitar TELEX',
            ErrorReporting: 'Informe de errores',
            HoppieUserId: 'ID de usuario de Hoppie',
            MetarSource: 'Fuente METAR',
            OptionalA32nxErrorReporting: 'Informe de errores A32NX opcional',
            PleaseCheckThatYouHaveCorrectlyEnteredYourSimbBriefUsernameOrPilotId: 'Compruebe que ha introducido correctamente su nombre de usuario o identificador de piloto de SimBrief.',
            SimBriefUsernamePilotId: 'Nombre de usuario/ID de piloto de SimBrief',
            TafSource: 'Fuente TAF',
            Telex: 'TÉLEX',
            TelexEnablesFreeTextAndLiveMap: 'TELEX permite texto libre y mapa en vivo. Si se habilita, los datos de posición de la aeronave se publican durante el vuelo. Los mensajes son públicos y no están moderados. USE ESTA FUNCIÓN BAJO SU PROPIO RIESGO. Para obtener más información sobre TELEX y las funciones que habilita, vaya a https://docs.flybywiresim.com/telex.',
            TelexWarning: 'Advertencia TELEX',
            Title: 'ATSU / AOC',
            YouAreAbleToOptIntoAnonymousErrorReporting: 'Puede optar por la notificación de errores anónima que nos permitirá diagnosticar, controlar y solucionar los problemas a un ritmo más rápido. Esta función es completamente opcional y nunca recopilaremos sus datos personales, pero puede permitirle obtener asistencia más fácilmente y solucionar los problemas que encuentre a un ritmo más rápido.',
            YourSimBriefPilotIdHasBeenValidatedAndUpdatedTo: 'Su ID de piloto de SimBrief se ha validado y actualizado a',
        },
        Audio: {
            Announcements: 'Anuncios',
            BoardingMusic: 'Música de embarque',
            EngineInteriorVolume: 'Volumen interior del motor',
            ExteriorMasterVolume: 'Volumen maestro exterior',
            PassengerAmbience: 'Ambiente pasajero',
            PtuAudibleInCockpit: 'PTU audible en cabina',
            Title: 'Sonido',
            WindInteriorVolume: 'Volumen interior del viento',
        },
        Fast: 'Rápido',
        Instant: 'Instante',
        Real: 'Real',
        Realism: {
            AdirsAlignTime: 'Tiempo de alineación de ADIRS',
            AutofillChecklists: 'Listas de verificación de autocompletar',
            BoardingTime: 'Hora de embarque',
            DatalinkTransmissionTime: 'Tiempo de transmisión DATALINK',
            DmcSelfTestTime: 'Tiempo de autoprueba de DMC',
            HomeCockpitMode: 'Modo de cabina de inicio',
            McduFocusTimeout: 'Tiempo de espera de enfoque de MCDU (segundos)',
            McduKeyboardInput: 'Entrada de teclado MCDU',
            SeparateTillerFromRudderInputs: 'Separe las entradas del timón del timón',
            Title: 'Realismo',
        },
        SimOptions: {
            Active: 'Activo',
            Auto: 'Auto',
            Calibrate: 'Calibrar',
            DefaultBarometerUnit: 'Unidad de barómetro predeterminada',
            DynamicRegistrationDecal: 'Calcomanía de registro dinámico',
            EnabledMcduServerConnectionAutoDeactivatesAfter5MinutesIfNoSuccessfulConnection: 'Habilitar la conexión del servidor MCDU (se desactiva automáticamente después de 5 minutos si la conexión no se realiza correctamente)',
            ExternalMcduServerPort: 'Puerto de servidor MCDU externo',
            Hpa: 'hPa',
            Inactive: 'Inactivo',
            LoadOnly: 'Solo carga',
            None: 'Ninguno',
            Off: 'Desactivado',
            Save: 'Guardar',
            SyncMsfsFlightPlan: 'Plan de vuelo MSFS sincronizado',
            ThrottleDetents: 'Retenes del acelerador',
            Title: 'Opciones de Sim',
            UseCalculatedIlsSignals: 'Usar señales ILS calculadas',
            inHg: 'inHg',
        },
        ThrottleConfig: {
            Apply: 'Aplicar',
            AreYouSureThatYouWantToResetYourCurrentThrottleConfigurationToTheirDefaultStates: '¿Está seguro de que desea restablecer los valores de configuración del acelerador actuales a sus estados predeterminados? Esta acción es irreversible.',
            Axis: 'Eje',
            Back: 'Atrás',
            ConfigureEnd: 'Configurar fin',
            CurrentValue: 'Valor actual',
            Deadband: 'Banda muerta',
            ErrorOverlapMsg: 'se superpone con',
            IndependentAxis: 'Eje independiente',
            LoadFromFile: 'Cargar desde archivo',
            PleaseEnterAValidDeadzone: 'Por favor, introduzca una zona muerta válida',
            ResetToDefaults: 'Restablecer los valores predeterminados',
            ReverseFull: 'Marcha atrás completa',
            ReverseIdle: 'Ralentí inverso',
            ReverserOnAxis: 'Inversor en el eje',
            SaveAndApply: 'Guardar y aplicar',
            SetFromThrottle: 'Set de Throttle',
            ThrottleConfigurationReset: 'Reinicio de la configuración',
        },
        Title: 'Ajustes',
        Unrealistic: 'Poco realista',
        flyPad: {
            AutoBrightness: 'Brillo automático',
            AutomaticallyShowOnscreenKeyboard: 'Mostrar teclado en pantalla automáticamente',
            Blue: 'Azul',
            Brightness: 'Brillo',
            Dark: 'Oscuro',
            Language: 'Idioma',
            Light: 'Claro',
            Local: 'Local',
            LocalTimeFormat: 'Formato de hora local',
            OnscreenKeyboardLayout: 'Distribución del teclado en pantalla',
            ShowColoredRawMetar: 'Mostrar METAR sin procesar coloreado',
            ShowStatusBarFlightProgressIndicator: 'Mostrar indicador de progreso de vuelo en la barra',
            Theme: 'Tema',
            TimeDisplayed: 'Tiempo que se muestra',
            Title: 'flyPad',
            TwelveHours: '12h',
            TwentyFourHours: '24h',
            Utc: 'UTC',
            UtcAndLocal: 'UTC y local',
        },
    },
    'Settings.flyPad.BatteryLifeEnabled': 'Duración de la batería simulada',
    'StatusBar': {
        Apr: 'Abr',
        Aug: 'Ago',
        Dec: 'Dic',
        Feb: 'Feb',
        Fri: 'Vie',
        Jan: 'Ene',
        Jun: 'Jun',
        Mar: 'Mar',
        May: 'May',
        Mon: 'Lun',
        Nov: 'Nov',
        Oct: 'Oct',
        Sat: 'Sáb',
        Sep: 'Sep',
        Sun: 'Dom',
        TT: {
            ConnectedToLocalApi: 'Conectado a la API local',
            DisconnectedFromLocalApi: 'Desconectado de la API local',
            TurnOffOrShutdownEfb: 'Apagar o apagar EFB',
        },
        Thu: 'Jue',
        Tue: 'Mar',
        Wed: 'Mié',
    },
};
