export const fr = {
    AirTrafficControl: {
        Active: 'Actif',
        ConnectHoppieACARS: "Connecter l'ACARS Hoppie",
        DisconnectHoppieACARS: "Déconnecter l'ACARS Hoppie",
        FlightnumberIsAlreadyInUse: 'Le numéro de vol est déjà utilisé.',
        HoppieError: 'Erreur Hoppie',
        HoppieSystemRequiresAUserIdWhichNeedsToBeSetInSettings: "Hoppie requiert un ID d'utilisateur, qui doit être configuré dans Options > ATSU / AOC.",
        InvalidLogonCodeUsed: "Code d'ouverture de session non valide utilisé.",
        NoInformationAvailableForThisFrequency: 'AUCUNE INFORMATION DISPONIBLE POUR CETTE FRÉQUENCE',
        SetActive: 'Passer en actif',
        SetStandby: 'Passer en réserve',
        Standby: 'Réserve',
        Title: 'Contrôle du trafic aérien',
    },
    Checklist: {
        ThereAreRemainingAutofillChecklistItemsThatHaveNotYetBeenCompleted: "Il reste des éléments de la check-list en saisie automatique qui n'ont pas encore été complétés",
    },
    Checklists: {
        AreYouSureYouWantToResetAllChecklists: 'Êtes-vous sûr de vouloir réinitialiser toutes les check-lists ?',
        AreYouSureYouWantToResetChecklists: 'Êtes-vous sûr de vouloir réinitialiser toutes les check-lists ?',
        ChecklistResetWarning: 'Avertissement',
        MarkChecklistAsComplete: 'Marquer la liste comme complète',
        MarkItemAsComplete: "Compléter l'item",
        ProceedToNextChecklist: 'Passer à la check-list suivante',
        ResetAll: 'Réinitialiser tout',
        ResetChecklist: 'Réinitialiser la check-list',
        TheLastChecklistIsComplete: 'La dernière check-list est complète',
        ThereAreRemainingAutofillChecklistItemsThatHaveNotYetBeenCompleted: "Il reste des éléments de la check-list en saisie automatique qui n'ont pas encore été complétés",
        Title: 'Check-lists',
    },
    Dashboard: {
        ImportantInformation: {
            Checklists: {
                NoRelevantChecklists: 'Aucune liste de contrôle pertinente',
                Title: 'Listes de contrôle',
            },
            GoToPage: 'Aller à la page',
            Maintenance: {
                NoActiveFailures: 'Aucune défaillance active',
                Title: 'Maintenance',
            },
            PinnedCharts: {
                NoPinnedCharts: 'Aucun graphique épinglé',
                Title: 'Cartes épinglées',
            },
            TT: {
                RearrangeWidgets: 'Réorganiser les widgets',
            },
            Title: 'Informations importantes',
            Weather: {
                AirPressure: "Pression de l'air",
                DewPoint: 'Point de rosée',
                Loading: 'Chargement',
                Raw: 'Brut',
                TT: {
                    SwitchToIconView: 'Basculer vers la vue Icône',
                    SwitchToRawMetarView: 'Basculer vers la vue Raw Metar',
                },
                Temperature: 'Température',
                Title: 'Météo',
                WindSpeed: 'Vitesse du vent',
            }
        },
        Title: 'Tableau de bord',
        YourFlight: {
            Alternate: 'Alternate',
            AverageWind: 'Vent moyen',
            CompanyRoute: "Route de l'entreprise",
            CostIndex: 'Indice de coût',
            CruiseAlt: 'Cruise Alt.',
            ImportSimBriefData: 'Importer les données de SimBrief',
            Route: 'Itinéraire',
            SimBriefDataNotYetLoaded: 'Les données SimBrief ne sont pas encore chargées.',
            Title: 'Votre vol',
            ZFW: 'ZFW',
        }
    },
    Dispatch: {
        Ofp: {
            ImportSimBriefData: 'Importer les données de SimBrief',
            TT: {
                IncreaseFontSize: 'Augmenter la taille de la police',
                ReduceFontSize: 'Réduire la taille de police',
            },
            Title: 'OFP',
            YouHaveNotYetImportedAnySimBriefData: "Vous n'avez pas encore importé de données SimBrief.",
        },
        Overview: {
            Engines: 'Motorisation',
            MMO: 'MMO',
            MRW: 'MRW',
            MTOW: 'MTOW',
            MZFW: 'MZFW',
            MaximumCargo: 'Cargo maximum',
            MaximumFuelCapacity: 'Capacité maximale de carburant',
            MaximumPassengers: 'Nombre maximum de passagers',
            Model: 'Modèle',
            Range: 'Autonomie',
            Title: 'Aperçu',
        },
        Title: 'Dépêche',
    },
    Failures: {
        Comfort: {
            Title: 'Confort',
        },
        Compact: {
            Title: 'Compacte',
        },
        FullSimulationOfTheFailuresBelowIsntYetGuaranteed: "La simulation complète de toutes les pannes n'est pas garantie.",
        Search: 'Rechercher',
        Title: 'Pannes',
    },
    Ground: {
        Fuel: {
            CenterTank: 'Réservoir Central',
            Completed: 'Terminé',
            Defueling: 'Déravitaillement',
            EstimatedTime: 'Durée Estimée',
            LeftInnerTank: 'Réservoir Intérieur Gauche',
            LeftOuterTank: 'Réservoir Extérieur Gauche',
            ReadyToStart: 'Prêt à Démarrer',
            Refuel: 'Ravitaillement',
            RefuelTime: 'Temps de Ravitaillement',
            Refueling: 'Ravitaillement',
            RightInnerTank: 'Réservoir Intérieur Droit',
            RightOuterTank: 'Réservoir Extérieur Droit',
            TT: {
                AircraftMustBeColdAndDarkToChangeRefuelTimes: 'Les avions doivent être froids et sombres pour modifier les temps de ravitaillement',
                FillBlockFuelFromSimBrief: 'Fill Block Fuel de SimBrief',
            },
            Title: 'Carburant',
            TotalFuel: 'Carburant Total',
            Unavailable: 'Indisponible',
        },
        Pushback: {
            Title: 'Pushback',
        },
        Services: {
            CallBaggageTruck: 'Connecter le camion à bagages',
            CallCateringTruck: "Connecter le camion d'approvisionnement",
            CallFuelTruck: 'Connecter le camion à carburant',
            ConnectExternalPower: "Connecter l'alimentation externe",
            ConnectJetBridge: 'Connecter la passerelle',
            DisconnectExternalPower: "Déconnecter l'alimentation externe",
            DoorAft: 'Porte arrière',
            DoorFwd: 'Porte avant',
            Title: 'Services',
        },
        Title: 'Sol',
    },
    Modals: {
        Cancel: 'Annuler',
        Confirm: 'Confirmer',
        Okay: "D'accord",
    },
    NavigationAndCharts: {
        All: 'Tout',
        Altn: 'Alton',
        ExitFullscreenMode: 'Quitter le mode plein-écran',
        From: 'De',
        LocalFiles: {
            Both: 'Les deux',
            EstablishingConnection: 'Établissement de la connexion…',
            FailedToEstablishConnection: "Impossible d'établir la connexion.",
            FileName: 'Nom du fichier',
            Image: 'Images',
            Pdf: 'PDF',
            Retry: 'Réessayer',
            Title: 'Fichiers locaux',
        },
        Navigraph: {
            AirportDoesNotExist: "L'aéroport n'existe pas",
            AuthenticateWithNavigraph: 'Authentifier avec Navigraph',
            InsufficientEnv: 'Fichier .env insuffisant',
            IntoYourBrowserAndEnterTheCodeBelow: 'dans votre navigateur et saisissez le code ci-dessous\n',
            NoAirportSelected: 'Aucun aéroport sélectionné',
            ResetNavigraphAuthentication: "Réinitialiser l'authentification Navigraph",
            ScanTheQrCodeOrOpen: 'Scannez le code QR ou ouvrez',
            Title: 'Navigraph',
        },
        PinnedCharts: {
            Delete: 'Supprimer',
            Edit: 'Modifier',
            NoItemsFound: 'Aucun élément trouvé.',
            ShowingChartsFromAllProviders: 'Affichage des graphiques de tous les fournisseurs',
            SortMethods: {
                AlphabeticalAZ: 'Alphabétique - A -> Z',
                AlphabeticalZA: 'Alphabétique - Z -> A',
                FirstAccessed: 'Premier accès',
                LastAccessed: 'Dernier accès',
                None: 'Aucun',
            },
            TT: {
                ChangeChartProvider: 'Fournisseur de graphiques de changement',
                ChangeChartSortMethod: 'Modifier la méthode de tri du graphique',
            },
            Title: 'Cartes épinglées',
            View: 'Afficher',
        },
        PleaseWait: 'Patientez SVP...',
        ShowingAllItems: 'Afficher tous les articles',
        TT: {
            FitChartToHeight: "Tableau d'ajustement à la hauteur",
            FitChartToWidth: "Tableau d'ajustement à la largeur",
            ResetMovement: 'Mouvement Reset',
            'RotateLeft45Degrees': 'Rotation à gauche de 45 degrés',
            'RotateRight45Degrees': 'Rotation à droite de 45 degrés',
            ZoomIn: 'Zoom avant',
            ZoomOut: 'Zoom arrière',
        },
        ThereAreNoChartsToDisplay: "Il n'y a aucune carte à afficher.",
        ThereIsNoChartToDisplay: "Il n'y a aucune carte à afficher.",
        Title: 'Navigation et Cartes',
        To: 'À',
    },
    Performance: {
        Data: 'Données',
        Landing: {
            AirportIcao: "Code OACI de l'aéroport",
            ApproachSpeed: "Vitesse d'approche",
            AutoLand: 'Terre automatique',
            Calculate: 'Calculer',
            Clear: 'Effacer',
            FillDataFrom: 'Remplir de',
            FlapsConfiguration: 'Configuration des volets',
            Low: 'Faible',
            MaximumManual: 'Manuel maximum',
            Medium: 'Moyenne',
            OverweightProcedure: 'Procédure en surpoids',
            Qnh: 'QNH',
            ReverseThrust: 'Poussée inverse',
            RunwayAltitude: 'Altitude de la piste',
            RunwayCondition: 'État de la piste',
            RunwayHeading: 'Cap de piste',
            RunwayLda: 'Piste LDA',
            RunwaySlope: 'Pente de piste',
            Temperature: 'Température',
            Title: "L'atterrissage",
            Weight: 'Poids',
            WindDirection: 'Direction du vent',
            WindMagnitude: 'Ampleur du vent',
        },
        SYNC: 'SYNCHRONISER',
        Title: 'Performances',
        TopOfDescent: {
            Data: {
                Angle: 'Angle',
                CurrentAltitude: 'Altitude actuelle',
                Distance: 'Distance',
                GroundSpeed: 'Vitesse au sol',
                TargetAltitude: 'Altitude cible',
                Title: 'Données',
                VerticalSpeed: 'Vitesse verticale',
            },
            GroundSpeed: {
                Add: 'Ajouter',
                FetchingSpeedFromSimulator: 'Récupération de la vitesse depuis le simulator',
                GroundSpeed: 'Vitesse au sol',
                ManualInput: 'Entrée manuelle',
                MinAltitude: 'Altitude min.',
                RemoveLast: 'Supprimer le dernier',
                Sync: 'SYNCHRONISER',
                Title: 'Vitesse au sol',
            },
            Result: {
                BeforeTarget: 'avant la cible',
                StartYourDescentAbout: 'Commencez votre descente à propos de',
                Title: 'Résultat',
            },
            Title: 'Au sommet de la descente',
        }
    },
    Presets: {
        AircraftStates: {
            Cancel: 'Annuler',
            CurrentProcedureStep: 'Étape de procédure en cours',
            PleaseConfirmLoadingOfPreset: 'Veuillez confirmer le chargement du préréglage.',
            SelectAPresetToLoad: 'Sélectionnez un préréglage à charger',
            TheAircraftMustBeOnTheGroundToLoadAPreset: "L'avion doit être au sol pour charger un préréglage.",
            TheAircraftMustBeOntheGroundToLoadAPreset: "L'avion doit être au sol pour charger un préréglage.",
            Title: 'États des aéronefs',
        },
        InteriorLighting: {
            AircraftNeedsToBePoweredToLoadPresets: "L'avion doit être alimenté pour charger des préréglages",
            AircraftNeedsToBePoweredToSavePresets: "L'avion doit être alimenté pour enregistrer les préréglages",
            LoadPreset: 'Charger le préréglage',
            LoadingPreset: 'Préréglage de chargement',
            NoName: 'Sans nom',
            PleaseConfirmSavingPreset: "Veuillez confirmer l'enregistrement du préréglage",
            SavePreset: 'Sauver le préréglage',
            SavingPreset: "Préréglage d'enregistrement",
            SelectAnInteriorLightingPresetToLoadOrSave: "Sélectionnez un préréglage d'éclairage intérieur à charger ou à enregistrer.",
            TT: {
                AircraftMustBePowered: "L'avion doit être propulsé",
                ClickTextToChangeThePresetsName: 'Cliquez sur Texte pour modifier le nom du préréglage',
                LoadThisPreset: 'Charger ce préréglage',
                SaveTheCurrentLightingLevels: "Enregistrer les niveaux d'éclairage actuels",
            },
            TheAircraftMustBePoweredForInteriorLightingPresets: "L'avion doit être alimenté pour les préréglages d'éclairage intérieur.",
            Title: 'Éclairage intérieur',
        },
        Title: 'Préréglages',
    },
    Pushback: {
        Backward: 'Reculer',
        CallTug: "Remorqueur d'appel",
        Forward: 'Avancer',
        Halt: 'Interrompre',
        ParkingBrake: {
            Off: 'DÉSACTIVÉ',
            On: 'ACTIVÉ',
            Title: 'Frein de stationnement',
        },
        TugDirection: 'Direction du remorqueur',
        TugSpeed: 'Vitesse du remorqueur',
    },
    Settings: {
        About: {
            Title: 'À propos',
        },
        AircraftOptionsPinPrograms: {
            AccelerationHeight: "Hauteur d'accélération",
            EngineOutAccelerationHeight: "Hauteur d'accélération du moteur en panne",
            IsisBaroUnit: "Unité Baro de l'EIIS",
            IsisMetricAltitude: 'Altitude métrique ISIS',
            PaxSigns: 'Panneaux PAX',
            RmpVhfSpacing: 'Espacement VHF RMP',
            ThrustReductionHeight: 'Hauteur de réduction de poussée',
            Title: 'Options des aéronefs/programmes de broches',
            WeightUnit: 'Unité de poids',
        },
        AtsuAoc: {
            AtisAtcSource: 'Source ATIS/ATC',
            AutomaticallyImportSimBriefData: 'Importer automatiquement les données SimBrief',
            Enable: 'Activer',
            EnableTelex: 'Activer le télex',
            ErrorReporting: "Rapport d'erreurs",
            HoppieUserId: "Nom d'utilisateur Hoppie",
            MetarSource: 'Source METAR',
            "OptionalA32nxErrorReporting": "Rapport d'erreurs A32NX en option",
            PleaseCheckThatYouHaveCorrectlyEnteredYourSimbBriefUsernameOrPilotId: "Vérifiez que vous avez correctement saisi votre nom d'utilisateur SimBrief ou votre identifiant de pilote.",
            SimBriefUsernamePilotId: "Nom d'utilisateur/ID pilote SimBrief",
            TafSource: 'Source du TAF',
            Telex: 'Télex',
            TelexEnablesFreeTextAndLiveMap: "Le TELEX permet le texte libre et la carte en direct. Si cette option est activée, les données de position de l'avion sont publiées pour la durée du vol. Les messages sont publics et ne sont pas modérés. UTILISEZ CETTE FONCTIONNALITÉ À VOS RISQUES ET PÉRILS. Pour en savoir plus sur le TELEX et les fonctionnalités qu'il permet, rendez-vous sur https://docs.flybywiresim.com/telex.",
            TelexWarning: 'Avertissement TELEX',
            Title: 'ATSU/AOC',
            YouAreAbleToOptIntoAnonymousErrorReporting: "Vous pouvez opter pour le signalement d'erreurs anonyme qui nous permettra de diagnostiquer, de surveiller et de traiter les problèmes plus rapidement. Cette fonctionnalité est totalement facultative et nous ne collecterons jamais vos données personnelles, mais elle peut vous permettre d'obtenir plus facilement de l'aide et de résoudre plus rapidement les problèmes que vous rencontrez.",
            YourSimBriefPilotIdHasBeenValidatedAndUpdatedTo: 'Votre SimBrief PilotID a été validé et mis à jour pour',
        },
        Audio: {
            Announcements: 'Annonces',
            BoardingMusic: "Musique d'embarquement",
            EngineInteriorVolume: 'Volume intérieur du moteur',
            ExteriorMasterVolume: 'Volume principal extérieur',
            PassengerAmbience: 'Ambiance des passagers',
            PtuAudibleInCockpit: 'PTU audible dans le cockpit',
            Title: 'Audio',
            WindInteriorVolume: 'Volume intérieur du vent',
        },
        Fast: 'Rapide',
        Instant: 'Instantané',
        Real: 'Réel',
        Realism: {
            AdirsAlignTime: "Temps d'alignement ADIRS",
            AutofillChecklists: 'Listes de contrôle de saisie automatique',
            BoardingTime: "Heure d'embarquement",
            DatalinkTransmissionTime: 'Durée de transmission DATALINK',
            DmcSelfTestTime: "Temps d'auto-test DMC",
            HomeCockpitMode: 'Mode Cockpit domestique',
            McduFocusTimeout: "Délai d'attente du focus MCDU (secondes)",
            McduKeyboardInput: 'Entrée clavier MCDU',
            SeparateTillerFromRudderInputs: 'Barre franche séparée des entrées de gouvernail',
            Title: 'Réalisme',
        },
        SimOptions: {
            Calibrate: 'Calibrer',
            DefaultBarometerUnit: 'Baromètre par défaut',
            DynamicRegistrationDecal: "Autocollant d'enregistrement dynamique",
            "EnabledMcduServerConnectionAutoDeactivatesAfter5MinutesIfNoSuccessfulConnection": "Activer la connexion au serveur MCDU (désactivation automatique après 5 minutes en cas d'échec de la connexion)",
            ExternalMcduServerPort: 'Port du serveur MCDU externe',
            LoadOnly: 'Charge seule',
            None: 'Aucun',
            Save: 'Enregistrer',
            SyncMsfsFlightPlan: 'Synchroniser le plan de vol MSFS',
            ThrottleDetents: "Détenteurs d'accélérateur",
            Title: 'Options de carte SIM',
            UseCalculatedIlsSignals: 'Utiliser des signaux ILS calculés',
        },
        ThrottleConfig: {
            Apply: 'Appliquer',
            AreYouSureThatYouWantToResetYourCurrentThrottleConfigurationToTheirDefaultStates: "Êtes-vous sûr de vouloir réinitialiser les paramètres actuels de configuration de l'accélérateur à leurs états par défaut ? Cette action est irréversible.",
            Axis: 'Axis',
            Back: 'Retour',
            ConfigureEnd: 'Configurer la fin',
            CurrentValue: 'Valeur actuelle',
            Deadband: 'Deadband',
            IndependentAxis: 'Axe indépendant',
            LoadFromFile: 'Charger depuis un fichier',
            PleaseEnterAValidDeadzone: 'Veuillez saisir une zone morte valide',
            ResetToDefaults: 'Rétablir les valeurs par défaut',
            ReverseFull: 'Inverse complète',
            ReverseIdle: 'Inverse Idle',
            ReverserOnAxis: 'Inverseur sur axe',
            SaveAndApply: 'Enregistrer et appliquer',
            SetFromThrottle: 'Set de Throttle',
            ThrottleConfigurationReset: 'Réinitialisation de la configuration',
        },
        Title: 'Paramètres',
        Unrealistic: 'Irréalisme',
        flyPad: {
            '12Hour': '12 heures',
            '24Hour': '24 heures',
            AutoBrightness: 'Luminosité automatique',
            AutomaticallyShowOnscreenKeyboard: "Afficher automatiquement le clavier à l'écran",
            Blue: 'Bleu',
            Brightness: 'Luminosité',
            Dark: 'Sombre',
            Language: 'Langue',
            Light: 'Clair',
            Local: 'Locale',
            LocalTimeFormat: "Format de l'heure locale",
            OnscreenKeyboardLayout: "Disposition du clavier à l'écran",
            ShowColoredRawMetar: 'Afficher le métal brut coloré',
            ShowStatusBarFlightProgressIndicator: "Afficher la barre d'état indicateur de progression du vol",
            Theme: 'Thème',
            TimeDisplayed: 'Heure affichée',
            Title: 'flyPad',
            Utc: 'UTC',
            UtcAndLocal: 'UTC et local',
        }
    },
    StatusBar: {
        Apr: 'Avr',
        Aug: 'Août',
        Dec: 'Déc',
        Feb: 'Fév',
        Fri: 'Ven',
        Jan: 'Janv',
        Jun: 'Juin',
        Mar: 'Mars',
        May: 'Mai',
        Mon: 'Lun',
        Nov: 'Nov',
        Oct: 'Oct',
        Sat: 'Samedi',
        Sep: 'Sept',
        Sun: 'Dim',
        TT: {
            ConnectedToLocalApi: "Connecté à l'API locale",
            DisconnectedFromLocalApi: "Déconnecté de l'API locale",
            TurnOffOrShutdownEfb: "Éteindre ou arrêter l'EFB",
        },
        Thu: 'Jeu',
        Tue: 'Mar',
        Wed: 'Mer',
    }
};