export const fr = {
    AirTrafficControl: {
        Active: 'Actif',
        ConnectHoppieACARS: "Connecter l'ACARS Hoppie",
        DisconnectHoppieACARS: "Déconnecter l'ACARS Hoppie",
        HoppieError: 'Erreur Hoppie',
        HoppieSystemRequiresAUserIdWhichNeedsToBeSetInSettings: "Hoppie requiert un ID d'utilisateur, qui doit être configuré dans Options > ATSU / AOC.",
        NoInformationAvailableForThisFrequency: 'AUCUNE INFORMATION DISPONIBLE POUR CETTE FRÉQUENCE',
        SetActive: 'Passer en actif',
        SetStandby: 'Passer en réserve',
        Standby: 'Réserve',
        Title: 'Contrôle du trafic aérien',
    },
    Checklist: { ThereAreRemainingAutofillChecklistItemsThatHaveNotYetBeenCompleted: "Il reste des éléments de la check-list en saisie automatique qui n'ont pas encore été complétés" },
    Checklists: {
        AreYouSureYouWantToResetAllChecklists: 'Êtes-vous sûr de vouloir réinitialiser toutes les check-lists ?',
        AreYouSureYouWantToResetChecklists: 'Êtes-vous sûr de vouloir réinitialiser toutes les check-lists ?',
        ChecklistResetWarning: 'Avertissement',
        MarkChecklistAsComplete: 'Marquer la liste comme complète',
        MarkItemAsComplete: "Compléter l'item",
        ProceedToNextChecklist: 'Passer à la check-list suivante',
        ResetAll: 'Réinitialiser tout',
        ResetChecklist: 'Réinitialiser la check-list',
        TheLastChecklistIsComplete: 'La dernière check-list est complète',
        ThereAreRemainingAutofillChecklistItemsThatHaveNotYetBeenCompleted: "Il reste des éléments de la check-list en saisie automatique qui n'ont pas encore été complétés",
        Title: 'Check-lists',
    },
    Dashboard: {
        Alternate: 'Alternate',
        AverageWind: 'Vent moyen',
        Checklists: 'Check-lists',
        CompanyRoute: 'Company Route',
        CostIndex: 'Cost Index',
        CruiseAlt: 'Altitude de croisière',
        GoToPage: 'Aller a la page',
        ImportSimBriefData: 'Importer les données de SimBrief',
        ImportantInformation: 'Information importante',
        Maintenance: 'Maintenance',
        NoActiveFailures: 'Aucune panne active',
        NoIcaoProvided: 'Pas de code OACI entré',
        NoPinnedCharts: 'Aucune carte épinglée',
        NoRelevantChecklists: 'Aucune check-list pertinente',
        PinnedCharts: 'Cartes épinglées',
        Route: 'Itinéraire',
        SimBriefDataNotYetLoaded: 'Les données SimBrief ne sont pas encore chargées.',
        Weather: 'Météo',
        YourFlight: 'Votre vol',
        ZFW: 'ZFW',
    },
    Dispatch: {
        Ofp: {
            ImportSimBriefData: 'Importer les données de SimBrief',
            Title: 'OFP',
            YouHaveNotYetImportedAnySimBriefData: "Vous n'avez pas encore importé de données SimBrief.",
        },
        Overview: {
            Engines: 'Motorisation',
            MMO: 'MMO',
            MRW: 'MRW',
            MTOW: 'MTOW',
            MZFW: 'MZFW',
            MaximumCargo: 'Cargo maximum',
            MaximumFuelCapacity: 'Capacité maximale de carburant',
            MaximumPassengers: 'Nombre maximum de passagers',
            Model: 'Modèle',
            Range: 'Autonomie',
            Title: 'Aperçu',
        },
        Title: 'Dépêche',
    },
    Failures: {
        Comfort: { Title: 'Confort' },
        Compact: { Title: 'Compacte' },
        FullSimulationOfTheFailuresBelowIsntYetGuaranteed: "La simulation complète de toutes les pannes n'est pas garantie.",
        Search: 'Rechercher',
        Title: 'Pannes',
    },
    Ground: {
        Fuel: {
            CenterTank: 'Réservoir Central',
            Completed: 'Terminé',
            Defueling: 'Déravitaillement',
            EstimatedTime: 'Durée Estimée',
            LeftInnerTank: 'Réservoir Intérieur Gauche',
            LeftOuterTank: 'Réservoir Extérieur Gauche',
            ReadyToStart: 'Prêt à Démarrer',
            Refuel: 'Ravitaillement',
            RefuelTime: 'Temps de Ravitaillement',
            Refueling: 'Ravitaillement',
            RightInnerTank: 'Réservoir Intérieur Droit',
            RightOuterTank: 'Réservoir Extérieur Droit',
            Title: 'Carburant',
            TotalFuel: 'Carburant Total',
            Unavailable: 'Indisponible',
        },
        Pushback: { Title: 'Pushback' },
        Services: {
            CallBaggageTruck: 'Connecter le camion à bagages',
            CallCateringTruck: "Connecter le camion d'approvisionnement",
            CallFuelTruck: 'Connecter le camion à carburant',
            ConnectExternalPower: "Connecter l'alimentation externe",
            ConnectJetBridge: 'Connecter la passerelle',
            DisconnectExternalPower: "Déconnecter l'alimentation externe",
            DoorAft: 'Porte arrière',
            DoorFwd: 'Porte avant',
            Title: 'Services',
        },
        Title: 'Sol',
    },
    Modals: {
        Cancel: 'Annuler',
        Confirm: 'Confirmer',
        Okay: "D'accord",
    },
    NavigationAndCharts: {
        All: 'Tout',
        Altn: 'Alton',
        ExitFullscreenMode: 'Quitter le mode plein-écran',
        From: 'De',
        LocalFiles: {
            Both: 'Les deux',
            EstablishingConnection: 'Établissement de la connexion…',
            FailedToEstablishConnection: "Impossible d'établir la connexion.",
            FileName: 'Nom du fichier',
            Image: 'Images',
            Pdf: 'PDF',
            Retry: 'Réessayer',
            Title: 'Fichiers locaux',
        },
        Navigraph: {
            AirportDoesNotExist: "L'aéroport n'existe pas",
            AuthenticateWithNavigraph: 'Authentifier avec Navigraph',
            InsufficientEnv: 'Fichier .env insuffisant',
            IntoYourBrowserAndEnterTheCodeBelow: 'dans votre navigateur et saisissez le code ci-dessous\n',
            NoAirportSelected: 'Aucun aéroport sélectionné',
            ResetNavigraphAuthentication: "Réinitialiser l'authentification Navigraph",
            ScanTheQrCodeOrOpen: 'Scannez le code QR ou ouvrez',
            Title: 'Navigraph',
        },
        PinnedCharts: {
            Delete: 'Supprimer',
            Edit: 'Modifier',
            NoItemsFound: 'Aucun élément trouvé.',
            ShowingChartsFromAllProviders: 'Affichage des graphiques de tous les fournisseurs',
            SortMethods: {
                AlphabeticalAZ: 'Alphabétique - A -> Z',
                AlphabeticalZA: 'Alphabétique - Z -> A',
                FirstAccessed: 'Premier accès',
                LastAccessed: 'Dernier accès',
                None: 'Aucun',
            },
            Title: 'Cartes épinglées',
            View: 'Afficher',
        },
        PleaseWait: 'Patientez SVP...',
        ShowingAllItems: 'Afficher tous les articles',
        ThereAreNoChartsToDisplay: "Il n'y a aucune carte à afficher.",
        ThereIsNoChartToDisplay: "Il n'y a aucune carte à afficher.",
        Title: 'Navigation et Cartes',
        To: 'À',
    },
    Performance: {
        Data: 'Données',
        Landing: {
            AirportIcao: "Code OACI de l'aéroport",
            ApproachSpeed: "Vitesse d'approche",
            AutoLand: 'Terre automatique',
            Calculate: 'Calculer',
            Clear: 'Effacer',
            FillDataFrom: 'Remplir de',
            FlapsConfiguration: 'Configuration des volets',
            Low: 'Faible',
            MaximumManual: 'Manuel maximum',
            Medium: 'Moyenne',
            OverweightProcedure: 'Procédure en surpoids',
            Qnh: 'QNH',
            ReverseThrust: 'Poussée inverse',
            RunwayAltitude: 'Altitude de la piste',
            RunwayCondition: 'État de la piste',
            RunwayHeading: 'Cap de piste',
            RunwayLda: 'Piste LDA',
            RunwaySlope: 'Pente de piste',
            Temperature: 'Température',
            Title: "L'atterrissage",
            Weight: 'Poids',
            WindDirection: 'Direction du vent',
            WindMagnitude: 'Ampleur du vent',
        },
        SYNC: 'SYNCHRONISER',
        Title: 'Performances',
        TopOfDescent: {
            Data: {
                Angle: 'Angle',
                CurrentAltitude: 'Altitude actuelle',
                GroundSpeed: 'Vitesse au sol',
                TargetAltitude: 'Altitude cible',
                Title: 'Données',
            },
            GroundSpeed: {
                Add: 'Ajouter',
                FetchingSpeedFromSimulator: 'Récupération de la vitesse depuis le simulator',
                GroundSpeed: 'Vitesse au sol',
                ManualInput: 'Entrée manuelle',
                MinAltitude: 'Altitude min.',
                RemoveLast: 'Supprimer le dernier',
                Sync: 'SYNCHRONISER',
                Title: 'Vitesse au sol',
            },
            Result: {
                BeforeTarget: 'avant la cible',
                StartYourDescentAbout: 'Commencez votre descente à propos de',
                Title: 'Résultat',
            },
            Title: 'Au sommet de la descente',
        },
    },
    Presets: {
        AircraftStates: {
            Cancel: 'Annuler',
            CurrentProcedureStep: 'Étape de procédure en cours',
            PleaseConfirmLoadingOfPreset: 'Veuillez confirmer le chargement du préréglage.',
            SelectAPresetToLoad: 'Sélectionnez un préréglage à charger',
            TheAircraftMustBeOnTheGroundToLoadAPreset: "L'avion doit être au sol pour charger un préréglage.",
            TheAircraftMustBeOntheGroundToLoadAPreset: "L'avion doit être au sol pour charger un préréglage.",
            Title: 'États des aéronefs',
        },
        InteriorLighting: {
            LoadPreset: 'Charger le préréglage',
            NoName: 'Sans nom',
            SavePreset: 'Sauver le préréglage',
            SelectAnInteriorLightingPresetToLoadOrSave: "Sélectionnez un préréglage d'éclairage intérieur à charger ou à enregistrer.",
            TheAircraftMustBePoweredForInteriorLightingPresets: "L'avion doit être alimenté pour les préréglages d'éclairage intérieur.",
            Title: 'Éclairage intérieur',
        },
        Title: 'Préréglages',
    },
    Pushback: {
        Backward: 'Reculer',
        CallTug: "Remorqueur d'appel",
        Forward: 'Avancer',
        Halt: 'Interrompre',
        ParkingBrake: {
            Off: 'DÉSACTIVÉ',
            On: 'ACTIVÉ',
            Title: 'Frein de stationnement',
        },
        TugDirection: 'Direction du remorqueur',
        TugSpeed: 'Vitesse du remorqueur',
    },
};
