/* eslint-disable max-len */
export const sl = {
    'AirTrafficControl': {
        Active: 'Aktivno',
        ConnectHoppieACARS: 'Povežite Hoppie ACARS',
        DisconnectHoppieACARS: 'Odklopite Hoppie ACARS',
        FlightnumberIsAlreadyInUse: 'Številka leta je že v uporabi.',
        HoppieError: 'Hoppie Napaka',
        HoppieSystemRequiresAUserIdWhichNeedsToBeSetInSettings: 'Sistem Hoppie zahteva ID uporabnika, ki ga je treba nastaviti v nastavitvah > ATSU/AOC.',
        InvalidLogonCodeUsed: 'Neveljavna prijavna koda.',
        NoInformationAvailableForThisFrequency: 'ZA TO FREKVENCO NI NA VOLJO NOBENIH INFORMACIJ',
        SetActive: 'Nastavi kot Aktivno',
        SetStandby: 'Nastavi v pripravljenost',
        Standby: 'V pripravljenosti',
        Title: 'Kontrola Zračnega Prometa',
    },
    'Checklist': { ThereAreRemainingAutofillChecklistItemsThatHaveNotYetBeenCompleted: 'Nekateri elementi kontrolnega seznama še niso dokončani' },
    'Checklists': {
        AreYouSureYouWantToResetAllChecklists: 'Ali ste prepričani, da želite ponastaviti vse kontrolne sezname?',
        AreYouSureYouWantToResetChecklists: 'Ali ste prepričani, da želite ponastaviti vse kontrolne sezname?',
        ChecklistResetWarning: 'Opozorilo o Ponastavitvi Kontrolnega Seznama',
        MarkChecklistAsComplete: 'Označi kontrolni seznam kot dokončan',
        MarkItemAsComplete: 'Označi element kot dokončen',
        ProceedToNextChecklist: 'Nadaljujte z naslednjim kontrolnim seznamom',
        ResetAll: 'Ponastavi Vse',
        ResetChecklist: 'Ponastavi Kontrolni Seznam',
        TheLastChecklistIsComplete: 'Zadnji kontrolni seznam je končan',
        ThereAreRemainingAutofillChecklistItemsThatHaveNotYetBeenCompleted: 'Nekateri elementi kontrolnega seznama še niso dokončani',
        Title: 'Kontrolni seznami',
    },
    'Dashboard': {
        ImportantInformation: {
            Checklists: {
                NoRelevantChecklists: 'Ni ustreznih kontrolnih seznamov',
                Title: 'Kontrolni seznami',
            },
            GoToPage: 'Pojdi na stran',
            Maintenance: {
                NoActiveFailures: 'Ni aktivnih okvar',
                Title: 'Vzdrževanje',
            },
            PinnedCharts: {
                NoPinnedCharts: 'Ni pripetih kart',
                Title: 'Pripete karte',
            },
            TT: { RearrangeWidgets: 'Preurejanje pripomočkov' },
            Title: 'Pomembne informacije',
            Weather: {
                AirPressure: 'Zražni tlak',
                DewPoint: 'Rosišče',
                IcaoInvalid: 'Neveljaven ICAO oz. METAR ni na voljo',
                Loading: 'Nalagam',
                MetarParsingError: 'Prejetega METAR-ja ni bilo mogoče razčleniti',
                NoIcaoProvided: 'ICAO ni naveden',
                Raw: 'Nerazčlenjeno',
                TT: {
                    SwitchToIconView: 'Preklopi na ikonski pogled',
                    SwitchToRawMetarView: 'Preklop na nerazčlenjene podatke METAR',
                },
                Temperature: 'Temperatura',
                Title: 'Vreme',
                WindSpeed: 'Hitrost vetra',
            },
        },
        Title: 'Nadzorna plošča',
        YourFlight: {
            Alternate: 'Nadomestno',
            AverageWind: 'Povprečni veter',
            CompanyRoute: 'Company Route',
            CostIndex: 'Stroškovni indeks',
            CruiseAlt: 'Cruise Alt.',
            ImportSimBriefData: 'Uvoz podatkov iz SimBrief-a',
            Route: 'Načrt poti',
            SimBriefDataNotYetLoaded: 'SimBrief podatki še niso naloženi.',
            Title: 'Vaš let',
            ZFW: 'ZFW',
        },
    },
    'Dispatch': {
        Ofp: {
            ImportSimBriefData: 'Uvoz podatkov iz SimBrief-a',
            TT: {
                IncreaseFontSize: 'Povečaj pisavo',
                ReduceFontSize: 'Zmanjšanje velikosti pisave',
            },
            Title: 'OFP',
            YouHaveNotYetImportedAnySimBriefData: 'Zaenkrat še niste uvozili nobenih SimBrief podatkov.',
        },
        Overview: {
            Engines: 'Motorji',
            MMO: 'MMO',
            MRW: 'MRW',
            MTOW: 'MTOW',
            MZFW: 'MZFW',
            MaximumCargo: 'Maksimalni Tovor',
            MaximumFuelCapacity: 'Največja Kapaciteta Goriva',
            MaximumPassengers: 'Največje Število Potnikov',
            Model: 'Model',
            Range: 'Doseg',
            Title: 'Pregled',
        },
        Title: 'Odpošiljanje',
    },
    'Failures': {
        Comfort: { Title: 'Udobje' },
        Compact: { Title: 'Strnjeno' },
        FullSimulationOfTheFailuresBelowIsntYetGuaranteed: 'Celostna simulacija spodnjih napak še ni zagotovljena.',
        Search: 'Išči',
        Title: 'Napake',
    },
    'Ground': {
        Fuel: {
            CenterTank: 'Središčni Rezervoar',
            Completed: 'Dokončano',
            Defueling: 'Odtoči Gorivo',
            EstimatedDuration: 'Predvideno trajanje v minutah',
            EstimatedTime: 'Predvideni Čas',
            LeftInnerTank: 'Levi Notranji Rezervoar',
            LeftOuterTank: 'Levi Zunanji Rezervoar',
            ReadyToStart: 'Pripravljen za Začetek',
            Refuel: 'Napolni gorivo',
            RefuelTime: 'Čas polnjenja goriva',
            Refueling: 'Polnjenje z gorivom',
            RightInnerTank: 'Desni Notranji Rezervoar',
            RightOuterTank: 'Desni Zunanji Rezervoar',
            TT: {
                AircraftMustBeColdAndDarkToChangeRefuelTimes: 'Zrakoplov mora biti v stanju "temno in hladno", da lahko spremenite čas polnjena goriva.',
                FillBlockFuelFromSimBrief: 'Uvozi "Block Fuel" iz Simbrief-a',
            },
            Title: 'Gorivo',
            TotalFuel: 'Skupno Gorivo',
            Unavailable: 'Ni na voljo',
        },
        Pushback: { Title: 'Vlačilec' },
        Services: {
            BaggageTruck: 'Tovornjak za Prtljago',
            CateringTruck: 'Gostinski Tovornjak',
            DoorAft: 'Zadnja Vrata',
            DoorFwd: 'Sprednja Vrata',
            ExternalPower: 'Zunanje Napajanje',
            FuelTruck: 'Tovornjak z Gorivom',
            JetBridge: 'Potniški Most',
            Title: 'Storitve',
        },
        Title: 'Tla',
    },
    'Modals': {
        Cancel: 'Prekliči',
        Confirm: 'Potrdi',
        Okay: 'V redu',
    },
    'NavigationAndCharts': {
        All: 'Vse',
        Altn: 'Altn',
        ExitFullscreenMode: 'Zapri Celozaslonski Način',
        From: 'Od',
        LocalFiles: {
            Both: 'Oboje',
            EstablishingConnection: 'Vzpostavljanje Povezave',
            FailedToEstablishConnection: 'Vzpostavitev povezave neuspešno.',
            FileName: 'Ime datoteke',
            Image: 'Slika',
            Pdf: 'PDF',
            Retry: 'Poskusi znova',
            Title: 'Lokalne datoteke',
        },
        Navigraph: {
            AirportDoesNotExist: 'Letališče ne obstaja',
            AuthenticateWithNavigraph: 'Preverjanje pristnosti z Navigraph-om',
            InsufficientEnv: 'Nezadostna datoteka .env',
            IntoYourBrowserAndEnterTheCodeBelow: 'v brskalniku in vnesite spodnjo kodo',
            NoAirportSelected: 'Ni izbranega letališča',
            ResetNavigraphAuthentication: 'Ponastavitev Navigraph Avtentikacije',
            ScanTheQrCodeOrOpen: 'Skenirajte QR kodo ali Odprite',
            Title: 'Navigraph',
        },
        PinnedCharts: {
            Delete: 'Izbriši',
            Edit: 'Uredi',
            NoItemsFound: 'Ni najdenih rezultatov',
            SearchPlaceholder: 'Iskanje',
            ShowingChartsFromAllProviders: 'Prikaži karte vseh ponudnikov',
            SortMethods: {
                AlphabeticalAZ: 'Abecedno - A -> Z',
                AlphabeticalZA: 'Abecedno - Z -> A',
                FirstAccessed: 'Prvi dostop',
                LastAccessed: 'Zadnji dostop',
                None: 'Brez',
            },
            TT: {
                ChangeChartProvider: 'Spremeni ponudnika kart',
                ChangeChartSortMethod: 'Spreminjanje načina razvrščanja kart',
            },
            Title: 'Pripete karte',
            View: 'Pogled',
        },
        PleaseWait: 'Prosimo počakajte',
        ShowingAllItems: 'Prikazujem vse elemente',
        TT: {
            FitChartToHeight: 'Prilagodi karto po višini',
            FitChartToWidth: 'Prilagodi karto po širini',
            ResetMovement: 'Ponastavi premike',
            RotateLeft45Degrees: 'Zavrtite 45 stopinj v levo',
            RotateRight45Degrees: 'Zavrtite 45 stopinj v desno',
            ZoomIn: 'Povečaj',
            ZoomOut: 'Pomanjšaj',
        },
        ThereAreNoChartsToDisplay: 'Ni kart za prikaz.',
        ThereIsNoChartToDisplay: 'Ni karte za prikaz.',
        Title: 'Navigacija in Karte',
        To: 'Do',
    },
    'Performance': {
        Data: 'Podatki',
        Landing: {
            AirportIcao: 'ICAO Letališča',
            ApproachSpeed: 'Hitrost Prileta',
            ApproachSpeedUnit: 'kts',
            AutoLand: 'Auto Land',
            Calculate: 'Izračunaj',
            Clear: 'Počisti',
            DropDownNo: 'Ne',
            DropDownYes: 'Da',
            FillDataFrom: 'Izpolnite podatke iz',
            FlapsConfiguration: 'Konfiguracija Zakrilc',
            Low: 'Nizko',
            MaximumManual: 'Maximum Manual',
            Medium: 'Srednje',
            OverweightProcedure: 'Postopek ob Prekomerni Teži',
            Qnh: 'QNH',
            ReverseThrust: 'Vzvratni Potisk',
            RunwayAltitude: 'Višina Steze',
            RunwayAltitudeUnit: 'ft ASL',
            RunwayCondition: 'Stanje Steze',
            RunwayHeading: 'Smer Steze',
            RunwayHeadingUnit: '°',
            RunwayLda: 'LDA Steze',
            RunwayLdaUnitFt: 'ft',
            RunwayLdaUnitMeter: 'm',
            RunwaySlope: 'Nagib Steze',
            TT: {
                YouNeedToEnterAnIcaoCodeInOrderToMakeAMetarRequest: 'Če želite zahtevati METAR, morate prej vnesti kodo ICAO',
                YouNeedToLoadSimBriefDataInOrderToAutofillData: 'Za samodejno izpolnjevanje podatkov morate naložiti podatke iz SimBrief-a',
            },
            Temperature: 'Temperatura',
            Title: 'Pristanek',
            UnitFt: 'ft',
            UnitMeter: 'm',
            Weight: 'Teža',
            WindDirection: 'Smer Vetra',
            WindDirectionUnit: '°',
            WindMagnitude: 'Moč Vetra',
            WindMagnitudeUnit: 'kts',
        },
        SYNC: 'Sinhroniziraj',
        Title: 'Zmogljivost',
        TopOfDescent: {
            Data: {
                Angle: 'Kot',
                CurrentAltitude: 'Trenutna nadmorska višina',
                Distance: 'Razdalja',
                GroundSpeed: 'Ground Speed',
                TargetAltitude: 'Ciljna Nadmorska Višina',
                Title: 'Podatki',
                UnitAngleDegrees: 'stopinj',
                UnitFeet: 'čevlji',
                UnitFtMin: 'ft/min',
                UnitNM: 'NM',
                VerticalSpeed: 'Navpična hitrost',
            },
            GroundSpeed: {
                Add: 'Dodaj',
                FetchingSpeedFromSimulator: 'Pridobivanje hitrosti iz simulatorja',
                GroundSpeed: 'Talna Hitrost',
                ManualInput: 'Ročni Vnos',
                MinAltitude: 'Min. Nadmorska višina',
                RemoveLast: 'Odstrani Zadnje',
                Sync: 'Sinhroniziraj',
                Title: 'Talna Hitrost',
                UnitKnots: 'vozlov',
                UnitKt: 'kt',
            },
            Result: {
                BeforeTarget: 'pred ciljem',
                DesiredDescentAngle: 'Želeni kot spusta',
                DesiredVerticalSpeed: 'Želena Navpična Hitrost',
                StartYourDescentAbout: 'Začnite spust okvirno',
                Title: 'Rezultat',
            },
            TT: {
                DesynchronizeInputWithAircraftsCurrentAltitude: 'Desinhronizirajte vnos trenutne nadmorske višine zrakoplova',
                SynchronizeInputWithAircraftsCurrentAltitude: 'Sinhronizirajte vnos trenutne nadmorske višine zrakoplova',
            },
            Title: 'Vrh spusta',
        },
    },
    'Presets': {
        AircraftStates: {
            Cancel: 'Prekliči',
            ColdDark: 'Hladno in temno',
            ConfirmationDialogMsg: 'Prosimo, potrdite nalaganje prednastavitve.',
            CurrentProcedureStep: 'Trenutni Korak Postopka',
            PleaseConfirmLoadingOfPreset: 'Prosimo, potrdite nalaganje prednastavitve.',
            ReadyPushback: 'Pripravljen za Vleko',
            ReadyTakeoff: 'Pripravljen za Vzlet',
            ReadyTaxi: 'Pripravljen za taksiranje',
            SelectAPresetToLoad: 'Izberite Prednastavitev',
            TheAircraftMustBeOnTheGroundToLoadAPreset: 'Letalo mora biti na tleh, preden lahko naložite prednastavitev.',
            TheAircraftMustBeOntheGroundToLoadAPreset: 'Letalo mora biti na tleh, preden lahko naložite prednastavitev.',
            Title: 'Stanja Zrakoplova',
            Turnaround: 'Preobrat',
        },
        InteriorLighting: {
            AircraftNeedsToBePoweredToLoadPresets: 'Za nalaganje prednastavitev zrakoplov potrebuje napajanje',
            AircraftNeedsToBePoweredToSavePresets: 'Za shranjevanje prednastavitev zrakoplov potrebuje napajanje',
            LoadPreset: 'Naloži Prednastavitev',
            LoadingPreset: 'Nalaganje prednastavitve',
            NoName: 'Brez imena',
            PleaseConfirmSavingPreset: 'Prosimo, potrdite shranjevanje prednastavitve',
            SavePreset: 'Shrani Prednastavitev',
            SavingPreset: 'Shranjevanje prednastavitve',
            SelectAnInteriorLightingPresetToLoadOrSave: 'Izberite prednastavitev notranje osvetlitve, ki jo želite naložiti ali shraniti.',
            TT: {
                AircraftMustBePowered: 'Zrakoplov mora biti napajan',
                ClickTextToChangeThePresetsName: 'Kliknite Besedilo, če želite spremeniti ime Prednastavitve',
                LoadThisPreset: 'Naloži prednstavitev',
                SaveTheCurrentLightingLevels: 'Shrani trenutne ravni osvetlitve',
            },
            TheAircraftMustBePoweredForInteriorLightingPresets: 'Zrakoplov potrebuje napajanje za prednastavitve notranje osvetlitve.',
            Title: 'Notranja Razsvetljava',
        },
        Title: 'Prednastavitve',
    },
    'Pushback': {
        Backward: 'Vzvratno',
        CallTug: 'Pokliči vlačilec',
        Forward: 'Naprej',
        Halt: 'Ustavi',
        ParkingBrake: {
            Off: 'Izklop',
            On: 'Vklop',
            Title: 'Parkirna zavora',
        },
        TugDirection: 'Smer vlačilca',
        TugSpeed: 'Hitrost vlačilca',
    },
    'Settings': {
        About: { Title: 'Vizitka' },
        AircraftOptionsPinPrograms: {
            AccelerationHeight: 'Višina pospešitve (ft)',
            EngineOutAccelerationHeight: 'Višina pospeška ob izgubi motorja (ft)',
            IsisBaroUnit: 'ISIS Baro Enota',
            IsisMetricAltitude: 'ISIS metrična nadmorska višina',
            PaxSigns: 'PAX Znaki',
            RmpVhfSpacing: 'RMP VHF razmik',
            ThrustReductionHeight: 'Višina zmanjšanja potiska (ft)',
            Title: 'Možnosti Zrakoplova / Pripeti Programi',
            WeightUnit: 'Enota za težo',
        },
        AtsuAoc: {
            AtisAtcSource: 'ATIS/ATC Vir',
            AutomaticallyImportSimBriefData: 'Samodejni uvoz podatkov SimBrief',
            Enable: 'Omogoči',
            EnableTelex: 'Omogoči TELEX',
            ErrorReporting: 'Poročanje napak',
            HoppieUserId: 'Hoppie uporabniški ID',
            MetarSource: 'METAR Vir',
            OptionalA32nxErrorReporting: 'Prostovoljno poročanje o napakah A32NX',
            PleaseCheckThatYouHaveCorrectlyEnteredYourSimbBriefUsernameOrPilotId: 'Preverite, če ste pravilno vnesli svoje uporabniško ime SimBrief oz. ID pilota.',
            SimBriefUsernamePilotId: 'Simbrief uporabniško ime/ID',
            TafSource: 'TAF Vir',
            Telex: 'TELEX',
            TelexEnablesFreeTextAndLiveMap: 'TELEX omogoča "free text" in zemljevid v živo. Če je omogočen, so podatki o položaju zrakoplova objavljeni za čas trajanja leta. Sporočila so javna in niso moderirana. TO FUNKCIJO UPORABLJAJTE NA LASTNO ODGOVORNOST. Če želite izvedeti več o TELEX-u in funkcijah, ki jih omogoča, obiščite spletno mesto https://docs.flybywiresim.com/telex.',
            TelexWarning: 'TELEX Opozorilo',
            Title: 'ATSU / AOC',
            YouAreAbleToOptIntoAnonymousErrorReporting: 'Lahko se odločite za anonimno poročanje o napakah, kar nam bo omogočilo hitrejše diagnosticiranje, spremljanje in odpravljanje težav. Funkcija je popolnoma neobvezna in vaši osebni podatki niso zbirani, vendar vam lahko omogoči, da lažje dobite podporo in hitreje odpravite težave, na katere naletite.',
            YourSimBriefPilotIdHasBeenValidatedAndUpdatedTo: 'Vaš SimBrief PilotID je bil potrjen in posodobljen na',
        },
        Audio: {
            Announcements: 'Objave',
            BoardingMusic: 'Glasba pri Vkrcanju',
            EngineInteriorVolume: 'Zvok Motorja Znotraj',
            ExteriorMasterVolume: 'Zunanja Glasnost',
            PassengerAmbience: 'Zvoki Potnikov',
            PtuAudibleInCockpit: 'PTU slišen v pilotski kabini',
            Title: 'Zvok',
            WindInteriorVolume: 'Glasnost vetra znotraj',
        },
        Fast: 'Hitro',
        Instant: 'Takoj',
        Real: 'Resnično',
        Realism: {
            AdirsAlignTime: 'ADIRS Čas uskladitve',
            AutofillChecklists: 'Samodejno izpolni kontrolne sezname',
            BoardingTime: 'Čas vkrcanja',
            DatalinkTransmissionTime: 'DATALINK Čas oddajanja',
            DmcSelfTestTime: 'DMC samopreizkusni čas',
            HomeCockpitMode: 'Način "Home Cockpit"',
            McduFocusTimeout: 'MCDU Časovna omejitev fokusa (sekunde)',
            McduKeyboardInput: 'MCDU vnos s tipkovnico',
            SeparateTillerFromRudderInputs: 'Ločite delovanje krmilnika od krmila',
            Title: 'Realizem',
        },
        SimOptions: {
            Active: 'Aktivno',
            Auto: 'Samodejno',
            Calibrate: 'Kalibracija',
            DefaultBarometerUnit: 'Privzeta barometrična enota',
            DynamicRegistrationDecal: 'Dinamična Registracijska Nalepka',
            EnabledMcduServerConnectionAutoDeactivatesAfter5MinutesIfNoSuccessfulConnection: 'Omogoči povezavo s strežnikom MCDU (samodejna deaktivacija po 5 minutah, če ni uspešne povezave)',
            ExternalMcduServerPort: 'Zunanji MCDU Port',
            Hpa: 'hPa',
            Inactive: 'Neaktivno',
            LoadOnly: 'Naloži samo',
            None: 'Brez',
            Off: 'Izklopljeno',
            Save: 'Shrani',
            SyncMsfsFlightPlan: 'Sinhroniziraj z MSFS načrtom leta',
            ThrottleDetents: 'Odkloni Pogonskega Krmilnika',
            Title: 'Nastavitve simulatorja',
            UseCalculatedIlsSignals: 'Uporaba izračunanih signalov ILS',
            inHg: 'inHg',
        },
        ThrottleConfig: {
            Apply: 'Potrdi',
            AreYouSureThatYouWantToResetYourCurrentThrottleConfigurationToTheirDefaultStates: 'Ali ste prepričani, da želite ponastaviti trenutne konfiguracijske nastavitve pogonskega krmilnika na privzeto stanje? To dejanje je nepovratno.',
            Axis: 'Os',
            Back: 'Nazaj',
            ConfigureEnd: 'Končaj konfiguracijo',
            CurrentValue: 'Trenutna vrednost',
            Deadband: 'Mrtva trak',
            ErrorOverlapMsg: 'se prekriva z/s',
            IndependentAxis: 'Neodvisna os',
            LoadFromFile: 'Naloži iz datoteke',
            PleaseEnterAValidDeadzone: 'Prosimo, vnesite veljavno mrtvo cono',
            ResetToDefaults: 'Ponastavitev na privzete nastavitve',
            ReverseFull: 'Polna vzvratna moč',
            ReverseIdle: 'Vzvratni prosti tek',
            ReverserOnAxis: 'Vzvratni Pogon na Osi',
            SaveAndApply: 'Shrani in Potrdi',
            SetFromThrottle: 'Nastavi iz Pogonskega Krmilnika',
            ThrottleConfigurationReset: 'Ponastavitev konfiguracije pogonskega krmilnika',
        },
        Title: 'Nastavitve',
        Unrealistic: 'Nerealistično',
        flyPad: {
            AutoBrightness: 'Samodejna Svetlost',
            AutomaticallyShowOnscreenKeyboard: 'Samodejno Prikaži Zaslonsko Tipkovnico',
            Blue: 'Modra',
            Brightness: 'Svetlost',
            Dark: 'Temno',
            Language: 'Jezik',
            Light: 'Svetlo',
            Local: 'Lokalni Čas',
            LocalTimeFormat: 'Format Lokalnega Časa',
            OnscreenKeyboardLayout: 'Postavitev Zaslonske Tipkovnice',
            ShowColoredRawMetar: 'Prikaži obarvan nerazčlenjen METAR',
            ShowStatusBarFlightProgressIndicator: 'Pokaži kazalnik napredka leta v vrstici stanja',
            Theme: 'Tema',
            TimeDisplayed: 'Prikazan čas',
            Title: 'flyPad',
            TwelveHours: '12h',
            TwentyFourHours: '24h',
            Utc: 'UTC',
            UtcAndLocal: 'UTC in lokalni čas',
        },
    },
    'Settings.flyPad.BatteryLifeEnabled': 'Simulirano trajanje baterije',
    'StatusBar': {
        Apr: 'Apr',
        Aug: 'Avg',
        Dec: 'Dec',
        Feb: 'Feb',
        Fri: 'Pet',
        Jan: 'Jan',
        Jun: 'Jun',
        Mar: 'Mar',
        May: 'Maj',
        Mon: 'Pon',
        Nov: 'Nov',
        Oct: 'Okt',
        Sat: 'Sob',
        Sep: 'Sep',
        Sun: 'Ned',
        TT: {
            ConnectedToLocalApi: 'Povezan na lokalni API',
            DisconnectedFromLocalApi: 'Odklopljen iz lokalnega API',
            TurnOffOrShutdownEfb: 'Izklopi ali Zaustavi EFB',
        },
        Thu: 'Čet',
        Tue: 'Tor',
        Wed: 'Sre',
    },
};
