/* eslint-disable max-len */
export const zhHant = {
    'AirTrafficControl': {
        Active: 'Active',
        ConnectHoppieACARS: '連接 Hoppie ACARS',
        DisconnectHoppieACARS: 'Disconnect Hoppie ACARS',
        FlightnumberIsAlreadyInUse: '航班編號已？才用。',
        HoppieError: 'Hoppie 故障',
        HoppieSystemRequiresAUserIdWhichNeedsToBeSetInSettings: 'Hoppie 系統帳戶不少還未輸入 — 請在「設定」> 「ATU/AOC」內輸入。',
        InvalidLogonCodeUsed: '登錄號碼(logon code)無效。',
        NoInformationAvailableForThisFrequency: '此頻率沒有資料',
        SetActive: 'Set Active',
        SetStandby: 'Set Standby',
        Standby: 'Standby',
        Title: '空中管制',
    },
    'Checklist': { ThereAreRemainingAutofillChecklistItemsThatHaveNotYetBeenCompleted: '還有剩餘的自動充填核對項目尚未完成' },
    'Checklists': {
        AreYouSureYouWantToResetAllChecklists: '是否重置所有checklist？',
        AreYouSureYouWantToResetChecklists: '是否重置所有checklist？',
        ChecklistResetWarning: 'Checklist 重置警告',
        MarkChecklistAsComplete: '將此 checklist 標記為完成',
        MarkItemAsComplete: '將此項目標記為完成',
        ProceedToNextChecklist: '進入下一個 checklist',
        ResetAll: '全部重置',
        ResetChecklist: '重置此 checklist',
        TheLastChecklistIsComplete: '最後 checklist 已完成',
        ThereAreRemainingAutofillChecklistItemsThatHaveNotYetBeenCompleted: '還有剩餘的自動充填核對項目尚未完成',
        Title: 'Checklists',
    },
    'Dashboard': {
        ImportantInformation: {
            Checklists: {
                NoRelevantChecklists: '沒有相關的 checklist',
                Title: 'Checklists',
            },
            GoToPage: '跳到頁數',
            Maintenance: {
                NoActiveFailures: '無故障現行',
                Title: '維修',
            },
            PinnedCharts: {
                NoPinnedCharts: '沒有航圖編上',
                Title: '編上航圖',
            },
            TT: { RearrangeWidgets: '重新排列小組件' },
            Title: '重要資訊',
            Weather: {
                AirPressure: '氣壓',
                DewPoint: '露點',
                IcaoInvalid: 'ICAO invalid or no METAR available',
                Loading: '加载中…',
                MetarParsingError: 'Received METAR could not be parsed',
                NoIcaoProvided: 'No ICAO provided',
                Raw: '原始',
                TT: {
                    SwitchToIconView: '圖標',
                    SwitchToRawMetarView: '起源',
                },
                Temperature: '溫度',
                Title: '天氣',
                WindSpeed: '風速',
            },
        },
        Title: '控制台',
        YourFlight: {
            Alternate: '在備機場',
            AverageWind: '平均風力',
            CompanyRoute: '公司路線',
            CostIndex: 'Cost Index',
            CruiseAlt: '滑行高度',
            ImportSimBriefData: '導入 SimBrief 數據',
            Route: '航線',
            SimBriefDataNotYetLoaded: '尚未導入 SimBrief 數據。',
            Title: '您的航班',
            ZFW: 'ZFW',
        },
    },
    'Dispatch': {
        Ofp: {
            ImportSimBriefData: '導入 SimBrief 數據',
            TT: {
                IncreaseFontSize: '增大字體',
                ReduceFontSize: '減小字體',
            },
            Title: 'OFP',
            YouHaveNotYetImportedAnySimBriefData: '尚未導入 SimBrief 數據。',
        },
        Overview: {
            Engines: '引擎',
            MMO: 'MMO',
            MRW: 'MRW',
            MTOW: 'MTOW',
            MZFW: 'MZFW',
            MaximumCargo: '最大貨物重量',
            MaximumFuelCapacity: '最大燃油容量',
            MaximumPassengers: '最大客量',
            Model: '飛機型號',
            Range: '航距',
            Title: '概覽',
        },
        Title: '派遣',
    },
    'Failures': {
        Comfort: { Title: '解壓' },
        Compact: { Title: '加壓' },
        FullSimulationOfTheFailuresBelowIsntYetGuaranteed: '以下故障仿真度未能保證。',
        Search: '搜尋',
        Title: '故障',
    },
    'Ground': {
        Fuel: {
            CenterTank: '中央油箱',
            Completed: '完成',
            Defueling: '減油',
            EstimatedDuration: 'Estimated duration (minutes)',
            EstimatedTime: '估計時間',
            LeftInnerTank: '左內油箱',
            LeftOuterTank: '左外油箱',
            ReadyToStart: '預備開始',
            Refuel: '加油',
            RefuelTime: '加油時間',
            Refueling: '正在加油',
            RightInnerTank: '右內油箱',
            RightOuterTank: '右外油箱',
            TT: {
                AircraftMustBeColdAndDarkToChangeRefuelTimes: '飛機必須完全關掉才能改變加油時間',
                FillBlockFuelFromSimBrief: '由 SimBrief 填充油量',
            },
            Title: '燃油',
            TotalFuel: '總計油量',
            Unavailable: '唔用得',
        },
        Pushback: { Title: '推機' },
        Services: {
            BaggageTruck: 'Baggage Truck',
            CateringTruck: 'Catering Truck',
            DoorAft: '後門',
            DoorFwd: '正門',
            ExternalPower: 'External Power',
            FuelTruck: 'Fuel Truck',
            JetBridge: 'Jet Bridge',
            Title: '服務',
        },
        Title: '地勤',
    },
    'Modals': {
        Cancel: '取消',
        Confirm: '確定',
        Okay: '得',
    },
    'NavigationAndCharts': {
        All: '全部',
        Altn: '在備機場',
        ExitFullscreenMode: '退出全屏模式',
        From: '由',
        LocalFiles: {
            Both: '兩者',
            EstablishingConnection: '正在連接',
            FailedToEstablishConnection: '無法建立連接。',
            FileName: '文件名',
            Image: '圖片',
            Pdf: 'PDF',
            Retry: '重試',
            Title: '電腦文件',
        },
        Navigraph: {
            AirportDoesNotExist: '無此機場',
            AuthenticateWithNavigraph: 'Navigraph 驗證',
            InsufficientEnv: '.env 文件不足',
            IntoYourBrowserAndEnterTheCodeBelow: '進入您的瀏覽器，然後輸入下面的代碼\n',
            NoAirportSelected: '未有選擇機場',
            ResetNavigraphAuthentication: '重置 Navigraph 驗證',
            ScanTheQrCodeOrOpen: '掃描二維碼或打開',
            Title: 'Navigraph',
        },
        PinnedCharts: {
            Delete: '删除',
            Edit: '編輯',
            NoItemsFound: '找不到項目',
            SearchPlaceholder: 'Search',
            ShowingChartsFromAllProviders: '現正顯示所有提供商的航圖',
            SortMethods: {
                AlphabeticalAZ: '按字母順序排列 A -> Z',
                AlphabeticalZA: '按字母順序排列 A -> Z',
                FirstAccessed: '首次訪問',
                LastAccessed: '上次訪問',
                None: '冇',
            },
            TT: {
                ChangeChartProvider: '轉換航圖提供商',
                ChangeChartSortMethod: '轉換航圖排序方法',
            },
            Title: '編上航圖',
            View: '檢視',
        },
        PleaseWait: '請稍候...',
        ShowingAllItems: '顯示所有航圖',
        TT: {
            FitChartToHeight: '將航圖適合於高度',
            FitChartToWidth: '將航圖適合寬度',
            ResetMovement: '重置位置',
            RotateLeft45Degrees: '向左旋轉 45 度',
            RotateRight45Degrees: '向右旋轉 45 度',
            ZoomIn: '放大',
            ZoomOut: '縮小',
        },
        ThereAreNoChartsToDisplay: '沒有航圖可顯示。',
        ThereIsNoChartToDisplay: '沒有航圖可顯示。',
        Title: '導航和航圖',
        To: '到',
    },
    'Performance': {
        Data: '數據',
        Landing: {
            AirportIcao: '機場 ICAO',
            ApproachSpeed: '降速',
            ApproachSpeedUnit: 'kts',
            AutoLand: 'Auto Land',
            Calculate: '計算',
            Clear: '清除',
            DropDownNo: 'No',
            DropDownYes: 'Yes',
            FillDataFrom: '由 FMGC 填充數據',
            FlapsConfiguration: '襟翼 (Flaps) 位置',
            Low: '低',
            MaximumManual: '最大手動',
            Medium: '中',
            OverweightProcedure: '超重程序',
            Qnh: 'QNH',
            ReverseThrust: '反向推力 (Reverse)',
            RunwayAltitude: '跑道海拔',
            RunwayAltitudeUnit: 'ft ASL',
            RunwayCondition: '跑道狀況',
            RunwayHeading: '跑道方針',
            RunwayHeadingUnit: '°',
            RunwayLda: '跑道可降距離 (LDA)',
            RunwayLdaUnitFt: 'ft',
            RunwayLdaUnitMeter: 'm',
            RunwaySlope: '跑道斜坡',
            TT: {
                YouNeedToEnterAnIcaoCodeInOrderToMakeAMetarRequest: '您需要輸入機場 ICAO 代碼才能提出 METAR 請求',
                YouNeedToLoadSimBriefDataInOrderToAutofillData: '您需要加載 SimBrief 數據才能使用自動填充功能',
            },
            Temperature: '溫度',
            Title: '降落',
            UnitFt: 'ft',
            UnitMeter: 'm',
            Weight: '重量',
            WindDirection: '風向',
            WindDirectionUnit: '°',
            WindMagnitude: '風速',
            WindMagnitudeUnit: 'kts',
        },
        SYNC: 'SYNC',
        Title: '性能',
        TopOfDescent: {
            Data: {
                Angle: '角度',
                CurrentAltitude: '現時高度',
                Distance: '距離',
                GroundSpeed: '地面速度',
                TargetAltitude: '目標高度',
                Title: '數據',
                UnitAngleDegrees: 'degrees',
                UnitFeet: 'feet',
                UnitFtMin: 'ft/min',
                UnitNM: 'NM',
                VerticalSpeed: '垂直速度',
            },
            GroundSpeed: {
                Add: '加',
                FetchingSpeedFromSimulator: '正從模擬器取速',
                GroundSpeed: '地面速度',
                ManualInput: '人手輸入',
                MinAltitude: '最低高度',
                RemoveLast: '刪除上一個',
                Sync: 'SYNC',
                Title: '地面速度',
                UnitKnots: 'knots',
                UnitKt: 'kt',
            },
            Result: {
                BeforeTarget: '在目標前',
                DesiredDescentAngle: '所需的下降角度',
                DesiredVerticalSpeed: 'Desired Vertical Speed',
                StartYourDescentAbout: '大約開始你的下降在',
                Title: '結果',
            },
            TT: {
                DesynchronizeInputWithAircraftsCurrentAltitude: "Desynchronize Input with Aircraft's Current Altitude",
                SynchronizeInputWithAircraftsCurrentAltitude: '同步輸入飛機現時高度',
            },
            Title: '下降點',
        },
    },
    'Presets': {
        AircraftStates: {
            Cancel: '取消',
            ColdDark: 'Cold & Dark',
            ConfirmationDialogMsg: 'Please confirm loading of preset.',
            CurrentProcedureStep: '現時程步',
            PleaseConfirmLoadingOfPreset: '請確認加載預設。',
            ReadyPushback: 'Ready for Pushback',
            ReadyTakeoff: 'Ready for Takeoff',
            ReadyTaxi: 'Ready for Taxi',
            SelectAPresetToLoad: '選擇預設',
            TheAircraftMustBeOnTheGroundToLoadAPreset: '飛機必須在地面上才能加載預設。',
            TheAircraftMustBeOntheGroundToLoadAPreset: '飛機必須在地面上才能加載預設。',
            Title: 'Aircraft States',
            Turnaround: 'Turnaround',
        },
        InteriorLighting: {
            AircraftNeedsToBePoweredToLoadPresets: 'Aircraft Needs to be Powered to Load Presets',
            AircraftNeedsToBePoweredToSavePresets: 'Aircraft Needs to Be Powered to Save Presets',
            LoadPreset: 'Load Preset',
            LoadingPreset: 'Loading Preset',
            NoName: 'No Name',
            PleaseConfirmSavingPreset: 'Please Confirm Saving Preset',
            SavePreset: 'Save Preset',
            SavingPreset: 'Saving Preset',
            SelectAnInteriorLightingPresetToLoadOrSave: 'Select an interior lighting preset to load or save.',
            TT: {
                AircraftMustBePowered: 'Aircraft Must be Powered',
                ClickTextToChangeThePresetsName: "Click Text to Change the Preset's Name",
                LoadThisPreset: 'Load This Preset',
                SaveTheCurrentLightingLevels: 'Save the Current Lighting Levels',
            },
            TheAircraftMustBePoweredForInteriorLightingPresets: 'The aircraft must be powered for interior lighting presets.',
            Title: 'Interior Lighting',
        },
        Title: 'Presets',
    },
    'Pushback': {
        Backward: 'Backward',
        CallTug: 'Call Tug',
        Forward: 'Forward',
        Halt: 'Halt',
        ParkingBrake: {
            Off: 'Off',
            On: 'On',
            Title: 'Parking Brake',
        },
        TugDirection: 'Tug Direction',
        TugSpeed: 'Tug Speed',
    },
    'Settings': {
        About: { Title: 'About' },
        AircraftOptionsPinPrograms: {
            AccelerationHeight: 'Acceleration Height (ft)',
            EngineOutAccelerationHeight: 'Engine-Out Acceleration Height (ft)',
            IsisBaroUnit: 'ISIS Baro Unit',
            IsisMetricAltitude: 'ISIS Metric Altitude',
            PaxSigns: 'PAX Signs',
            RmpVhfSpacing: 'RMP VHF Spacing',
            ThrustReductionHeight: 'Thrust Reduction Height (ft)',
            Title: 'Aircraft Options / Pin Programs',
            WeightUnit: 'Weight Unit',
        },
        AtsuAoc: {
            AtisAtcSource: 'ATIS/ATC Source',
            AutomaticallyImportSimBriefData: 'Automatically Import SimBrief Data',
            Enable: 'Enable',
            EnableTelex: 'Enable TELEX',
            ErrorReporting: 'Error Reporting',
            HoppieUserId: 'Hoppie User ID',
            MetarSource: 'METAR Source',
            OptionalA32nxErrorReporting: 'Optional A32NX Error Reporting',
            PleaseCheckThatYouHaveCorrectlyEnteredYourSimbBriefUsernameOrPilotId: 'Please check that you have correctly entered your SimBrief username or pilot ID.',
            SimBriefUsernamePilotId: 'SimBrief Username/Pilot ID',
            TafSource: 'TAF Source',
            Telex: 'TELEX',
            TelexEnablesFreeTextAndLiveMap: 'TELEX enables free text and live map. If enabled, aircraft position data is published for the duration of the flight. Messages are public and not moderated. USE THIS FEATURE AT YOUR OWN RISK. To learn more about TELEX and the features it enables, please go to https://docs.flybywiresim.com/telex.',
            TelexWarning: 'TELEX Warning',
            Title: 'ATSU / AOC',
            YouAreAbleToOptIntoAnonymousErrorReporting: 'You are able to opt into anonymous error reporting that will allow us to diagnose, monitor, and take care of issues at a faster rate. This feature is completely optional and we will never collect your personal data, but may allow you to more easily get support and have the issues you encounter fixed at a faster rate.',
            YourSimBriefPilotIdHasBeenValidatedAndUpdatedTo: 'Your SimBrief PilotID has been validated and updated to',
        },
        Audio: {
            Announcements: 'Announcements',
            BoardingMusic: 'Boarding Music',
            EngineInteriorVolume: 'Engine Interior Volume',
            ExteriorMasterVolume: 'Exterior Master Volume',
            PassengerAmbience: 'Passenger Ambience',
            PtuAudibleInCockpit: 'PTU Audible in Cockpit',
            Title: 'Audio',
            WindInteriorVolume: 'Wind Interior Volume',
        },
        Fast: 'Fast',
        Instant: 'Instant',
        Real: 'Real',
        Realism: {
            AdirsAlignTime: 'ADIRS Align Time',
            AutofillChecklists: 'Autofill Checklists',
            BoardingTime: 'Boarding Time',
            DatalinkTransmissionTime: 'DATALINK Transmission Time',
            DmcSelfTestTime: 'DMC Self Test Time',
            HomeCockpitMode: 'Home Cockpit Mode',
            McduFocusTimeout: 'MCDU Focus Timeout (seconds)',
            McduKeyboardInput: 'MCDU Keyboard Input',
            SeparateTillerFromRudderInputs: 'Separate Tiller from Rudder Inputs',
            Title: 'Realism',
        },
        SimOptions: {
            Active: 'Active',
            Auto: 'Auto',
            Calibrate: 'Calibrate',
            DefaultBarometerUnit: 'Default Barometer Unit',
            DynamicRegistrationDecal: 'Dynamic Registration Decal',
            EnabledMcduServerConnectionAutoDeactivatesAfter5MinutesIfNoSuccessfulConnection: 'Enable MCDU Server Connection (Auto deactivates after 5 minutes if no successful connection)',
            ExternalMcduServerPort: 'External MCDU Server Port',
            Hpa: 'hPa',
            Inactive: 'Inactive',
            LoadOnly: 'Load Only',
            None: '冇',
            Off: 'Off',
            Save: 'Save',
            SyncMsfsFlightPlan: 'Sync MSFS Flight Plan',
            ThrottleDetents: 'Throttle Detents',
            Title: 'Sim Options',
            UseCalculatedIlsSignals: 'Use Calculated ILS Signals',
            inHg: 'in Hg',
        },
        ThrottleConfig: {
            Apply: 'Apply',
            AreYouSureThatYouWantToResetYourCurrentThrottleConfigurationToTheirDefaultStates: 'Are you sure that you want to reset your current throttle configuration settings to their default states? This action is irreversible.',
            Axis: 'Axis',
            Back: 'Back',
            ConfigureEnd: 'Configure End',
            CurrentValue: 'Current Value',
            Deadband: 'Deadband',
            ErrorOverlapMsg: 'overlaps with',
            IndependentAxis: 'Independent Axis',
            LoadFromFile: 'Load from File',
            PleaseEnterAValidDeadzone: 'Please enter a valid deadzone',
            ResetToDefaults: 'Reset to Defaults',
            ReverseFull: 'Reverse Full',
            ReverseIdle: 'Reverse Idle',
            ReverserOnAxis: 'Reverser On Axis',
            SaveAndApply: 'Save and Apply',
            SetFromThrottle: 'Set from Throttle',
            ThrottleConfigurationReset: 'Throttle Configuration Reset',
        },
        Title: 'Settings',
        Unrealistic: 'Unrealistic',
        flyPad: {
            AutoBrightness: 'Auto Brightness',
            AutomaticallyShowOnscreenKeyboard: 'Automatically Show Onscreen Keyboard',
            Blue: 'Blue',
            Brightness: 'Brightness',
            Dark: 'Dark',
            Language: 'Language',
            Light: 'Light',
            Local: 'Local',
            LocalTimeFormat: 'Local Time Format',
            OnscreenKeyboardLayout: 'Onscreen Keyboard Layout',
            ShowColoredRawMetar: 'Show Colored Raw METAR',
            ShowStatusBarFlightProgressIndicator: 'Show Status Bar Flight Progress Indicator',
            Theme: 'Theme',
            TimeDisplayed: 'Time Displayed',
            Title: 'flyPad',
            TwelveHours: '12h',
            TwentyFourHours: '24h',
            Utc: 'UTC',
            UtcAndLocal: 'UTC and Local',
        },
    },
    'Settings.flyPad.BatteryLifeEnabled': 'Battery Life Simulated',
    'StatusBar': {
        Apr: 'Apr',
        Aug: 'Aug',
        Dec: 'Dec',
        Feb: 'Feb',
        Fri: 'Fri',
        Jan: 'Jan',
        Jun: 'Jun',
        Mar: 'Mar',
        May: 'May',
        Mon: 'Mon',
        Nov: 'Nov',
        Oct: 'Oct',
        Sat: 'Sat',
        Sep: 'Sep',
        Sun: 'Sun',
        TT: {
            ConnectedToLocalApi: 'Connected to Local API',
            DisconnectedFromLocalApi: 'Disconnected from Local API',
            TurnOffOrShutdownEfb: 'Turn off or Shutdown EFB',
        },
        Thu: 'Thu',
        Tue: 'Tue',
        Wed: 'Wed',
    },
};
