#include "../../fbw-a32nx/src/wasm/fbw_a320/src/EngineData.h"
#include "../../fbw-a32nx/src/wasm/fbw_a320/src/AdditionalData.h"
#include "../../fbw-a32nx/src/wasm/fbw_a320/src/model/AutopilotLaws_types.h"
#include "../../fbw-a32nx/src/wasm/fbw_a320/src/model/AutopilotStateMachine_types.h"
#include "../../fbw-a32nx/src/wasm/fbw_a320/src/model/Autothrust_types.h"
