#ifndef A380PrimComputerFctl_h_
#define A380PrimComputerFctl_h_
#include "rtwtypes.h"
#include "A380PrimComputerFctl_types.h"
#include "A380LateralNormalLaw.h"
#include "A380LateralDirectLaw.h"
#include "A380PitchNormalLaw.h"
#include "A380PitchAlternateLaw.h"
#include "A380PitchDirectLaw.h"

extern const real_T A380PrimComputerFctl_RGND;
class A380PrimComputerFctl final
{
 public:
  struct rtDW_RateLimiter_A380PrimComputerFctl_T {
    real_T pY;
    boolean_T pY_not_empty;
  };

  struct rtDW_RateLimiter_A380PrimComputerFctl_p_T {
    real_T pY;
    boolean_T pY_not_empty;
  };

  struct rtDW_RateLimiter_A380PrimComputerFctl_m_T {
    real_T pY;
    boolean_T pY_not_empty;
  };

  struct rtDW_RateLimiter_A380PrimComputerFctl_c_T {
    real_T pY;
    boolean_T pY_not_empty;
  };

  struct rtDW_TransportDelay_A380PrimComputerFctl_T {
    real_T stack[70];
    real_T pointer;
    real_T timeSinceLastSample;
  };

  struct rtDW_LagFilter_A380PrimComputerFctl_T {
    real_T pY;
    real_T pU;
    boolean_T pY_not_empty;
    boolean_T pU_not_empty;
  };

  struct rtDW_MATLABFunction_A380PrimComputerFctl_o_T {
    boolean_T previousInput;
    boolean_T previousInput_not_empty;
  };

  struct rtDW_MATLABFunction_A380PrimComputerFctl_a_T {
    real_T timeSinceCondition;
    boolean_T output;
  };

  struct BlockIO_A380PrimComputerFctl_T {
    prim_outputs BusAssignment_nw;
    prim_outputs BusAssignment_m;
  };

  struct D_Work_A380PrimComputerFctl_T {
    real_T Delay_DSTATE;
    real_T Delay_DSTATE_m;
    real_T eventTime;
    real_T resetEventTime;
    real_T eventTime_f;
    boolean_T Delay_DSTATE_c;
    boolean_T Delay1_DSTATE;
    boolean_T Delay1_DSTATE_b;
    boolean_T Delay2_DSTATE;
    boolean_T Delay3_DSTATE;
    boolean_T Delay_DSTATE_e;
    uint8_T is_active_c28_A380PrimComputerFctl;
    uint8_T is_c28_A380PrimComputerFctl;
    boolean_T Memory_PreviousInput;
    boolean_T Memory_PreviousInput_a;
    boolean_T Memory_PreviousInput_d;
    boolean_T Memory_PreviousInput_j;
    boolean_T icLoad;
    boolean_T pLeftStickDisabled;
    boolean_T pRightStickDisabled;
    boolean_T sProtActive;
    boolean_T eventTime_not_empty;
    boolean_T resetEventTime_not_empty;
    boolean_T sProtActive_g;
    boolean_T eventTime_not_empty_m;
    boolean_T abnormalConditionWasActive;
    boolean_T Runtime_MODE;
    rtDW_MATLABFunction_A380PrimComputerFctl_o_T sf_MATLABFunction_dmh;
    rtDW_MATLABFunction_A380PrimComputerFctl_o_T sf_MATLABFunction_ky;
    rtDW_RateLimiter_A380PrimComputerFctl_m_T sf_RateLimiter_nd;
    rtDW_MATLABFunction_A380PrimComputerFctl_a_T sf_MATLABFunction_al4;
    rtDW_MATLABFunction_A380PrimComputerFctl_o_T sf_MATLABFunction_nu;
    rtDW_MATLABFunction_A380PrimComputerFctl_o_T sf_MATLABFunction_g4;
    rtDW_MATLABFunction_A380PrimComputerFctl_a_T sf_MATLABFunction_j2;
    rtDW_MATLABFunction_A380PrimComputerFctl_a_T sf_MATLABFunction_g2;
    rtDW_RateLimiter_A380PrimComputerFctl_c_T sf_RateLimiter_lf;
    rtDW_RateLimiter_A380PrimComputerFctl_c_T sf_RateLimiter_b4;
    rtDW_RateLimiter_A380PrimComputerFctl_c_T sf_RateLimiter_mr;
    rtDW_RateLimiter_A380PrimComputerFctl_c_T sf_RateLimiter_ne;
    rtDW_MATLABFunction_A380PrimComputerFctl_a_T sf_MATLABFunction_nb;
    rtDW_MATLABFunction_A380PrimComputerFctl_o_T sf_MATLABFunction_ny;
    rtDW_MATLABFunction_A380PrimComputerFctl_o_T sf_MATLABFunction_gc;
    rtDW_MATLABFunction_A380PrimComputerFctl_o_T sf_MATLABFunction_m1;
    rtDW_MATLABFunction_A380PrimComputerFctl_o_T sf_MATLABFunction_ff;
    rtDW_RateLimiter_A380PrimComputerFctl_p_T sf_RateLimiter_j;
    rtDW_RateLimiter_A380PrimComputerFctl_p_T sf_RateLimiter_b;
    rtDW_RateLimiter_A380PrimComputerFctl_p_T sf_RateLimiter_c4;
    rtDW_RateLimiter_A380PrimComputerFctl_p_T sf_RateLimiter_mp;
    rtDW_LagFilter_A380PrimComputerFctl_T sf_LagFilter_k;
    rtDW_LagFilter_A380PrimComputerFctl_T sf_LagFilter;
    rtDW_TransportDelay_A380PrimComputerFctl_T sf_TransportDelay_c;
    rtDW_RateLimiter_A380PrimComputerFctl_T sf_RateLimiter_dg;
    rtDW_TransportDelay_A380PrimComputerFctl_T sf_TransportDelay;
    rtDW_RateLimiter_A380PrimComputerFctl_T sf_RateLimiter_it;
    rtDW_RateLimiter_A380PrimComputerFctl_p_T sf_RateLimiter_k;
    rtDW_RateLimiter_A380PrimComputerFctl_p_T sf_RateLimiter_c;
    rtDW_RateLimiter_A380PrimComputerFctl_p_T sf_RateLimiter_pw;
    rtDW_RateLimiter_A380PrimComputerFctl_p_T sf_RateLimiter_lv;
    rtDW_RateLimiter_A380PrimComputerFctl_p_T sf_RateLimiter_po;
    rtDW_RateLimiter_A380PrimComputerFctl_p_T sf_RateLimiter_ng;
    rtDW_RateLimiter_A380PrimComputerFctl_p_T sf_RateLimiter_ib;
    rtDW_RateLimiter_A380PrimComputerFctl_c_T sf_RateLimiter_a;
    rtDW_RateLimiter_A380PrimComputerFctl_c_T sf_RateLimiter_oa;
    rtDW_RateLimiter_A380PrimComputerFctl_c_T sf_RateLimiter_l3;
    rtDW_RateLimiter_A380PrimComputerFctl_m_T sf_RateLimiter_d;
    rtDW_RateLimiter_A380PrimComputerFctl_p_T sf_RateLimiter_la;
    rtDW_RateLimiter_A380PrimComputerFctl_p_T sf_RateLimiter_n;
    rtDW_RateLimiter_A380PrimComputerFctl_p_T sf_RateLimiter_oj;
    rtDW_RateLimiter_A380PrimComputerFctl_p_T sf_RateLimiter_iq;
    rtDW_RateLimiter_A380PrimComputerFctl_p_T sf_RateLimiter_l;
    rtDW_RateLimiter_A380PrimComputerFctl_p_T sf_RateLimiter_p;
    rtDW_RateLimiter_A380PrimComputerFctl_p_T sf_RateLimiter_hj;
    rtDW_RateLimiter_A380PrimComputerFctl_p_T sf_RateLimiter_ob;
    rtDW_RateLimiter_A380PrimComputerFctl_p_T sf_RateLimiter_f1;
    rtDW_RateLimiter_A380PrimComputerFctl_p_T sf_RateLimiter_iv;
    rtDW_RateLimiter_A380PrimComputerFctl_p_T sf_RateLimiter_mt;
    rtDW_RateLimiter_A380PrimComputerFctl_p_T sf_RateLimiter_fk;
    rtDW_RateLimiter_A380PrimComputerFctl_p_T sf_RateLimiter_gk;
    rtDW_RateLimiter_A380PrimComputerFctl_p_T sf_RateLimiter_o;
    rtDW_RateLimiter_A380PrimComputerFctl_p_T sf_RateLimiter_f;
    rtDW_RateLimiter_A380PrimComputerFctl_p_T sf_RateLimiter_iu;
    rtDW_RateLimiter_A380PrimComputerFctl_p_T sf_RateLimiter_h;
    rtDW_RateLimiter_A380PrimComputerFctl_T sf_RateLimiter_i;
    rtDW_RateLimiter_A380PrimComputerFctl_T sf_RateLimiter_g;
    rtDW_RateLimiter_A380PrimComputerFctl_T sf_RateLimiter_m;
    rtDW_RateLimiter_A380PrimComputerFctl_T sf_RateLimiter;
  };

  struct ExternalInputs_A380PrimComputerFctl_T {
    prim_outputs in;
  };

  struct ExternalOutputs_A380PrimComputerFctl_T {
    prim_outputs out;
  };

  struct Parameters_A380PrimComputerFctl_T {
    real_T LagFilter1_C1;
    real_T LagFilter_C1;
    real_T DiscreteDerivativeVariableTs_Gain;
    real_T DiscreteTimeIntegratorVariableTsLimit_Gain;
    real_T RateLimiterGenericVariableTs24_InitialCondition;
    real_T RateLimiterVariableTs1_InitialCondition;
    real_T RateLimiterVariableTs2_InitialCondition;
    real_T RateLimiterVariableTs3_InitialCondition;
    real_T RateLimiterVariableTs4_InitialCondition;
    real_T RateLimiterVariableTs6_InitialCondition;
    real_T RateLimiterGenericVariableTs25_InitialCondition;
    real_T RateLimiterVariableTs5_InitialCondition;
    real_T DiscreteDerivativeVariableTs_InitialCondition;
    real_T BitfromLabel2_bit;
    real_T BitfromLabel1_bit;
    real_T BitfromLabel1_bit_n;
    real_T BitfromLabel3_bit;
    real_T BitfromLabel2_bit_l;
    real_T BitfromLabel1_bit_b;
    real_T BitfromLabel1_bit_k;
    real_T BitfromLabel2_bit_e;
    real_T BitfromLabel3_bit_c;
    real_T BitfromLabel4_bit;
    real_T BitfromLabel6_bit;
    real_T BitfromLabel9_bit;
    real_T BitfromLabel10_bit;
    real_T BitfromLabel5_bit;
    real_T BitfromLabel7_bit;
    real_T BitfromLabel8_bit;
    real_T BitfromLabel_bit;
    real_T BitfromLabel1_bit_c;
    real_T BitfromLabel2_bit_p;
    real_T BitfromLabel3_bit_n;
    real_T BitfromLabel4_bit_j;
    real_T BitfromLabel5_bit_i;
    real_T BitfromLabel6_bit_j;
    real_T BitfromLabel7_bit_n;
    real_T BitfromLabel8_bit_n;
    real_T BitfromLabel9_bit_b;
    real_T BitfromLabel10_bit_h;
    real_T BitfromLabel11_bit;
    real_T BitfromLabel14_bit;
    real_T BitfromLabel15_bit;
    real_T BitfromLabel16_bit;
    real_T BitfromLabel17_bit;
    real_T BitfromLabel1_bit_g;
    real_T BitfromLabel2_bit_pc;
    real_T BitfromLabel1_bit_i;
    real_T BitfromLabel2_bit_n;
    real_T BitfromLabel1_bit_nd;
    real_T BitfromLabel2_bit_d;
    real_T BitfromLabel8_bit_l;
    real_T BitfromLabel9_bit_g;
    real_T BitfromLabel10_bit_j;
    real_T BitfromLabel11_bit_j;
    real_T BitfromLabel14_bit_p;
    real_T BitfromLabel15_bit_i;
    real_T BitfromLabel12_bit;
    real_T BitfromLabel13_bit;
    real_T BitfromLabel1_bit_l;
    real_T BitfromLabel2_bit_f;
    real_T BitfromLabel1_bit_p;
    real_T BitfromLabel2_bit_b;
    real_T BitfromLabel16_bit_b;
    real_T BitfromLabel17_bit_i;
    real_T BitfromLabel18_bit;
    real_T BitfromLabel19_bit;
    real_T BitfromLabel20_bit;
    real_T BitfromLabel21_bit;
    real_T BitfromLabel22_bit;
    real_T BitfromLabel23_bit;
    real_T BitfromLabel1_bit_lr;
    real_T BitfromLabel2_bit_g;
    real_T BitfromLabel3_bit_k;
    real_T BitfromLabel4_bit_n;
    real_T BitfromLabel5_bit_e;
    real_T BitfromLabel6_bit_b;
    real_T BitfromLabel7_bit_p;
    real_T BitfromLabel8_bit_d;
    real_T BitfromLabel9_bit_e;
    real_T BitfromLabel11_bit_n;
    real_T BitfromLabel38_bit;
    real_T BitfromLabel39_bit;
    real_T BitfromLabel32_bit;
    real_T BitfromLabel33_bit;
    real_T BitfromLabel36_bit;
    real_T BitfromLabel37_bit;
    real_T BitfromLabel3_bit_m;
    real_T BitfromLabel4_bit_b;
    real_T BitfromLabel1_bit_pt;
    real_T BitfromLabel2_bit_h;
    real_T BitfromLabel5_bit_d;
    real_T BitfromLabel6_bit_p;
    real_T BitfromLabel7_bit_g;
    real_T BitfromLabel8_bit_i;
    real_T BitfromLabel_bit_c;
    real_T BitfromLabel1_bit_o;
    real_T BitfromLabel2_bit_hn;
    real_T BitfromLabel6_bit_h;
    real_T BitfromLabel3_bit_b;
    real_T BitfromLabel4_bit_g;
    real_T BitfromLabel5_bit_j;
    real_T BitfromLabel7_bit_o;
    real_T BitfromLabel_bit_l;
    real_T BitfromLabel1_bit_cm;
    real_T BitfromLabel_bit_e;
    real_T BitfromLabel1_bit_d;
    real_T BitfromLabel2_bit_pt;
    real_T BitfromLabel3_bit_g;
    real_T BitfromLabel4_bit_p;
    real_T BitfromLabel_bit_g;
    real_T BitfromLabel6_bit_l;
    real_T BitfromLabel5_bit_a;
    real_T BitfromLabel_bit_ci;
    real_T BitfromLabel_bit_j;
    real_T BitfromLabel1_bit_h;
    real_T BitfromLabel2_bit_he;
    real_T BitfromLabel3_bit_l;
    real_T BitfromLabel4_bit_nn;
    real_T BitfromLabel5_bit_f;
    real_T BitfromLabel_bit_d;
    real_T BitfromLabel1_bit_lh;
    real_T BitfromLabel2_bit_c;
    real_T BitfromLabel3_bit_i;
    real_T BitfromLabel4_bit_o;
    real_T BitfromLabel5_bit_ft;
    real_T BitfromLabel_bit_h;
    real_T CompareToConstant_const;
    real_T CompareToConstant3_const;
    real_T CompareToConstant4_const;
    real_T CompareToConstant1_const;
    real_T CompareToConstant2_const;
    real_T CompareToConstant_const_n;
    real_T CompareToConstant13_const;
    real_T CompareToConstant9_const;
    real_T CompareToConstant10_const;
    real_T CompareToConstant14_const;
    real_T CompareToConstant_const_m;
    real_T CompareToConstant26_const;
    real_T CompareToConstant11_const;
    real_T CompareToConstant27_const;
    real_T CompareToConstant5_const;
    real_T CompareToConstant6_const;
    real_T CompareToConstant12_const;
    real_T CompareToConstant15_const;
    real_T CompareToConstant29_const;
    real_T CompareToConstant16_const;
    real_T CompareToConstant17_const;
    real_T CompareToConstant18_const;
    real_T CompareToConstant7_const;
    real_T CompareToConstant8_const;
    real_T CompareToConstant3_const_n;
    real_T CompareToConstant4_const_k;
    real_T CompareToConstant1_const_a;
    real_T CompareToConstant2_const_k;
    real_T CompareToConstant_const_c;
    real_T CompareToConstant1_const_p;
    real_T CompareToConstant_const_e;
    real_T CompareToConstant_const_b;
    real_T CompareToConstant2_const_h;
    real_T CompareToConstant3_const_m;
    real_T CompareToConstant4_const_e;
    real_T CompareToConstant5_const_p;
    real_T CompareToConstant1_const_b;
    real_T CompareToConstant2_const_d;
    real_T CompareToConstant_const_d;
    real_T CompareToConstant1_const_c;
    real_T CompareToConstant1_const_p3;
    real_T RateLimiterGenericVariableTs_lo;
    real_T RateLimiterGenericVariableTs1_lo;
    real_T RateLimiterGenericVariableTs2_lo;
    real_T RateLimiterGenericVariableTs3_lo;
    real_T RateLimiterGenericVariableTs24_lo;
    real_T RateLimiterVariableTs1_lo;
    real_T RateLimiterVariableTs2_lo;
    real_T RateLimiterVariableTs3_lo;
    real_T RateLimiterGenericVariableTs4_lo;
    real_T RateLimiterGenericVariableTs_lo_d;
    real_T RateLimiterGenericVariableTs1_lo_h;
    real_T RateLimiterGenericVariableTs2_lo_b;
    real_T RateLimiterGenericVariableTs3_lo_b;
    real_T RateLimiterGenericVariableTs5_lo;
    real_T RateLimiterVariableTs4_lo;
    real_T RateLimiterVariableTs6_lo;
    real_T RateLimiterGenericVariableTs28_lo;
    real_T RateLimiterGenericVariableTs25_lo;
    real_T RateLimiterGenericVariableTs8_lo;
    real_T RateLimiterGenericVariableTs9_lo;
    real_T RateLimiterGenericVariableTs10_lo;
    real_T RateLimiterGenericVariableTs11_lo;
    real_T RateLimiterGenericVariableTs27_lo;
    real_T RateLimiterGenericVariableTs14_lo;
    real_T RateLimiterGenericVariableTs15_lo;
    real_T RateLimiterGenericVariableTs12_lo;
    real_T RateLimiterGenericVariableTs13_lo;
    real_T RateLimiterGenericVariableTs18_lo;
    real_T RateLimiterGenericVariableTs19_lo;
    real_T RateLimiterGenericVariableTs26_lo;
    real_T RateLimiterGenericVariableTs16_lo;
    real_T RateLimiterGenericVariableTs17_lo;
    real_T RateLimiterGenericVariableTs22_lo;
    real_T RateLimiterGenericVariableTs23_lo;
    real_T RateLimiterGenericVariableTs20_lo;
    real_T RateLimiterGenericVariableTs21_lo;
    real_T RateLimiterVariableTs5_lo;
    real_T RateLimiterGenericVariableTs6_lo;
    real_T RateLimiterGenericVariableTs7_lo;
    real_T RateLimiterGenericVariableTs_lo_c;
    real_T RateLimiterGenericVariableTs1_lo_a;
    real_T RateLimiterGenericVariableTs2_lo_m;
    real_T RateLimiterGenericVariableTs3_lo_p;
    real_T ConfirmNode_timeDelay;
    real_T ConfirmNode1_timeDelay;
    real_T ConfirmNode_timeDelay_a;
    real_T ConfirmNode_timeDelay_g;
    real_T RateLimiterGenericVariableTs_up;
    real_T RateLimiterGenericVariableTs1_up;
    real_T RateLimiterGenericVariableTs2_up;
    real_T RateLimiterGenericVariableTs3_up;
    real_T RateLimiterGenericVariableTs24_up;
    real_T RateLimiterVariableTs1_up;
    real_T RateLimiterVariableTs2_up;
    real_T RateLimiterVariableTs3_up;
    real_T RateLimiterGenericVariableTs4_up;
    real_T RateLimiterGenericVariableTs_up_p;
    real_T RateLimiterGenericVariableTs1_up_o;
    real_T RateLimiterGenericVariableTs2_up_m;
    real_T RateLimiterGenericVariableTs3_up_b;
    real_T RateLimiterGenericVariableTs5_up;
    real_T RateLimiterVariableTs4_up;
    real_T RateLimiterVariableTs6_up;
    real_T RateLimiterGenericVariableTs28_up;
    real_T RateLimiterGenericVariableTs25_up;
    real_T RateLimiterGenericVariableTs8_up;
    real_T RateLimiterGenericVariableTs9_up;
    real_T RateLimiterGenericVariableTs10_up;
    real_T RateLimiterGenericVariableTs11_up;
    real_T RateLimiterGenericVariableTs27_up;
    real_T RateLimiterGenericVariableTs14_up;
    real_T RateLimiterGenericVariableTs15_up;
    real_T RateLimiterGenericVariableTs12_up;
    real_T RateLimiterGenericVariableTs13_up;
    real_T RateLimiterGenericVariableTs18_up;
    real_T RateLimiterGenericVariableTs19_up;
    real_T RateLimiterGenericVariableTs26_up;
    real_T RateLimiterGenericVariableTs16_up;
    real_T RateLimiterGenericVariableTs17_up;
    real_T RateLimiterGenericVariableTs22_up;
    real_T RateLimiterGenericVariableTs23_up;
    real_T RateLimiterGenericVariableTs20_up;
    real_T RateLimiterGenericVariableTs21_up;
    real_T RateLimiterVariableTs5_up;
    real_T RateLimiterGenericVariableTs6_up;
    real_T RateLimiterGenericVariableTs7_up;
    real_T RateLimiterGenericVariableTs_up_b;
    real_T RateLimiterGenericVariableTs1_up_g;
    real_T RateLimiterGenericVariableTs2_up_d;
    real_T RateLimiterGenericVariableTs3_up_m;
    SignStatusMatrix EnumeratedConstant1_Value;
    SignStatusMatrix EnumeratedConstant_Value;
    SignStatusMatrix EnumeratedConstant2_Value;
    SignStatusMatrix EnumeratedConstant2_Value_l;
    SignStatusMatrix EnumeratedConstant1_Value_j;
    SignStatusMatrix EnumeratedConstant_Value_e;
    SignStatusMatrix EnumeratedConstant_Value_i;
    SignStatusMatrix EnumeratedConstant1_Value_g;
    a380_lateral_efcs_law EnumeratedConstant_Value_g;
    a380_pitch_efcs_law EnumeratedConstant_Value_l;
    a380_pitch_efcs_law EnumeratedConstant_Value_j;
    boolean_T SRFlipFlop_initial_condition;
    boolean_T SRFlipFlop1_initial_condition;
    boolean_T SRFlipFlop1_initial_condition_i;
    boolean_T SRFlipFlop_initial_condition_i;
    boolean_T ConfirmNode_isRisingEdge;
    boolean_T PulseNode_isRisingEdge;
    boolean_T PulseNode1_isRisingEdge;
    boolean_T ConfirmNode1_isRisingEdge;
    boolean_T ConfirmNode_isRisingEdge_j;
    boolean_T ConfirmNode_isRisingEdge_c;
    boolean_T PulseNode7_isRisingEdge;
    boolean_T PulseNode6_isRisingEdge;
    boolean_T PulseNode5_isRisingEdge;
    boolean_T PulseNode4_isRisingEdge;
    boolean_T PulseNode1_isRisingEdge_n;
    boolean_T PulseNode2_isRisingEdge;
    uint8_T CompareToConstant19_const;
    prim_outputs out_Y0;
    real_T Gain1_Gain;
    real_T Bias_Bias;
    real_T Saturation7_UpperSat;
    real_T Saturation7_LowerSat;
    real_T Gain6_Gain;
    real_T Constant5_Value;
    real_T Constant6_Value;
    real_T Constant9_Value;
    real_T Constant8_Value;
    real_T Constant2_Value;
    real_T Constant1_Value;
    real_T Constant4_Value;
    real_T Constant3_Value;
    real_T Constant_Value;
    real_T Gain1_Gain_c;
    real_T Gain_Gain;
    real_T Gain7_Gain;
    real_T Constant2_Value_g;
    real_T Constant3_Value_m;
    real_T Constant1_Value_b;
    real_T uDLookupTable_tableData[5];
    real_T uDLookupTable_bp01Data[5];
    real_T Gain_Gain_g;
    real_T Saturation_UpperSat;
    real_T Saturation_LowerSat;
    real_T Constant10_Value;
    real_T Constant11_Value;
    real_T Constant1_Value_n;
    real_T Constant2_Value_k;
    real_T Constant3_Value_g;
    real_T Constant4_Value_i;
    real_T Constant5_Value_n;
    real_T Constant6_Value_f;
    real_T Constant7_Value;
    real_T Constant8_Value_p;
    real_T Constant9_Value_n;
    real_T Constant_Value_b;
    real_T Constant_Value_p;
    real_T Saturation_UpperSat_d;
    real_T Saturation_LowerSat_h;
    real_T Constant1_Value_p;
    real_T Saturation1_UpperSat;
    real_T Saturation1_LowerSat;
    real_T alphamax_tableData[24];
    real_T alphamax_bp01Data[4];
    real_T alphamax_bp02Data[6];
    real_T alphaprotection_tableData[24];
    real_T alphaprotection_bp01Data[4];
    real_T alphaprotection_bp02Data[6];
    real_T alpha0_tableData[6];
    real_T alpha0_bp01Data[6];
    real_T alphastallwarnmax_tableData[24];
    real_T alphastallwarnmax_bp01Data[4];
    real_T alphastallwarnmax_bp02Data[6];
    real_T Constant5_Value_k;
    real_T Constant6_Value_b;
    real_T Constant7_Value_g;
    real_T Constant8_Value_h;
    real_T Gain1_Gain_d;
    real_T uDLookupTable1_tableData[4];
    real_T uDLookupTable1_bp01Data[4];
    real_T uDLookupTable2_tableData[4];
    real_T uDLookupTable2_bp01Data[4];
    real_T uDLookupTable_tableData_n[4];
    real_T uDLookupTable_bp01Data_m[4];
    real_T Constant_Value_i;
    real_T Gain8_Gain;
    real_T Saturation3_UpperSat;
    real_T Saturation3_LowerSat;
    real_T Saturation_UpperSat_f;
    real_T Saturation_LowerSat_hn;
    real_T Saturation2_UpperSat;
    real_T Saturation2_LowerSat;
    real_T Gain4_Gain;
    real_T Gain_Gain_h;
    real_T Saturation2_UpperSat_j;
    real_T Saturation2_LowerSat_i;
    real_T Saturation1_UpperSat_n;
    real_T Saturation1_LowerSat_c;
    real_T Gain3_Gain;
    real_T Saturation3_UpperSat_b;
    real_T Saturation3_LowerSat_h;
    real_T Saturation4_UpperSat;
    real_T Saturation4_LowerSat;
    real_T Gain5_Gain;
    real_T Gain2_Gain;
    real_T uDLookupTable1_tableData_d[9];
    real_T uDLookupTable1_bp01Data_n[9];
    real_T Gain9_Gain;
    real_T uDLookupTable2_tableData_o[9];
    real_T uDLookupTable2_bp01Data_o[9];
    real_T Saturation6_UpperSat;
    real_T Saturation6_LowerSat;
    real_T Saturation5_UpperSat;
    real_T Saturation5_LowerSat;
    real_T Gain_Gain_p;
    real_T Constant_Value_g;
    real_T Gain_Gain_a;
    real_T Constant_Value_j;
    real_T Saturation3_UpperSat_o;
    real_T Saturation3_LowerSat_f;
    real_T Saturation2_UpperSat_l;
    real_T Saturation2_LowerSat_l;
    real_T Saturation_UpperSat_g;
    real_T Saturation_LowerSat_c;
    real_T Saturation1_UpperSat_m;
    real_T Saturation1_LowerSat_b;
    real_T Constant2_Value_o;
    real_T Switch7_Threshold;
    real32_T Constant10_Value_b;
    real32_T Constant9_Value_o;
    real32_T Constant8_Value_j;
    real32_T Constant7_Value_k;
    real32_T Constant6_Value_h;
    real32_T Constant5_Value_a;
    real32_T Constant4_Value_b;
    real32_T Constant3_Value_k;
    real32_T Constant2_Value_kh;
    real32_T Constant1_Value_a;
    real32_T Constant14_Value;
    real32_T Constant15_Value;
    real32_T Constant24_Value;
    real32_T Constant23_Value;
    real32_T Constant26_Value;
    real32_T Constant25_Value;
    real32_T Constant28_Value;
    real32_T Constant27_Value;
    real32_T Constant30_Value;
    real32_T Constant29_Value;
    real32_T Constant32_Value;
    real32_T Constant13_Value;
    real32_T Constant31_Value;
    real32_T Constant33_Value;
    real32_T Constant34_Value;
    real32_T Constant35_Value;
    real32_T Constant12_Value;
    real32_T Constant11_Value_a;
    real32_T Constant20_Value;
    real32_T Gain_Gain_n;
    real32_T Gain1_Gain_i;
    real32_T Gain2_Gain_g;
    real32_T Gain3_Gain_a;
    real32_T Gain4_Gain_h;
    uint32_T alphamax_maxIndex[2];
    uint32_T alphaprotection_maxIndex[2];
    uint32_T alphastallwarnmax_maxIndex[2];
    boolean_T Constant_Value_a;
    boolean_T Delay_InitialCondition;
    boolean_T Delay1_InitialCondition;
    boolean_T reset_Value;
    boolean_T reset_Value_j;
    boolean_T reset_Value_jz;
    boolean_T reset_Value_g;
    boolean_T Constant_Value_h;
    boolean_T Logic_table[16];
    boolean_T reset_Value_f;
    boolean_T Logic_table_h[16];
    boolean_T Delay1_InitialCondition_n;
    boolean_T Delay2_InitialCondition;
    boolean_T Delay3_InitialCondition;
    boolean_T Delay_InitialCondition_o;
    boolean_T Logic_table_j[16];
    boolean_T Logic_table_n[16];
    boolean_T reset_Value_p;
    boolean_T reset_Value_m;
    boolean_T Constant7_Value_o;
    boolean_T reset_Value_n;
    boolean_T reset_Value_nc;
    boolean_T Constant1_Value_f;
    boolean_T Constant_Value_ba;
    boolean_T Constant16_Value;
    boolean_T Constant17_Value;
    boolean_T Constant18_Value;
    boolean_T Constant19_Value;
    boolean_T Constant21_Value;
    boolean_T Constant22_Value;
    boolean_T Constant_Value_ho;
    boolean_T Constant9_Value_f;
    boolean_T Constant8_Value_h3;
    boolean_T Constant4_Value_o;
    boolean_T Constant5_Value_c;
    boolean_T Constant7_Value_p;
    boolean_T Constant1_Value_h;
    boolean_T Constant6_Value_o;
    boolean_T Constant2_Value_d;
  };

  A380PrimComputerFctl(A380PrimComputerFctl const&) = delete;
  A380PrimComputerFctl& operator= (A380PrimComputerFctl const&) & = delete;
  A380PrimComputerFctl(A380PrimComputerFctl &&) = delete;
  A380PrimComputerFctl& operator= (A380PrimComputerFctl &&) = delete;
  ExternalInputs_A380PrimComputerFctl_T A380PrimComputerFctl_U;
  ExternalOutputs_A380PrimComputerFctl_T A380PrimComputerFctl_Y;
  void initialize();
  void step();
  static void terminate();
  A380PrimComputerFctl();
  ~A380PrimComputerFctl();
 private:
  BlockIO_A380PrimComputerFctl_T A380PrimComputerFctl_B;
  D_Work_A380PrimComputerFctl_T A380PrimComputerFctl_DWork;
  static Parameters_A380PrimComputerFctl_T A380PrimComputerFctl_P;
  static void A380PrimComputerFctl_RateLimiter_Reset(rtDW_RateLimiter_A380PrimComputerFctl_T *localDW);
  static void A380PrimComputerFctl_RateLimiter(real_T rtu_u, real_T rtu_up, real_T rtu_lo, real_T rtu_Ts, real_T
    rtu_init, real_T *rty_Y, rtDW_RateLimiter_A380PrimComputerFctl_T *localDW);
  static void A380PrimComputerFctl_RateLimiter_a_Reset(rtDW_RateLimiter_A380PrimComputerFctl_p_T *localDW);
  static void A380PrimComputerFctl_RateLimiter_h(real_T rtu_u, real_T rtu_up, real_T rtu_lo, real_T rtu_Ts, real_T
    rtu_init, boolean_T rtu_reset, real_T *rty_Y, rtDW_RateLimiter_A380PrimComputerFctl_p_T *localDW);
  static void A380PrimComputerFctl_RateLimiter_b_Reset(rtDW_RateLimiter_A380PrimComputerFctl_m_T *localDW);
  static void A380PrimComputerFctl_RateLimiter_d(real_T rtu_u, real_T rtu_up, real_T rtu_lo, real_T rtu_Ts, real_T
    rtu_init, boolean_T rtu_reset, real_T *rty_Y, rtDW_RateLimiter_A380PrimComputerFctl_m_T *localDW);
  static void A380PrimComputerFctl_RateLimiter_f_Reset(rtDW_RateLimiter_A380PrimComputerFctl_c_T *localDW);
  static void A380PrimComputerFctl_RateLimiter_l(real_T rtu_u, real_T rtu_up, real_T rtu_lo, real_T rtu_Ts, boolean_T
    rtu_reset, real_T *rty_Y, rtDW_RateLimiter_A380PrimComputerFctl_c_T *localDW);
  static void A380PrimComputerFctl_TransportDelay_Init(rtDW_TransportDelay_A380PrimComputerFctl_T *localDW);
  static void A380PrimComputerFctl_TransportDelay_Reset(rtDW_TransportDelay_A380PrimComputerFctl_T *localDW);
  static void A380PrimComputerFctl_TransportDelay(real_T rtu_u, real_T rtu_dt, boolean_T rtu_reset, real_T *rty_y,
    rtDW_TransportDelay_A380PrimComputerFctl_T *localDW);
  static void A380PrimComputerFctl_Spoiler345Computation(real_T rtu_xiSplr, real_T rtu_speedBrakeDeflection, real_T
    *rty_leftCommand, real_T *rty_rightCommand);
  static void A380PrimComputerFctl_MATLABFunction(const base_arinc_429 *rtu_u, boolean_T *rty_y);
  static void A380PrimComputerFctl_MATLABFunction_p(const base_arinc_429 *rtu_u, real_T rtu_bit, uint32_T *rty_y);
  static void A380PrimComputerFctl_LagFilter_Reset(rtDW_LagFilter_A380PrimComputerFctl_T *localDW);
  static void A380PrimComputerFctl_LagFilter(real_T rtu_U, real_T rtu_C1, real_T rtu_dt, real_T *rty_Y,
    rtDW_LagFilter_A380PrimComputerFctl_T *localDW);
  static void A380PrimComputerFctl_MATLABFunction_m(boolean_T rtu_bit1, boolean_T rtu_bit2, boolean_T rtu_bit3,
    boolean_T rtu_bit4, boolean_T rtu_bit5, boolean_T rtu_bit6, real_T *rty_handleIndex);
  static void A380PrimComputerFctl_MATLABFunction_b_Reset(rtDW_MATLABFunction_A380PrimComputerFctl_o_T *localDW);
  static void A380PrimComputerFctl_MATLABFunction_f(boolean_T rtu_u, boolean_T rtu_isRisingEdge, boolean_T *rty_y,
    rtDW_MATLABFunction_A380PrimComputerFctl_o_T *localDW);
  static void A380PrimComputerFctl_MATLABFunction_g(boolean_T rtu_bit1, boolean_T rtu_bit2, boolean_T rtu_bit3,
    boolean_T rtu_valid, a380_pitch_efcs_law *rty_law);
  static void A380PrimComputerFctl_MATLABFunction_k_Reset(rtDW_MATLABFunction_A380PrimComputerFctl_a_T *localDW);
  static void A380PrimComputerFctl_MATLABFunction_n(boolean_T rtu_u, real_T rtu_Ts, boolean_T rtu_isRisingEdge, real_T
    rtu_timeDelay, boolean_T *rty_y, rtDW_MATLABFunction_A380PrimComputerFctl_a_T *localDW);
  static void A380PrimComputerFctl_CalculateV_alpha_max(real_T rtu_v_ias, real_T rtu_alpha, real_T rtu_alpha_0, real_T
    rtu_alpha_target, real_T *rty_V_alpha_target);
  static void A380PrimComputerFctl_GetIASforMach4(real_T rtu_m, real_T rtu_m_t, real_T rtu_v, real_T *rty_v_t);
  static void A380PrimComputerFctl_MATLABFunction_c(const base_arinc_429 *rtu_u, boolean_T *rty_y);
  static void A380PrimComputerFctl_MATLABFunction_gr(const boolean_T rtu_u[19], real32_T *rty_y);
  static void A380PrimComputerFctl_MATLABFunction_h(a380_pitch_efcs_law rtu_law, boolean_T *rty_bit1, boolean_T
    *rty_bit2, boolean_T *rty_bit3);
  static void A380PrimComputerFctl_MATLABFunction2(a380_lateral_efcs_law rtu_law, boolean_T *rty_bit1, boolean_T
    *rty_bit2);
  A380LateralDirectLaw LawMDLOBJ1;
  A380LateralNormalLaw LawMDLOBJ2;
  A380PitchAlternateLaw LawMDLOBJ3;
  A380PitchDirectLaw LawMDLOBJ4;
  A380PitchNormalLaw LawMDLOBJ5;
};

#endif

