// Copyright (c) 2022 FlyByWire Simulations
// SPDX-License-Identifier: GPL-3.0

#ifndef FLYBYWIRE_UNITS_H
#define FLYBYWIRE_UNITS_H

#include <map>
#include <string>
#include <utility>

#include <MSFS/Legacy/gauges.h>

#include "logging.h"

/**
 * Helper struct representing one unit
 */
struct Unit {
public:
  const char* name;
  const ENUM id;
  [[maybe_unused]]
  explicit Unit(const char* nameInSim) : name(nameInSim), id(get_units_enum(name)) {
    // LOG_INFO("Unit::Unit() " + std::string(name) + " = " + std::to_string(id));
  }
};

/**
 * The Units class is a helper class to make handling of MSFS SDK units easier.
 * Add any additional required units here as the MSFS SDK has many more.
 */
class Units {
public:
  // Selected commonly used units

  const Unit None{""}; // special case for no unit (e.g. in conjunction with a data type)
  const Unit Bool{"Bool"};
  const Unit Celsius{"Celsius"};
  const Unit Feet{"Feet"};
  const Unit FeetMin{"feet/minute"};
  const Unit FeetSec{"feet/second"};
  const Unit FeetSecSquared{"feet per second squared"};
  const Unit FootPounds{"Foot pounds"};
  const Unit Gallons{"Gallons"};
  const Unit Hours{"Hours"};
  const Unit Mach{"Mach"};
  const Unit Millibars{"Millibars"};
  const Unit Minutes{"Minutes"};
  const Unit Number{"Number"};
  const Unit Percent{"Percent"};
  const Unit PercentOver100{"Percent over 100"};
  const Unit Pounds{"Pounds"};
  const Unit Pph{"Pounds per hour"};
  const Unit Psi{"Psi"};
  const Unit Rad{"radians"};
  const Unit RadSec{"radians per second"};
  const Unit RadSecSquared{"radians per second squared"};
  const Unit Seconds{"Seconds"};

  // All units taken from the MSFS SDK Examples SimWatcher
  const Unit Bco16{"Bco16"};
  const Unit Bool_{"Bool"};
  const Unit Boolean{"Boolean"};
  const Unit Enum{"Enum"};
  const Unit Frequency_ADF_BCD32{"Frequency ADF BCD32"};
  const Unit Frequency_BCD16{"Frequency BCD16"};
  const Unit Frequency_BCD32{"Frequency BCD32"};
  const Unit GForce{"GForce"};
  const Unit GLOBALP_delta_heading_rate{"GLOBALP->delta_heading_rate"};
  const Unit GLOBALP_eng1_manifold_pressure{"GLOBALP->eng1.manifold_pressure"};
  const Unit GLOBALP_eng1_oil_prs{"GLOBALP->eng1.oil_prs"};
  const Unit GLOBALP_eng1_oil_tmp{"GLOBALP->eng1.oil_tmp"};
  const Unit GLOBALP_vertical_speed{"GLOBALP->vertical_speed"};
  const Unit G_Force_624_scaled{"G Force 624 scaled"};
  const Unit G_Force{"G Force"};
  const Unit Hertz{"Hertz"};
  const Unit Hz{"Hz"};
  const Unit KHz{"KHz"};
  const Unit KgFSqCm{"KgFSqCm"};
  const Unit Kilohertz{"Kilohertz"};
  const Unit MHz{"MHz"};
  const Unit Megahertz{"Megahertz"};
  const Unit Nm{"Nm"};
  const Unit Pa{"Pa"};
  const Unit Slug_ft3{"Slug/ft3"};
  const Unit Slug_per_cubic_feet{"Slug per cubic feet"};
  const Unit Slug_per_cubic_foot{"Slug per cubic foot"};
  const Unit Slugs_per_cubic_feet{"Slugs per cubic feet"};
  const Unit Slugs_per_cubic_foot{"Slugs per cubic foot"};
  const Unit Watts{"Watts"};
  const Unit Watt{"Watt"};
  const Unit amperes{"amperes"};
  const Unit ampere{"ampere"};
  const Unit amps{"amps"};
  const Unit amp{"amp"};
  const Unit angl16{"angl16"};
  const Unit angl32{"angl32"};
  const Unit atmospheres{"atmospheres"};
  const Unit atmosphere{"atmosphere"};
  const Unit atm{"atm"};
  const Unit bars{"bars"};
  const Unit bar{"bar"};
  const Unit bels{"bels"};
  const Unit bel{"bel"};
  const Unit boost_cmHg{"boost cmHg"};
  const Unit boost_inHg{"boost inHg"};
  const Unit boost_psi{"boost psi"};
  const Unit celsius_fs7_egt{"celsius fs7 egt"};
  const Unit celsius_fs7_oil_temp{"celsius fs7 oil temp"};
  const Unit celsius_scaler_16k{"celsius scaler 16k"};
  const Unit celsius_scaler_1_256{"celsius scaler 1/256"};
  const Unit celsius_scaler_256{"celsius scaler 256"};
  const Unit celsius{"celsius"};
  const Unit centimeter_of_mercury{"centimeter of mercury"};
  const Unit centimeters_of_mercury{"centimeters of mercury"};
  const Unit centimeters{"centimeters"};
  const Unit centimeter{"centimeter"};
  const Unit cm2{"cm2"};
  const Unit cm3{"cm3"};
  const Unit cmHg{"cmHg"};
  const Unit cm{"cm"};
  const Unit cu_cm{"cu cm"};
  const Unit cu_ft{"cu ft"};
  const Unit cu_in{"cu in"};
  const Unit cu_km{"cu km"};
  const Unit cu_mm{"cu mm"};
  const Unit cu_m{"cu m"};
  const Unit cu_yd{"cu yd"};
  const Unit cubic_centimeters{"cubic centimeters"};
  const Unit cubic_centimeter{"cubic centimeter"};
  const Unit cubic_feet{"cubic feet"};
  const Unit cubic_foot{"cubic foot"};
  const Unit cubic_inches{"cubic inches"};
  const Unit cubic_inch{"cubic inch"};
  const Unit cubic_kilometers{"cubic kilometers"};
  const Unit cubic_kilometer{"cubic kilometer"};
  const Unit cubic_meters{"cubic meters"};
  const Unit cubic_meter{"cubic meter"};
  const Unit cubic_miles{"cubic miles"};
  const Unit cubic_mile{"cubic mile"};
  const Unit cubic_millimeters{"cubic millimeters"};
  const Unit cubic_millimeter{"cubic millimeter"};
  const Unit cubic_yards{"cubic yards"};
  const Unit cubic_yard{"cubic yard"};
  const Unit days{"days"};
  const Unit day{"day"};
  const Unit decibels{"decibels"};
  const Unit decibel{"decibel"};
  const Unit decimiles{"decimiles"};
  const Unit decimile{"decimile"};
  const Unit decinmiles{"decinmiles"};
  const Unit decinmile{"decinmile"};
  const Unit degree_angl16{"degree angl16"};
  const Unit degree_angl32{"degree angl32"};
  const Unit degree_latitude{"degree latitude"};
  const Unit degree_longitude{"degree longitude"};
  const Unit degree_per_second_ang16{"degree per second ang16"};
  const Unit degree_per_second_squared{"degree per second squared"};
  const Unit degree_per_second{"degree per second"};
  const Unit degrees_angl16{"degrees angl16"};
  const Unit degrees_angl32{"degrees angl32"};
  const Unit degrees_latitude{"degrees latitude"};
  const Unit degrees_longitude{"degrees longitude"};
  const Unit degrees_per_second_ang16{"degrees per second ang16"};
  const Unit degrees_per_second_squared{"degrees per second squared"};
  const Unit degrees_per_second{"degrees per second"};
  const Unit degrees{"degrees"};
  const Unit degree{"degree"};
  const Unit fahrenheit{"fahrenheit"};
  const Unit farenheit{"farenheit"};
  const Unit feet_minute{"feet/minute"};
  const Unit feet_per_minute{"feet per minute"};
  const Unit feet_per_second_squared{"feet per second squared"};
  const Unit feet_per_second{"feet per second"};
  const Unit feet_second{"feet/second"};
  const Unit feet{"feet"};
  const Unit flags{"flags"};
  const Unit foot_per_second_squared{"foot per second squared"};
  const Unit foot_pound_{"foot-pound"};
  const Unit foot_pounds_{"foot pounds"};
  const Unit foot_pounds{"foot-pounds"};
  const Unit foot_pound{"foot pound"};
  const Unit foot{"foot"};
  const Unit fs7_charging_amps{"fs7 charging amps"};
  const Unit fs7_oil_quantity{"fs7 oil quantity"};
  const Unit ft2{"ft2"};
  const Unit ft3{"ft3"};
  const Unit ft_lb_per_second{"ft lb per second"};
  const Unit ft_lbs{"ft-lbs"};
  const Unit ft_min{"ft/min"};
  const Unit ft{"ft"};
  const Unit gallon_per_hour{"gallon per hour"};
  const Unit gallons_per_hour{"gallons per hour"};
  const Unit gallons{"gallons"};
  const Unit gallon{"gallon"};
  const Unit geepounds{"geepounds"};
  const Unit geepound{"geepound"};
  const Unit gph{"gph"};
  const Unit grads{"grads"};
  const Unit grad{"grad"};
  const Unit halfs{"halfs"};
  const Unit half{"half"};
  const Unit hectopascals{"hectopascals"};
  const Unit hectopascal{"hectopascal"};
  const Unit hour_over_10{"hour over 10"};
  const Unit hours_over_10{"hours over 10"};
  const Unit hours{"hours"};
  const Unit hour{"hour"};
  const Unit in2{"in2"};
  const Unit in3{"in3"};
  const Unit inHg_64_over_64k{"inHg 64 over 64k"};
  const Unit inHg{"inHg"};
  const Unit inch_of_mercury{"inch of mercury"};
  const Unit inches_of_mercury{"inches of mercury"};
  const Unit inches{"inches"};
  const Unit inch{"inch"};
  const Unit in{"in"};
  const Unit kPa{"kPa"};
  const Unit kelvin{"kelvin"};
  const Unit keyframes{"keyframes"};
  const Unit keyframe{"keyframe"};
  const Unit kgf_meters{"kgf meters"};
  const Unit kgf_meter{"kgf meter"};
  const Unit kg{"kg"};
  const Unit kilogram_force_per_square_centime{"kilogram force per square centimeter"};
  const Unit kilogram_meter_squared{"kilogram meter squared"};
  const Unit kilogram_meters{"kilogram meters"};
  const Unit kilogram_meter{"kilogram meter"};
  const Unit kilogram_per_cubic_meter{"kilogram per cubic meter"};
  const Unit kilogram_per_second{"kilogram per second"};
  const Unit kilograms_meter_squared{"kilograms meter squared"};
  const Unit kilograms_per_cubic_meter{"kilograms per cubic meter"};
  const Unit kilograms_per_second{"kilograms per second"};
  const Unit kilograms{"kilograms"};
  const Unit kilogram{"kilogram"};
  const Unit kilometer_hour{"kilometer/hour"};
  const Unit kilometer_per_hour{"kilometer per hour"};
  const Unit kilometers_hour{"kilometers/hour"};
  const Unit kilometers_per_hour{"kilometers per hour"};
  const Unit kilometers{"kilometers"};
  const Unit kilometer{"kilometer"};
  const Unit kilopascal{"kilopascal"};
  const Unit km2{"km2"};
  const Unit km3{"km3"};
  const Unit km{"km"};
  const Unit knot_scaler_128{"knot scaler 128"};
  const Unit knots_scaler_128{"knots scaler 128"};
  const Unit knots{"knots"};
  const Unit knot{"knot"};
  const Unit kph{"kph"};
  const Unit lbf_feet{"lbf-feet"};
  const Unit lbs{"lbs"};
  const Unit liter_per_hour{"liter per hour"};
  const Unit liters_per_hour{"liters per hour"};
  const Unit liters{"liters"};
  const Unit liter{"liter"};
  const Unit m2{"m2"};
  const Unit m3{"m3"};
  const Unit m_s{"m/s"};
  const Unit mach_3d2_over_64k{"mach 3d2 over 64k"};
  const Unit machs{"machs"};
  const Unit mach{"mach"};
  const Unit mask{"mask"};
  const Unit mbars{"mbars"};
  const Unit mbar{"mbar"};
  const Unit meter_cubed_per_second{"meter cubed per second"};
  const Unit meter_cubed{"meter cubed"};
  const Unit meter_latitude{"meter latitude"};
  const Unit meter_per_minute{"meter per minute"};
  const Unit meter_per_second_scaler_256{"meter per second scaler 256"};
  const Unit meter_per_second_squared{"meter per second squared"};
  const Unit meter_per_second{"meter per second"};
  const Unit meter_scaler_256{"meter scaler 256"};
  const Unit meter_second{"meter/second"};
  const Unit meters_cubed_per_second{"meters cubed per second"};
  const Unit meters_cubed{"meters cubed"};
  const Unit meters_latitude{"meters latitude"};
  const Unit meters_per_minute{"meters per minute"};
  const Unit meters_per_second_scaler_256{"meters per second scaler 256"};
  const Unit meters_per_second_squared{"meters per second squared"};
  const Unit meters_per_second{"meters per second"};
  const Unit meters_scaler_256{"meters scaler 256"};
  const Unit meters_second{"meters/second"};
  const Unit meters{"meters"};
  const Unit meter{"meter"};
  const Unit mile_per_hour{"mile per hour"};
  const Unit miles_per_hour{"miles per hour"};
  const Unit miles{"miles"};
  const Unit mile{"mile"};
  const Unit millibar_scaler_16{"millibar scaler 16"};
  const Unit millibars_scaler_16{"millibars scaler 16"};
  const Unit millibars{"millibars"};
  const Unit millibar{"millibar"};
  const Unit millimeter_of_mercury{"millimeter of mercury"};
  const Unit millimeter_of_water{"millimeter of water"};
  const Unit millimeters_of_mercury{"millimeters of mercury"};
  const Unit millimeters_of_water{"millimeters of water"};
  const Unit millimeters{"millimeters"};
  const Unit millimeter{"millimeter"};
  const Unit minute_per_round{"minute per round"};
  const Unit minutes_per_round{"minutes per round"};
  const Unit minutes{"minutes"};
  const Unit minute{"minute"};
  const Unit mm2{"mm2"};
  const Unit mm3{"mm3"};
  const Unit mmHg{"mmHg"};
  const Unit more_than_a_half{"more_than_a_half"};
  const Unit mph{"mph"};
  const Unit m{"m"};
  const Unit nautical_miles{"nautical miles"};
  const Unit nautical_mile{"nautical mile"};
  const Unit newton_meters{"newton meters"};
  const Unit newton_meter{"newton meter"};
  const Unit newton_per_square_meter{"newton per square meter"};
  const Unit newtons_per_square_meter{"newtons per square meter"};
  const Unit nice_minute_per_round{"nice minute per round"};
  const Unit nice_minutes_per_round{"nice minutes per round"};
  const Unit nmiles{"nmiles"};
  const Unit nmile{"nmile"};
  const Unit numbers_{"numbers"};
  const Unit number{"number"};
  const Unit part{"part"};
  const Unit pascals{"pascals"};
  const Unit pascal{"pascal"};
  const Unit per_degree{"per degree"};
  const Unit per_hour{"per hour"};
  const Unit per_minute{"per minute"};
  const Unit per_radian{"per radian"};
  const Unit per_second{"per second"};
  const Unit percent_over_100{"percent over 100"};
  const Unit percent_scaler_16k{"percent scaler 16k"};
  const Unit percent_scaler_2pow23{"percent scaler 2pow23"};
  const Unit percent_scaler_32k{"percent scaler 32k"};
  const Unit percentage{"percentage"};
  const Unit percent{"percent"};
  const Unit position_128{"position 128"};
  const Unit position_16k{"position 16k"};
  const Unit position_32k{"position 32k"};
  const Unit position{"position"};
  const Unit pound_force_per_square_foot{"pound-force per square foot"};
  const Unit pound_force_per_square_inch{"pound-force per square inch"};
  const Unit pound_per_hour{"pound per hour"};
  const Unit pound_scaler_256{"pound scaler 256"};
  const Unit poundal_feet{"poundal feet"};
  const Unit pounds_per_hour{"pounds per hour"};
  const Unit pounds_scaler_256{"pounds scaler 256"};
  const Unit pounds{"pounds"};
  const Unit pound{"pound"};
  const Unit pph{"pph"};
  const Unit psf_scaler_16k{"psf scaler 16k"};
  const Unit psf{"psf"};
  const Unit psi_4_over_16k{"psi 4 over 16k"};
  const Unit psi_fs7_oil_pressure{"psi fs7 oil pressure"};
  const Unit psi_scaler_16k{"psi scaler 16k"};
  const Unit psi{"psi"};
  const Unit quarts{"quarts"};
  const Unit quart{"quart"};
  const Unit radian_per_second_squared{"radian per second squared"};
  const Unit radian_per_second{"radian per second"};
  const Unit radians_per_second_squared{"radians per second squared"};
  const Unit radians_per_second{"radians per second"};
  const Unit radians{"radians"};
  const Unit radian{"radian"};
  const Unit rankine{"rankine"};
  const Unit ratio{"ratio"};
  const Unit revolution_per_minute{"revolution per minute"};
  const Unit revolutions_per_minute{"revolutions per minute"};
  const Unit rounds{"rounds"};
  const Unit round{"round"};
  const Unit rpm_1_over_16k{"rpm 1 over 16k"};
  const Unit rpms{"rpms"};
  const Unit rpm{"rpm"};
  const Unit scaler{"scaler"};
  const Unit seconds{"seconds"};
  const Unit second{"second"};
  const Unit slug_feet_squared{"slug feet squared"};
  const Unit slugs_feet_squared{"slugs feet squared"};
  const Unit slugs{"slugs"};
  const Unit slug{"slug"};
  const Unit sq_cm{"sq cm"};
  const Unit sq_ft{"sq ft"};
  const Unit sq_in{"sq in"};
  const Unit sq_km{"sq km"};
  const Unit sq_mm{"sq mm"};
  const Unit sq_m{"sq m"};
  const Unit sq_yd{"sq yd"};
  const Unit square_centimeters{"square centimeters"};
  const Unit square_centimeter{"square centimeter"};
  const Unit square_feet{"square feet"};
  const Unit square_foot{"square foot"};
  const Unit square_inches{"square inches"};
  const Unit square_inch{"square inch"};
  const Unit square_kilometers{"square kilometers"};
  const Unit square_kilometer{"square kilometer"};
  const Unit square_meters{"square meters"};
  const Unit square_meter{"square meter"};
  const Unit square_miles{"square miles"};
  const Unit square_mile{"square mile"};
  const Unit square_millimeters{"square millimeters"};
  const Unit square_millimeter{"square millimeter"};
  const Unit square_yards{"square yards"};
  const Unit square_yard{"square yard"};
  const Unit thirds{"thirds"};
  const Unit third{"third"};
  const Unit times{"times"};
  const Unit volts{"volts"};
  const Unit volt{"volt"};
  const Unit yards{"yards"};
  const Unit yard{"yard"};
  const Unit yd2{"yd2"};
  const Unit yd3{"yd3"};
  const Unit years{"years"};
  const Unit year{"year"};
};

// Global instance of the Units class
inline Units UNITS{};

#endif //FLYBYWIRE_UNITS_H
