export const ptuArray = [
    {
        scenario: 'PTU-off',
        format: [
            {
                id: 'ptu1',
                className: 'Hide',
                colour: '',
                orientation: 0,
                fill: 0,
            },
            {
                id: 'ptu2',
                className: 'AmberLine',
                colour: '',
                orientation: 0,
                fill: 0,
            },
            {
                id: 'ptu3',
                className: 'AmberLine NoFill',
                colour: '',
                orientation: 0,
                fill: 0,
            },
            {
                id: 'ptu4',
                className: 'AmberLine',
                colour: '',
                orientation: 0,
                fill: 0,
            },
            {
                id: 'ptu5',
                className: 'Hide',
                colour: '',
                orientation: 0,
                fill: 0,
            },
            {
                id: 'triangle1',
                className: '',
                colour: 'Amber',
                orientation: -90,
                fill: 0,
            },
            {
                id: 'triangle2',
                className: '',
                colour: 'Amber',
                orientation: -90,
                fill: 0,
            },
            {
                id: 'triangle3',
                className: '',
                colour: 'Amber',
                orientation: 90,
                fill: 0,
            },
        ],
    },
    {
        scenario: 'normal',
        format: [
            {
                id: 'ptu1',
                className: 'Hide',
                colour: '',
                orientation: 0,
                fill: 0,
            },
            {
                id: 'ptu2',
                className: 'GreenLine',
                colour: '',
                orientation: 0,
                fill: 0,
            },
            {
                id: 'ptu3',
                className: 'GreenLine NoFill',
                colour: '',
                orientation: 0,
                fill: 0,
            },
            {
                id: 'ptu4',
                className: 'GreenLine',
                colour: '',
                orientation: 0,
                fill: 0,
            },
            {
                id: 'ptu5',
                className: 'GreenLine Hide',
                colour: '',
                orientation: 0,
                fill: 0,
            },
            {
                id: 'triangle1',
                className: '',
                colour: 'Green',
                orientation: -90,
                fill: 0,
            },
            {
                id: 'triangle2',
                className: '',
                colour: 'Green',
                orientation: -90,
                fill: 0,
            },
            {
                id: 'triangle3',
                className: '',
                colour: 'Green',
                orientation: 90,
                fill: 0,
            },
        ],
    },
    {
        scenario: 'right-to-left',
        format: [
            {
                id: 'ptu1',
                className: 'GreenLine',
                colour: '',
                orientation: 0,
                fill: 0,
            },
            {
                id: 'ptu2',
                className: 'GreenLine',
                colour: '',
                orientation: 0,
                fill: 0,
            },
            {
                id: 'ptu3',
                className: 'GreenLine NoFill',
                colour: '',
                orientation: 0,
                fill: 0,
            },
            {
                id: 'ptu4',
                className: 'GreenLine',
                colour: '',
                orientation: 0,
                fill: 0,
            },
            {
                id: 'ptu5',
                className: 'GreenLine',
                colour: '',
                orientation: 0,
                fill: 0,
            },
            {
                id: 'triangle1',
                className: 'FillGreen',
                colour: 'Green',
                orientation: -90,
                fill: 1,
            },
            {
                id: 'triangle2',
                className: 'FillGreen',
                colour: 'Green',
                orientation: -90,
                fill: 1,
            },
            {
                id: 'triangle3',
                className: 'FillGreen',
                colour: 'Green',
                orientation: -90,
                fill: 1,
            },
        ],
    },
    {
        scenario: 'left-to-right',
        format: [
            {
                id: 'ptu1',
                className: 'GreenLine',
                colour: '',
                orientation: 0,
                fill: 0,
            },
            {
                id: 'ptu2',
                className: 'GreenLine',
                colour: '',
                orientation: 0,
                fill: 0,
            },
            {
                id: 'ptu3',
                className: 'GreenLine NoFill',
                colour: '',
                orientation: 0,
                fill: 0,
            },
            {
                id: 'ptu4',
                className: 'GreenLine',
                colour: '',
                orientation: 0,
                fill: 0,
            },
            {
                id: 'ptu5',
                className: 'GreenLine',
                colour: '',
                orientation: 0,
                fill: 0,
            },
            {
                id: 'triangle1',
                className: 'FillGreen',
                colour: 'Green',
                orientation: 90,
                fill: 1,
            },
            {
                id: 'triangle2',
                className: 'FillGreen',
                colour: 'Green',
                orientation: 90,
                fill: 1,
            },
            {
                id: 'triangle3',
                className: 'FillGreen',
                colour: 'Green',
                orientation: 90,
                fill: 1,
            },
        ],
    },
];

export const levels = [
    { system: 'GREEN', max: 14.5, low: 3.5, norm: 2.6 },
    { system: 'BLUE', max: 6.5, low: 2.4, norm: 1.6 },
    { system: 'YELLOW', max: 12.5, low: 3.5, norm: 2.6 },
];
